### PR TITLE
Anti flood for game commands; fix #753

### LINKED ISSUE #753: Abuse: Token Generation
Currently, there are multiple users who, when they lose, start swearing and making 1000s of tokens to crash their opponents.

While we can't stop them from swearing, the token issue is something I don't want to be a problem. My idea is to have a `TABLE_MAX_CARDS` option and that option cannot be exceeded (if someone tries to play/make a new card when the table is at max, it will return it to its prior location and/or return false (for creating cards).

Opinions on this?

### PR DESCRIPTION
**Pull request by ctrlaltca**
Mitigates #753 and any similar DOS based on sending a lot of commands from an user inside a game.
We already had an antiflood for messages in rooms, but not for game commands in a game.
No timers have been added, so it should not weight a lot on performance.
The default settings is max 10 commands in (the last) 10 seconds, the same for room messages.
I suppose that after some testing we'll end up with an higher limit, but i'd like to hear other opinions on this.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I'd love to test this. Can you set it up on the backup and/or testing server, @woogerboy21 ?

**Comment by tooomm** [comment]
I see some problems with fast live changes if you right-click many times on your life counter to get -10 for example.
Many people use this instead the direct changes.

**Comment by ctrlaltca** [comment]
Should we implement a whitelist of commands that doesn't trigger the antiflood or, vice versa, a blacklist?

**Comment by woogerboy21** [comment]
@tooomm isnt there a way to set your life total rather than clicking so many times?  I understand its a user behavior change but just want to make sure there is an alternate method that if they run into a timing issue with the first few implementations of something like this the users can still play on.

**Comment by woogerboy21** [comment]
@ctrlaltca should we set the number of commands as a server option in the config so it can be changed on the fly / if need be?  Thoughts.  I don't see that happening that often but its a thought.

**Comment by woogerboy21** [comment]
@ZeldaZach This is now running on the testing server.

**Comment by woogerboy21** [comment]
The first thing I noticed, there is no notification of the anti-flood kicking in.  Should there be something in the chat portion of the game area saying something about it?

**Comment by tooomm** [comment]
@woogerboy21 there is. you can right click on the battlefield and use "Couters" --> "life" ...
I needed to search for it first, hehe. I knew about it, but was not sure where it was. :)
Since there are also hotkeys for +1 (F12) and -1 (F11) that's easy and fast to use. I use it myself all the time (well, I click... :) ), even for bigger life swings.

**Comment by ZeldaZach** [comment]
@ctrlaltca Ok, so after my initial test I really like how this is going. It prevents the flood of tokens and such, but I'd like to see the following changes:

We should restrict this to a list of "limiting actions" (aka actions that could be potentially used for flood) because while testing I couldn't, for instance, make major life changes doing the +1/-1 methods nor draw cards one by one (such as if I resolved a big sphinx rev)...

Does anybody else have any thoughts on this?

**Comment by tooomm** [comment]
If there are white/blacklists you always need to care and adjust. But we can't solve all edge cases and things people might exploit.
I think it would be better to find a general value.

@ZeldaZach when you don't limit life changes for example, people can unrestrictedly spam (flood) the chat log with like 30 different life gain/loss actions in a few seconds, that's annoying as well and makes the game a pain. You can hardly verify their plays, too. *There should be a limit for all and every action if excessively & repeatedly used in short time.*

<br>
If there is going to be a notification about the flood-protection people know that they have to wait like 5s to draw their missing cards. That's a rare case and no big deal.
Apart from that, we can still try to support things like the alternative way to apply changes to your life counter in a better way to make its use easier. (see my post above)

**Comment by ZeldaZach** [comment]
You can change your life easily through the `CTRL & L` command, just people don't use it a lot. Similar to the `CTRL & E` command to draw a certain # of cards.

The goal of this commit is to prevent someone from crashing another individual through legal actions the client would allow them to do. Filling the chat log with nonsense is an issue I'm not really worried about at this time.

**Comment by tooomm** [comment]
True point. Still something we can be aware of (and fix with this same commit).

I know about the card drawing since it's kinda easy to find and you happen to right click on your library from time to time. :P

**Comment by poixen** [comment]
When looking at the code a few weeks ago I learnt you can mouse wheel click on life/mana to set the value. I use it all the Time now. Spread the word!

**Comment by ZeldaZach** [comment]
@poixen I never knew that... you rock :smile:

**Comment by Daenyth** [comment]
Wow, I didn't even know that. We should add a note somewhere in the wiki

**Comment by Daenyth** [comment]
The server code looks good, but I agree, Cockatrice should handle the RespChatFlood response to game commands.

**Comment by tooomm** [comment]
@Daenyth I added that to the shortcuts wiki already. But just in the under construction part.

**Comment by ctrlaltca** [comment]
User notification message has been added, the same as the existing chat flood message with s/chat/game/ : "You are flooding the game. Please wait a couple of seconds."

Whitelist for harmless commands have been added, with an initial list of whitelisted commands that you can find here: https://github.com/Cockatrice/Cockatrice/pull/829/files#diff-d3b638a03e1222b79c2b7b5b8935096fR187

New translations strings have been extracted and added to the english translation file.

**Comment by woogerboy21** [comment]
nice.  we should definitely get this test out :+1:

**Comment by ZeldaZach** [comment]
Can you get it up on the testing @woogerboy21

**Comment by ZeldaZach** [comment]
Btw, @ctrlaltca , is it possible to incorporate the desktop notifications messages into this for the alerts of too fast, and default to in game message if desktop notifications are off?

**Comment by woogerboy21** [comment]
@ZeldaZach This is now on the testing server.

**Comment by ctrlaltca** [comment]
@ZeldaZach i'm not sure i understand what you mean. Only the user flooding the game gets the "you're flooding the game message", and since he's sending commands to a game, its cockatrice window will be the active window, so no desktop notification is needed.

**Comment by tooomm** [comment]
Will the message be something like the kick-window or just a message line in the chat log?

**Comment by ctrlaltca** [comment]
Just a message line in the chat log (actually, one per each command discarded by the flood protection).

**Comment by tooomm** [comment]
So you just spam yourself in the chat if you don't stop creating new tokens. :+1:  :)

**Comment by Daenyth** [comment]
Perfect

File: cockatrice/src/tab_game.cpp [hunk 1]
```diff
@@ -837,6 +837,8 @@ void TabGame::sendGameCommand(PendingCommand *pend, int playerId)
     AbstractClient *client = getClientForPlayer(playerId);
     if (!client)
         return;
+
+    connect(pend, SIGNAL(finished(Response, CommandContainer, QVariant)), this, SLOT(commandFinished(const Response &)));
```
Comment (Daenyth) [inline cockatrice/src/tab_game.cpp]: Aren't you connecting this signal twice? Once here and once in the method calling this one? Can you explain?

File: common/server_protocolhandler.cpp [hunk 2]
```diff
@@ -184,6 +184,18 @@ Response::ResponseCode Server_ProtocolHandler::processRoomCommandContainer(const
 
 Response::ResponseCode Server_ProtocolHandler::processGameCommandContainer(const CommandContainer &cont, ResponseContainer &rc)
 {
+    static QList<GameCommand::GameCommandType> antifloodCommandsWhiteList = QList<GameCommand::GameCommandType>()
```
Comment (Daenyth) [inline common/server_protocolhandler.cpp]: Since this is static why not move it into a private member field? As written you will create a new object every single time the server handles a game command

File: servatrice/src/servatrice.h [hunk 3]
```diff
@@ -143,6 +143,8 @@ public slots:
 	int getMaxMessageCountPerInterval() const { return maxMessageCountPerInterval; }
 	int getMaxMessageSizePerInterval() const { return maxMessageSizePerInterval; }
 	int getMaxGamesPerUser() const { return maxGamesPerUser; }
+    int getCommandCountingInterval() const { return commandCountingInterval; }
+    int getMaxCommandCountPerInterval() const { return maxCommandCountPerInterval; }
```
Comment (Daenyth) [inline servatrice/src/servatrice.h]: Whitespace

File: cockatrice/src/tab_game.cpp (hunk 1 above)
Comment (ctrlaltca) [inline cockatrice/src/tab_game.cpp]: in TabGame there are two different sendGameCommand implementations, the first taking a PendingCommand* parameter and the second taking a google::protobuf::Message& parameter. They are called from different places, but they never call one eachother.

File: common/server_protocolhandler.cpp (hunk 2 above)
Comment (ctrlaltca) [inline common/server_protocolhandler.cpp]: IIRC, a static variable in a class method will be allocated on the class and initialized only one, the first time the method gets executed.
I wrote a quick test for this, and it seems it's working as i expected: https://gist.github.com/ctrlaltca/7561aaa1ed6fae2e368e

Anyway, the reason why i didn't declare this variable as a class member in the .h is that it would force to add an ```#include "pb/commands.pb.h"``` in the .h, so every time a command gets modified it would force a recompilation of all the files including server_protocolhandler.h and so on.

File: servatrice/src/servatrice.h (hunk 3 above)
Comment (ctrlaltca) [inline servatrice/src/servatrice.h]: The whole file is tab-indented, and i didn't want to pollute the commit. Other files in servatrice are tab-indented, i thought we'd prefer to address all these tab->spaces in an ad-hoc commit, if it's ok for you.

Comment (Daenyth) [inline servatrice/src/servatrice.h]: That's fine then, carry on

File: common/server_protocolhandler.cpp (hunk 2 above)
Comment (Daenyth) [inline common/server_protocolhandler.cpp]: OK, that makes sense. I wasn't familiar with those semantics in C++. :+1:

File: cockatrice/src/tab_game.cpp (hunk 1 above)
Comment (Daenyth) [inline cockatrice/src/tab_game.cpp]: Got it, thanks.

**Comment by Daenyth** [comment]
:shipit: pending merge conflict fixes

**Comment by ctrlaltca** [comment]
Reverted the translation file change that was causating merge conflict
