### PR TITLE
[TabGame] Fix dangling PlayerMenus in gameMenu

### LINKED ISSUE #6209: players rejoining games duplicate their entry in the game menu
**System Information:**

current master version

_______________________________________________________________________________________

Image

_______________________________________________________________________________________

**Steps to reproduce:**
 - create a local server
 - start client a, join server and create game
 - start client b, join server and join a's game
 - disconnect client b
 - reconnect client b
 - client a will now have two instances of client b's user in the menu

### PR DESCRIPTION
**Pull request by BruebachL**
## Related Ticket(s)
- Fixes #6209

## Short roundup of the initial problem
When we insert the playerMenu into the gameMenu, Qt wraps the playerMenu into a QAction*, which lives
independently and does not get cleaned up when the source menu gets destroyed. We have to manually clean up the QAction*.

## What will change with this Pull Request?
- Have playerManager actually delete Players
- Also clean up the gameMenu as described above.

### CODE REVIEW

File: cockatrice/src/tabs/tab_game.cpp [hunk 1]
```diff
@@ -707,6 +699,31 @@ void TabGame::addLocalPlayer(Player *newPlayer, int playerId)
...
 }
 
+void TabGame::processPlayerLeave(Player *leavingPlayer)
+{
+    QString playerName = "@" + leavingPlayer->getPlayerInfo()->getName();
+    removePlayerFromAutoCompleteList(playerName);
+
+    scene->removePlayer(leavingPlayer);
+
+    // When we inserted the playerMenu into the gameMenu earlier, Qt wrapped the playerMenu into a QAction*, which lives
```
Comment (ebbit1q) [inline cockatrice/src/tabs/tab_game.cpp:709]: is there a way we can simplify this by adding this as a property somewhere?

Comment (BruebachL) [reply cockatrice/src/tabs/tab_game.cpp:709]: There's no reason we can't eventually refactor the gameMenu out of TabGame and then simply have it populate the playerList dynamically like the playerMenu does in #6214. This works for now, imo, ahead of a proper refactor.

Comment (ebbit1q) [reply cockatrice/src/tabs/tab_game.cpp:709]: sure, this is a crash so we should prioritize fixing it
