### PR TITLE
Fix local mention crash

### LINKED ISSUE #1192: Local game chat crash
How to reproduce: In a local game, type any message containing the character '@' (and press enter) and the application will crash. 

As far as I can tell, the allUsersList pointer doesn't exist because you can't be connected to a server (thus having loaded the TabUserList) and be in a local game at the same time.

This should crash on every version since 27fa6eb.

```
Call Stack:
	cockatrice.exe!TabUserLists::getAllUsersList() Line 49	C++
	cockatrice.exe!ChatView::appendMessage(QString message, QString sender, QFlags<enum ServerInfo_User_UserLevelFlag> userLevel, bool playerBold) Line 301	C++
	cockatrice.exe!MessageLogWidget::logSay(Player * player, QString message) Line 166	C++
	cockatrice.exe!MessageLogWidget::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 292	C++
	Qt5Cored.dll!66550369()	Unknown
	[Frames below may be incorrect and/or missing, no symbols loaded for Qt5Cored.dll]	
	Qt5Cored.dll!6654fdb1()	Unknown
	cockatrice.exe!Player::logSay(Player * _t1, QString _t2) Line 925	C++
	cockatrice.exe!Player::eventGameSay(const Event_GameSay & event) Line 1152	C++
	cockatrice.exe!Player::processGameEvent(GameEvent_GameEventType type, const GameEvent & event, const GameEventContext & context) Line 1534	C++
	cockatrice.exe!TabGame::processGameEventContainer(const GameEventContainer & cont, AbstractClient * client) Line 780	C++
	cockatrice.exe!TabSupervisor::processGameEventContainer(const GameEventContainer & cont) Line 500	C++
	cockatrice.exe!TabSupervisor::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 295	C++
	Qt5Cored.dll!66550369()	Unknown
	Qt5Cored.dll!6654fdb1()	Unknown
	cockatrice.exe!AbstractClient::gameEventContainerReceived(const GameEventContainer & _t1) Line 411	C++
	cockatrice.exe!AbstractClient::processProtocolItem(const ServerMessage & item) Line 91	C++
	cockatrice.exe!LocalClient::itemFromServer(const ServerMessage & item) Line 32	C++
	cockatrice.exe!LocalClient::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 75	C++
	Qt5Cored.dll!66550369()	Unknown
	Qt5Cored.dll!6654fdb1()	Unknown
	cockatrice.exe!LocalServerInterface::itemToClient(const ServerMessage & _t1) Line 136	C++
	cockatrice.exe!LocalServerInterface::transmitProtocolItem(const ServerMessage & item) Line 17	C++
	cockatrice.exe!Server_ProtocolHandler::sendProtocolItem(const GameEventContainer & item) Line 113	C++
	cockatrice.exe!Server_Player::sendGameEvent(const GameEventContainer & cont) Line 1695	C++
	cockatrice.exe!Server_Game::sendGameEventContainer(GameEventContainer * cont, QFlags<enum GameEventStorageItem::EventRecipient> recipients, int privatePlayerId) Line 691	C++
	cockatrice.exe!GameEventStorage::sendToGame(Server_Game * game) Line 63	C++
	cockatrice.exe!Server_ProtocolHandler::processGameCommandContainer(const CommandContainer & cont, ResponseContainer & rc) Line 270	C++
	cockatrice.exe!Server_ProtocolHandler::processCommandContainer(const CommandContainer & cont) Line 327	C++
	cockatrice.exe!LocalServerInterface::itemFromClient(const CommandContainer & item) Line 22	C++
	cockatrice.exe!LocalClient::sendCommandContainer(const CommandContainer & cont) Line 27	C++
	cockatrice.exe!AbstractClient::queuePendingCommand(PendingCommand * pend) Line 128	C++
	cockatrice.exe!AbstractClient::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 215	C++
	Qt5Cored.dll!66550369()	Unknown
	Qt5Cored.dll!6654fdb1()	Unknown
	cockatrice.exe!AbstractClient::sigQueuePendingCommand(PendingCommand * _t1) Line 541	C++
	cockatrice.exe!AbstractClient::sendCommand(PendingCommand * pend) Line 118	C++
	cockatrice.exe!TabGame::sendGameCommand(const google::protobuf::Message & command, int playerId) Line 820	C++
	cockatrice.exe!TabGame::actSay() Line 667	C++
	cockatrice.exe!TabGame::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 466	C++
	Qt5Cored.dll!66550369()	Unknown
	Qt5Cored.dll!6654fdb1()	Unknown
	Qt5Widgetsd.dll!651f9f8a()	Unknown
	Qt5Widgetsd.dll!651f738e()	Unknown
	Qt5Cored.dll!66550369()	Unknown
	Qt5Cored.dll!6654fdb1()	Unknown
	Qt5Widgetsd.dll!654e6cca()	Unknown
	Qt5Widgetsd.dll!652a2b2f()	Unknown
	Qt5Widgetsd.dll!651fa687()	Unknown
	Qt5Widgetsd.dll!6507f0aa()	Unknown
	[External Code]	
	Qt5Widgetsd.dll!6503477e()	Unknown
	Qt5Widgetsd.dll!65030ccd()	Unknown
	Qt5Widgetsd.dll!6501c6fb()	Unknown
	[External Code]	
	Qt5Cored.dll!665057b7()	Unknown
	Qt5Cored.dll!66619318()	Unknown
	Qt5Widgetsd.dll!650b19d7()	Unknown
	Qt5Widgetsd.dll!650b13db()	Unknown
	Qt5Widgetsd.dll!6503477e()	Unknown
	Qt5Widgetsd.dll!65030bd9()	Unknown
	Qt5Cored.dll!6659f6cc()	Unknown
	Qt5Cored.dll!666356f1()	Unknown
	[External Code]	
	Qt5Cored.dll!6659f1a4()	Unknown
	Qt5Guid.dll!0fb20736()	Unknown
	Qt5Guid.dll!0fb1f07a()	Unknown
	Qt5Guid.dll!0fb1f005()	Unknown
	Qt5Cored.dll!665057b7()	Unknown
	Qt5Cored.dll!66619318()	Unknown
	Qt5Guid.dll!0fb3ca12()	Unknown
	Qt5Guid.dll!0fb3e5bb()	Unknown
	Qt5Guid.dll!0fb25beb()	Unknown
	Qt5Guid.dll!0fb202a1()	Unknown
	qwindowsd.dll!QWindowsGuiEventDispatcher::sendPostedEvents() Line 82	C++
	Qt5Cored.dll!6659d7c0()	Unknown
	[External Code]	
	Qt5Cored.dll!6659e30e()	Unknown
	[External Code]	
	Qt5Cored.dll!662590c4()	Unknown
	Qt5Cored.dll!661f27d0()	Unknown
	Qt5Cored.dll!661ed7c3()	Unknown
	Qt5Cored.dll!663da407()	Unknown
	Qt5Cored.dll!664770c5()	Unknown
	[External Code]	
	qwindowsd.dll!QWindowsGuiEventDispatcher::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 73	C++
	Qt5Cored.dll!665015fc()	Unknown
	Qt5Cored.dll!66501802()	Unknown
	Qt5Cored.dll!66503d82()	Unknown
	Qt5Guid.dll!0fb1da24()	Unknown
	Qt5Guid.dll!0fb0c38b()	Unknown
	Qt5Guid.dll!0fb3af68()	Unknown
	Qt5Widgetsd.dll!650306d9()	Unknown
	cockatrice.exe!main(int argc, char * * argv) Line 210	C++
	cockatrice.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 113	C++
	[External Code]	

ebug Output:
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\cockatrice.exe'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\Qt5Multimediad.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\Qt5Networkd.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ws2_32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\nsi.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\Qt5Cored.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\lpk.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\usp10.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\advapi32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mpr.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\icuin53.dll'. Module was built without symbols.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\icuuc53.dll'. Module was built without symbols.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\icudt53.dll'. Module was built without symbols.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcr120.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp120.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp120d.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcr120d.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dnsapi.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\crypt32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msasn1.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\Qt5Guid.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\opengl32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\glu32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ddraw.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dciman32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\setupapi.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cfgmgr32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\devobj.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dwmapi.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\Qt5PrintSupportd.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\Qt5Widgetsd.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winspool.drv'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\comdlg32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\winsxs\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.18201_none_ec80f00e8593ece5\comctl32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Cockatrice\build\cockatrice\Debug\Qt5Svgd.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imm32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msctf.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\shell32.dll'
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\platforms\qwindowsd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmm.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\uxtheme.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks.dll'. Module was built without symbols.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\winsxs\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57\msvcr90.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\user32.dll'
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\shell32.dll'
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Wintab32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wtsapi32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Pen_Tablet.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\shell32.dll'
15167 cards in 179 sets loaded
loadCardDatabase(): Path =  "D:/Games/CockatriceCustom/RELATED_DB2.xml"  Status =  0
15456 cards in 182 sets loaded
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\bearer\qgenericbearerd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\IPHLPAPI.DLL'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winnsi.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dhcpcsvc.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dhcpcsvc6.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\bearer\qnativewifibearerd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wlanapi.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wlanutil.dll'. Cannot find or open the PDB file.
First-chance exception at 0x7581C42D (KernelBase.dll) in cockatrice.exe: 0x000006A6: The binding handle is invalid.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qddsd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qgifd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qicnsd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qicod.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qjp2d.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qjpegd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qmngd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qsvgd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qtgad.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qtiffd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qwbmpd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\imageformats\qwebpd.dll'. Symbols loaded.
libpng warning: iCCP: known incorrect sRGB profile
main(): starting main program
SoundEngine: enabling sound
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\audio\qtaudio_windowsd.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\clbcatq.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\devenum.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntmarta.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Wldap32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MMDevAPI.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\propsys.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wdmaud.drv'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ksuser.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\avrt.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\AudioSes.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msacm32.drv'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msacm32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\midimap.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wintrust.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msdmo.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dsound.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\powrprof.dll'. Cannot find or open the PDB file.
The thread 0x22cc has exited with code 0 (0x0).
main(): SoundEngine constructor finished
'cockatrice.exe' (Win32): Loaded 'C:\Qt\Qt5.4.2\5.4\msvc2013_opengl\plugins\iconengines\qsvgicond.dll'. Symbols loaded.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\gdi32.dll'
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptsp.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rsaenh.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\RpcRtRemote.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\user32.dll'
main(): MainWindow constructor finished
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\ole32.dll'
'cockatrice.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. Cannot find or open the PDB file.
'cockatrice.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\ole32.dll'
main(): ui.show() finished
Adding room: ID= 0 name= ""
Server::loginUser: LocalServerInterface(0x7160d98) name= "Player 1"
session id: 0
gameEvent: invalid gameId
Server_AbstractUserInterface::playerAddedToGame(): gameId = 1
loading "D:/Games/Cockatrice/zonebg/Dark Wood HP9 (2).jpg"
GameScene::addPlayer
First-chance exception at 0x001BF571 in cockatrice.exe: 0xC0000005: Access violation reading location 0x00000030.
```

### PR DESCRIPTION
**Pull request by ZeldaZach**
Fix #1192.

This addresses the issue where if you `@foo` in a local game the client would crash. This came about from calling the `getUserListsTab()` function from the `tabSupervisor` which would return an exception when calling in a local match.

### CODE REVIEW

File: cockatrice/src/tab_supervisor.h [hunk 1]
```diff
@@ -67,6 +68,7 @@ class TabSupervisor : public QTabWidget {
     void start(const ServerInfo_User &userInfo);
     void startLocal(const QList<AbstractClient *> &_clients);
     void stop();
+    bool isALocalGame() const { return isLocalGame; }
```
Comment (Daenyth) [inline cockatrice/src/tab_supervisor.h]: Conventionally this would be `getIsLocalGame()`

Comment (ZeldaZach) [inline cockatrice/src/tab_supervisor.h]: Changed

**Comment by woogerboy21** [comment]
Tested and seems to fix.  Also tested watching saved replays with mentions and still no crash.
