### PR TITLE
fix incorrect pawn icons

### LINKED ISSUE #2386: Gummy Privlevel in PM transposed
<b>Cockatrice version:</b>
dab7316 2017-01-19

___
<br>

When PMing a user with elevated PrivLevel (Donator, VIP), the Gummy colors/flair are swapped between users.

If VIP_USER and DONATOR_USER are engaged in a private message, VIP_USER will have a purple gummy and DONATOR_USER will have an orange/gold gummy.  This is reverse of what their icons appear in chat and in the user list.

If VIP_USER and DONATOR_MOD are engaged, VIP_USER will have a purple gummy, and DONATOR_MOD will have a white/black with star (VIP mod) gummy.

### PR DESCRIPTION
**Pull request by ZeldaZach**
Fix #2386 

The issue came about because we always showed the pawn of "other user's pawn rank" instead of doing a tertiary case (like we do for flags).

This fixes the issue.

### CODE REVIEW

**Comment by tooomm** [comment]
@tritoch does this fix the pawns for you?

File: cockatrice/src/tab_message.cpp [hunk 1]
```diff
@@ -115,7 +115,8 @@ void TabMessage::actLeave()
 void TabMessage::processUserMessageEvent(const Event_UserMessage &event)
 {
     const UserLevelFlags userLevel(event.sender_name() == otherUserInfo->name() ? otherUserInfo->user_level() : ownUserInfo->user_level());
-    chatView->appendMessage(QString::fromStdString(event.message()), 0,QString::fromStdString(event.sender_name()), userLevel, QString::fromStdString(otherUserInfo->privlevel()), true);
+    const QString userPriv(event.sender_name() == otherUserInfo->name() ? QString::fromStdString(otherUserInfo->privlevel()) : QString::fromStdString(ownUserInfo->privlevel()));
```
Comment (Daenyth) [inline cockatrice/src/tab_message.cpp]: Minor tweak for duplication;

```cpp
auto userInfo = event.sender_name() == otherUserInfo->name() ? otherUserInfo : ownUserInfo;
const UserLevelFlags userLevel(userInfo->user_level());
const QString userPriv = QString::fromStdString(userInfo->privlevel());
```

**Comment by tritoch** [comment]
Pawns are now correct
