### PR TITLE
Related cards

### LINKED ISSUE #77: Oracle import: Flip cards
Flip cards are incorrectly imported if the flipped counterpart comes before the regular one alphabetically. 
As such, the flipped rules text is not added to the regular card, rather, the regular card gets the rules text (and p/t) of the flip side.

I suggest storing flipped versions (the ones with brackets) in memory if the flipped version is encountered and their regular counterpart has not yet been encountered. Once the regular is encountered, it can be created and the flipped version's text can be added to it.

Imo, the import should also create a separate instance of the flipped version of the card, so that a token can be created using the secondary card name, which would have flipped art, making it more easily readable by those who prefer to read the card art instead of text boxes.

Also, because of the way flip cards are currently handled, the un-set Erase is not being imported correctly (because it thinks it's a flip card). The un-set text is added to the regular Erase's text.
(Not sure how to correct this, though)

B.F.M. also loses its bracketed text due to being treated like a flip card.

AErathi Berserker is another card which has problems being imported due to the way it's being handled. In the text spoiler, It uses the misprinted name as the name with the corrected oracle name between brackets.

If a card with brackets is encountered, and there is no card found which refers to what's between those brackets, it should add the card with the brackets as a regular card (at the end of that set's import). This would fix BFM, but not erase, nor the berserker... (which would become 'rathi Berserker (AErathi Berserker)')

Those would need to be handled as exceptions.

### LINKED ISSUE #804: Adding rear-side of DFCs to predefined 'tokens' slot
tl;dr : We should be able to add rear-side of DFCs to predefined 'tokens' slot in decklists.

I rarely used a DFC properly in Cockatrice - instead of properly transforming the card (Flip the card, create a token with name of the rear-side, etc...), I just flipped it over to back-side and stuck some attributes on it and called it transformed.

However, now that we are about to get DFCs that will turn into Planeswalkers, I think we need a easier way to create an object that displays the rear-side of a DFC.

I think allowing rear-side of the DFCs to be put into tokens slot so that they can be easily created with a few clicks (instead of having to type out the name) is the easiest solution that will not cause too much trouble for devs.

What do you guys think?

### PR DESCRIPTION
**Pull request by ctrlaltca**
Hopefully fixes the following: Fix #804 and Fix #77
Oracle is now able to parse a list of related cards for each card (double faced, flip, ..) and save them to cards.xml.
You can then have cockatrice create a token for the related cards directly in-game, without the need to add them to the deck.

related

This is mostly based on the solution proposed by @Daenyth in #77.

What's next? I thought about flipping the original card facedown and attach it to the just-created token, but i quickly abandoned the idea since it's too game-specific and it would require a new command to be implemented (backwards compatibility, etc).

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Other problems/ideas with this implementation:
 * we are physically creating a new card on the table, this is not exactly correct for mtg's transform;
 * about mtg's new double faced planeswalker, currently tokens have no loyalty property;
 * about flip cards, we could add a "ThisIsTheFlippedHalf" property to cards and paint their picture rotated 180 degrees

**Comment by Daenyth** [comment]
I'm fine with creating new cards. If we create the flipped version, does it have the upside down art inherently? I think this is a great step for now.

It would be pretty awesome later down the line to have oracle automatically infer token creation, like having the "Create related" on Kher Keep for example creating a Kobold token.

**Comment by Daenyth** [comment]
Code looks fine, this feature looks awesome!

**Comment by ZeldaZach** [comment]
After my initial test, it works perfectly as expected. This feature has been in the works for a long time and I'm glad somebody finally got around to it!

I'm fine with a new card being created when you hit the button (essentially this is a shortcut for a token to be created), however I think it should take the same coordinate of the old card. (i.e. when I use the ability, it places the card over the old one as shown below:
 card

With the flip cards, like Akki Lavarunner, I think having the card re-painted to rotate it 180* would be the best course of action.

Responding to @Daenyth's comment, this is a great step towards having cards auto-link the tokens they create to allow for a more intuitive token creation menu from within the physical card instead of a separate menu.

Great job @ctrlaltca Keep up the great work :smile: :+1:

File: cockatrice/src/player.cpp [hunk 1]
```diff
@@ -1076,6 +1076,25 @@ void Player::actCreatePredefinedToken()
...
+
+    // create the token for the related card
+    Command_CreateToken cmd;
+    cmd.set_zone("table");
+    cmd.set_card_name(cardInfo->getName().toStdString());
+    cmd.set_color(cardInfo->getColors().isEmpty() ? QString().toStdString() : cardInfo->getColors().first().toLower().toStdString());
+    cmd.set_pt(cardInfo->getPowTough().toStdString());
+    cmd.set_destroy_on_zone_change(true);
+    cmd.set_x(-1);
+    cmd.set_y(0);
```
Comment (ZeldaZach) [inline cockatrice/src/player.cpp]: Instead of setting x and y by default, why not acquire where the card the transformation was called from (i.e. Get Delver of Secret's location) and place this new card right on top of it (giving it the same X/Y of Delver)

**Comment by ctrlaltca** [comment]
The last commit adds a small change to Command_CreateToken, adding two new optional parameters (a target card id and zone), so the change is backwards-compatible.
If these parameters points to an existing card, the existing card will be attached to the newly created token.
So now, when a new token gets created from the "related card" menu, the old card gets automatically attached behind the new one.

**Comment by ctrlaltca** [comment]
This last commit adds image rotation for the bottom half of flip cards.

**Comment by ZeldaZach** [comment]
After further testing, it seems that before the new card is attached, all other cards are unattached. Also, it moves it up to the top corner instead of where it was originally.

Before:
screenshot 2015-06-13 18 37 07

After:
screenshot 2015-06-13 18 37 15

**Comment by ctrlaltca** [comment]
> After further testing, it seems that before the new card is attached, all other cards are unattached.

Yes, this is true for every card that gets attached to another card, not only for tokens.

**Comment by ZeldaZach** [comment]
Is there a way to address that then? In another PR?

**Comment by ctrlaltca** [comment]
I could not find a way that didn't need the definition of a new command, a change that would not be compatible with older clients.

**Comment by ZeldaZach** [comment]
I think maybe it's time we force a user base update so everybody has to update their clients to a newer build. Some people still have the original Summer Magic build... When we publish the new build, can it include a server update for MIN_BUILD_DATE so we can force updates if necessary?

**Comment by Daenyth** [comment]
I'm reluctant to update the api version...

**Comment by ZeldaZach** [comment]
If you're not willing to update, then I guess at this point we can just merge this in and move on. I really think we should look into having a min version requirement for client builds in order to improve reliability on new things

**Comment by ctrlaltca** [comment]
I agree we shouldn't break old clients updating the minimum required api version unless it's absolutely needed. @ZeldaZach we already have a protocol version number (https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/src/serversocketinterface.cpp#L67) to ensure only working clients can connect to a server.

We can't accurately plan the transition of all server and clients from the old version to the new one, because:
 * we actually don't control the servers and can't decide when they'll be updated;
 * we don't have a proper release schedule;
 * we don't have a technology in place to handle different api versions at the same time, and slowly deprecate the older ones.

Back to this ticket, i'll have a look at fixing at least the card position.

**Comment by ZeldaZach** [comment]
I think we should look at just pushing the API version up, even though it's against what Dae thinks, because of how many things we've updated over time and how we're about to release the newest build of Cockatrice...

**Comment by Daenyth** [comment]
The purpose of the api field is to prevent *incompatible* clients from
connecting.

I think people will upgrade naturally enough, at least the
unregistered users, once we make registration mandatory

**Comment by Psithief** [comment]
This looks like it lays some groundwork for #590.
