### PR TITLE
Fix infinite loop on local game close

### LINKED ISSUE #2091: CrashLog from Single Player Game
Crashlog location: https://gist.github.com/ZeldaZach/04ff77d4e0f68ce221fe159e950b21ce

### PR DESCRIPTION
**Pull request by ctrlaltca**
Since #1991 servatrice only works in multithread mode, so in`Server::prepareDestroy()` the code  dealing with client destruction was using proper locking.
Since the "local game" server in cockatrice is not multithreaded, while closing a game it will hang indefinitely waiting for the lock to be removed.
This PR removes locking when destroying a local game server, the same way it was implemented before #1991.

fix #2091

### CODE REVIEW

File: common/server.cpp [hunk 1]
```diff
@@ -57,29 +57,35 @@ Server::~Server()
 {
 }
 
-void Server::prepareDestroy()
+void Server::prepareDestroy(bool lockClients)
 {
     // dirty :(
```
Comment (Nightfirecat) [inline common/server.cpp]: Is this still a dirty way to do this?

File: cockatrice/src/localserver.cpp [hunk 2]
```diff
@@ -11,7 +11,7 @@ LocalServer::LocalServer(QObject *parent)
 
 LocalServer::~LocalServer()
 {
-    prepareDestroy();
+    prepareDestroy(false);
```
Comment (Daenyth) [inline cockatrice/src/localserver.cpp]: What about making `prepareDestroy` virtual and overriding the behavior differently in real server and local server mode?

File: common/server.cpp (hunk 1 above)
Comment (ctrlaltca) [inline common/server.cpp]: as dirty as before, so i didn't remove the comment yet.

**Comment by ctrlaltca** [comment]
Reimplemented splitting methods to different classes as suggested by @Daenyth. A virtual method was not even needed.

File: cockatrice/src/localserver.cpp [hunk 3]
```diff
@@ -11,6 +11,10 @@ LocalServer::LocalServer(QObject *parent)
 
 LocalServer::~LocalServer()
 {
+    // no need to lock clients, they live in the same thread
```
Comment (Daenyth) [inline cockatrice/src/localserver.cpp]: Does the `LocalServer` class even have any locks? If not the comment is misleading. If it owns some but they are unused from lack of necessity that's even more confusing.

Comment (ctrlaltca) [inline cockatrice/src/localserver.cpp]: `LocalServer` is just a mockup built around the abstract `Server` class, so it implements almost nothing. All the client handling is in `Server` too, except this part.
I thought that in the future someone reading this code would ask himself why clients are directly being destroyed here without proper locking, instead of in the async+lock way they are destroyed in servatrice; so i left this comment.

Comment (Daenyth) [inline cockatrice/src/localserver.cpp]: Maybe `// LocalServer is single threaded so it doesn't need locks on this` ?

**Comment by ctrlaltca** [comment]
Comment updated

**Comment by ZeldaZach** [comment]
Seems fixed to me. Good job! :shipit:
