### PR TITLE
Fix macro for MSVC; fix #1063

### LINKED ISSUE #1063: Windows Installer Builds no longer build correctly
Not sure whats changed and wont be home to even begin to troubleshoot for another week but one of the more recent changes is now causing the windows installer file to not be created properly.  The mac seems to build a dmg file ok but windows fails to create the installer files.

Last successful build with installer was Cockatrice_win32_git-53f63e2.exe

### PR DESCRIPTION
**Pull request by ctrlaltca**

### CODE REVIEW

**Comment by poixen** [comment]
:+1:

File: servatrice/src/serversocketinterface.cpp [hunk 1]
```diff
@@ -164,14 +164,24 @@ void ServerSocketInterface::readClient()
             newCommandContainer.ParseFromArray(inputBuffer.data(), messageLength);
         }
         catch(std::exception &e) {
-            qDebug() << "Caught std::exception in" << __FILE__ << __LINE__ << __PRETTY_FUNCTION__;
+            qDebug() << "Caught std::exception in" << __FILE__ << __LINE__ << 
+#ifdef _MSC_VER // Visual Studio
+                __FUNCTION__;
+#else
+                __PRETTY_FUNCTION__;
+#endif
```
Comment (Daenyth) [inline servatrice/src/serversocketinterface.cpp]: Do you think this might get used anywhere else? I wonder if it's not better to `#DEFINE` just one of these and use it throughout.

Comment (ctrlaltca) [inline servatrice/src/serversocketinterface.cpp]: IIRC there are other places where protobuf's methods gets called (the replay/deck transfer code); all these calls could throw exceptions, and we should be able to catch them.
So yes, it might gets used somewhere else, but within the whole snippet of code implementing exception handling. Maybe we could reimplement this as a external helper.. i'll think a bit on it.
