### PR TITLE
Fix move to top of library shuffling an extra card

### LINKED ISSUE #5611: Bug on "put selected cards on top of librabry at random"
**System Information:**
Client Version: 2.10.0 (2025-02-10)
Client Operating System: Windows 7 Version 6.1 (Build 7601: SP 1)
Build Architecture: 64-bit
Qt Version: 5.15.2
System Locale: fr_FR
Install Mode: Standard

_______________________________________________________________________________________

put selected cards on top of librabry at random run with face-up cards, but if one or more of those cards are face-down the shuffle on top take 1 cards more.

Other detail : ctrl+B is used for 2 functions, put on top of the library at random, put on bottom of the library at random.

_______________________________________________________________________________________

**Steps to reproduce:**
- Put triumph of saint katherine in play face up.
- put two other cards face down in play from library.
- select the 3 cards.
- right clic -> move to -> top of library at random.
- when you reveal again the cards face up, a 4th card is shuffled with the 3 others.

### PR DESCRIPTION
**Pull request by RickyRister**
## Related Ticket(s)
- Fixes #5611

## Short roundup of the initial problem

"Move to top of library in random order" shuffles one card more than the number that was topped. 

## What will change with this Pull Request?

Seems like shuffle command's start and end index are both inclusive. We forgot a -1 on the end index.

### CODE REVIEW

File: cockatrice/src/game/player/player.cpp [hunk 1]
```diff
@@ -3186,7 +3186,7 @@ void Player::cardMenuAction()
                     auto *scmd = new Command_Shuffle;
                     scmd->set_zone_name("deck");
                     scmd->set_start(0);
-                    scmd->set_end(idList.card_size());
+                    scmd->set_end(idList.card_size() - 1);
```
Comment (ebbit1q) [inline cockatrice/src/game/player/player.cpp:3189]:
```suggestion
                    scmd->set_end(idList.card_size() - 1); // inclusive, the indexed card at end will be shuffled
```

**Review by ebbit1q — APPROVED** [review]
thank you
