### PR TITLE
Fix release tests

### LINKED ISSUE #4000: database tests fail on non debug builds
Building without the flag `-DCMAKE_BUILD_TYPE=Debug` but with `-DTEST=1` results in the tests crashing when run.

Minimal reproduction:
* Compile:
```
git pull https://github.com/Cockatrice/Cockatrice
cd Cockatrice
mkdir build
cd build
cmake .. -DTEST=1
make
```
* Run test:
```
./tests/carddatabase/carddatabase_test
```
* Output:
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from CardDatabaseTest
[ RUN      ] CardDatabaseTest.LoadXml
CardDatabase::loadCardDatabases start
Segmentation fault (core dumped)
```
* Traceback:
```
#0  0x000056133b549bb7 in CardDatabase::loadCardDatabases() ()
#1  0x000056133b541b58 in ?? ()
#2  0x00007f936853088b in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
   from /usr/lib/libgtest.so.1.8.1
#3  0x00007f9368526b2c in testing::Test::Run() () from /usr/lib/libgtest.so.1.8.1
#4  0x00007f9368526c89 in testing::TestInfo::Run() () from /usr/lib/libgtest.so.1.8.1
#5  0x00007f9368526d67 in testing::TestCase::Run() () from /usr/lib/libgtest.so.1.8.1
#6  0x00007f936852729d in testing::internal::UnitTestImpl::RunAllTests() () from /usr/lib/libgtest.so.1.8.1
#7  0x00007f9368530dfb in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) () from /usr/lib/libgtest.so.1.8.1
#8  0x00007f93685273cf in testing::UnitTest::Run() () from /usr/lib/libgtest.so.1.8.1
#9  0x000056133b53f7df in main ()
```

This issue directly causes https://github.com/Cockatrice/Cockatrice/issues/3639

### PR DESCRIPTION
**Pull request by olegshtch**
## Related Ticket(s)
- Fixes #4000

## Short roundup of the initial problem

Follows up #4058 

## What will change with this Pull Request?
- Uses real `SettingsCache` and `CardDatabaseSettings` headers with mocked implementation.

### CODE REVIEW

**Comment by ebbit1q** [comment]
Seems good, should be tested well of course, I do notice some overlap between the mocks used by dbconverter and the tests.

**Comment by ebbit1q** [comment]
Also you should test locally with the debug build as well, it uses rather strict -Wall unlike the release build.

File: dbconverter/src/mocks.cpp [hunk 1]
```diff
@@ -17,37 +21,250 @@ bool CardDatabaseSettings::isKnown(QString /* shortName */)
...
+{
+    return defaultPath;
+}
 SettingsCache::SettingsCache()
 {
-    cardDatabaseSettings = new CardDatabaseSettings();
-};
-SettingsCache::~SettingsCache()
+    settings = new QSettings("global.ini", QSettings::IniFormat, this);
+    shortcutsSettings = nullptr;
```
Comment (ebbit1q) [inline dbconverter/src/mocks.cpp:46]: might look a bit better with an initializer list

**Comment by ebbit1q** [comment]
I meant the member initializer list: https://en.cppreference.com/w/cpp/language/constructor

**Comment by ebbit1q** [comment]
The brackets don't really matter {}, () the previous commit was fine too. Sorry if I was confusing.
