### PR TITLE
detect recursive redirects

### LINKED ISSUE #6520: Random crashes
**System Information:**
Client Version: 2.10.2 (2025-04-04)
Client Operating System: Windows 10 Version 22H2
Build Architecture: 64-bit
Qt Version: 6.6.3
System Locale: ru_RU
Install Mode: Standard

<details><summary>Debug Log:</summary>

[0m[2026-01-14 21:01:40.845 [32mI[0m] [unknown] - Theme changed: "Default" [unknown:0]
[0m[2026-01-14 21:01:40.847 [32mI[0m] [unknown] - SoundEngine: disabling sound [unknown:0]
[0m[2026-01-14 21:01:40.847 [32mI[0m] [unknown] - Sound theme changed: "Default" [unknown:0]
[0m[2026-01-14 21:01:40.854 [32mI[0m] [unknown] - SoundEngine: disabling sound [unknown:0]
[0m[2026-01-14 21:01:40.855 [33mW[0m] [unknown] - Unable to load qt translation "qt_" at "C:/Program Files/Cockatrice/Resources/translations" [unknown:0]
[0m[2026-01-14 21:01:40.855 [33mW[0m] [unknown] - Unable to load "cockatrice" translation "cockatrice_" at "C:/Program Files/Cockatrice/translations" [unknown:0]
[0m[2026-01-14 21:01:40.856 [32mI[0m] [unknown] - Starting main program [unknown:0]
[0m[2026-01-14 21:01:41.422 [32mI[0m] [unknown] - MainWindow constructor finished [unknown:0]
[0m[2026-01-14 21:01:41.432 [32mI[0m] [unknown] - Spoilers Disabled [unknown:0]
[0m[2026-01-14 21:01:41.520 [32mI[0m] [unknown] - ui.show() finished [unknown:0]
[0m[2026-01-14 21:01:41.548 [32mI[0m] [unknown] - Searching for updates on the channel:  "https://api.github.com/repos/Cockatrice/Cockatrice/releases/latest" [unknown:0]
[0m[2026-01-14 21:01:41.562 [32mI[0m] [unknown] - Startup: found config with current version [unknown:0]
[0m[2026-01-14 21:01:41.569 [32mI[0m] [unknown] - Card Database Loading Started [unknown:0]
[0m[2026-01-14 21:01:41.569 [32mI[0m] [unknown] - Trying to parse:  "C:/Users/79624/AppData/Local/Cockatrice/Cockatrice/cards.xml" [unknown:0]
[0m[2026-01-14 21:01:41.570 [32mI[0m] [unknown] - Unknown item "info" , trying to continue anyway [unknown:0]
[0m[2026-01-14 21:01:42.137 [32mI[0m] [unknown] - Current hash= "0e7d7ff" update hash= "" [unknown:0]
[0m[2026-01-14 21:01:42.138 [32mI[0m] [unknown] - Got reply from release server, name= "Cockatrice 2.10.2: Omenpath Revision 2" desc= "https://github.com/Cockatrice/Cockatrice/releases/tag/2025-04-03-Release-2.10.2" date= QDate("2025-04-04") url= "https://github.com/Cockatrice/Cockatrice/releases/download/2025-04-03-Release-2.10.2/Cockatrice-Omenpath-2.10.2-Win10.exe" [unknown:0]
[0m[2026-01-14 21:01:42.138 [32mI[0m] [unknown] - Searching for commit hash corresponding to stable channel tag:  "2025-04-03-Release-2.10.2" [unknown:0]
[0m[2026-01-14 21:01:42.448 [32mI[0m] [unknown] - Got reply from tag server, commit= "0e7d7ffcb242163adb58e7cda6ecb4e1750689b1" [unknown:0]
[0m[2026-01-14 21:01:42.448 [32mI[0m] [unknown] - Current hash= "0e7d7ff" update hash= "0e7d7ff" [unknown:0]
[0m[2026-01-14 21:01:47.393 [32mI[0m] [unknown] - Path = "C:/Users/79624/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 33830 Sets = 849 "5824ms" [unknown:0]
[0m[2026-01-14 21:01:47.394 [32mI[0m] [unknown] - Trying to parse:  "C:/Users/79624/AppData/Local/Cockatrice/Cockatrice/tokens.xml" [unknown:0]
[0m[2026-01-14 21:01:47.394 [32mI[0m] [unknown] - Unknown item "info" , trying to continue anyway [unknown:0]
[0m[2026-01-14 21:01:47.485 [32mI[0m] [unknown] - Path = "C:/Users/79624/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 34766 Sets = 849 "92ms" [unknown:0]
[0m[2026-01-14 21:01:47.485 [32mI[0m] [unknown] - Path = "C:/Users/79624/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 34766 Sets = 849 "0ms" [unknown:0]
[0m[2026-01-14 21:01:47.486 [32mI[0m] [unknown] - Loading Custom Set 0 ( "C:/Users/79624/AppData/Local/Cockatrice/Cockatrice/customsets/Wixoss TCG.xml" ) [unknown:0]
[0m[2026-01-14 21:01:47.487 [32mI[0m] [unknown] - Trying to parse:  "C:/Users/79624/AppData/Local/Cockatrice/Cockatrice/customsets/Wixoss TCG.xml" [unknown:0]
[0m[2026-01-14 21:01:47.555 [33mW[0m] [unknown] - DirectWrite: CreateFontFaceFromHDC() failed (Означает ошибку во входном файле, например в файле шрифта.) for QFontDef(Family="Fixedsys", pointsize=9.75, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-16) dpi=96 [unknown:0]
[0m[2026-01-14 21:01:47.660 [33mW[0m] [unknown] - DirectWrite: CreateFontFaceFromHDC() failed (Означает ошибку во входном файле, например в файле шрифта.) for QFontDef(Family="Modern", pointsize=9.75, pixelsize=46, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Modern", lfWidth=0, lfHeight=-46) dpi=96 [unknown:0]
[0m[2026-01-14 21:01:48.197 [32mI[0m] [unknown] - Path = "C:/Users/79624/AppData/Local/Cockatrice/Cockatrice/customsets/Wixoss TCG.xml" Status = 0 Cards = 43726 Sets = 1071 "710ms" [unknown:0]
[0m[2026-01-14 21:01:48.320 [32mI[0m] [unknown] - Card Database Loading Success [unknown:0]
</details>

_______________________________________________________________________________________

I use an external plugin to get a custom card database (not for MTG) by adding an .xml file to the "customsets" folder. When using the search or selecting a card from that custom set in the list of the deck editor window, the program may suddenly close without displaying any error message. I could not identify any dependence of these crushes on the request or selected card. I am using the same version of the custom set file as before reinstalling the application and have not experienced such problems before. Please tell me what this might be related to.

Link to the custom set files: https://github.com/TetrusAO/Wixoss-TCG-Cockatrice-Plugin/tree/master

UPD: 
Experimentally, it was possible to establish the following:
1) If the laptop is inactive for a long time (about 5-10 minutes, but without going into sleep mode), the program still crashes at the first attempt of interaction.
2) When trying to assemble a deck, if the program crashes, the cards ? which were put into the deck randomly lose their type and get the "Unknown" type (sometimes all cards, sometimes some, sometimes none).

_______________________________________________________________________________________

### PR DESCRIPTION
**Pull request by ebbit1q**
## Related Ticket(s)
- Fixes #6520

## Short roundup of the initial problem
recursive redirects crash the client

## What will change with this Pull Request?
- if a redirect directs to itself we drop the request
- we do not detect recursions that involve multiple domains however

### CODE REVIEW

File: cockatrice/src/interface/card_picture_loader/card_picture_loader_worker_work.cpp [hunk 1]
```diff
@@ -70,16 +70,22 @@ void CardPictureLoaderWorkerWork::picDownloadFailed()
...
+    bool redirectFailure = false;
     if (redirectTarget.isValid()) {
         QUrl url = reply->request().url();
         QUrl redirectUrl = redirectTarget.toUrl();
         if (redirectUrl.isRelative()) {
             redirectUrl = url.resolved(redirectUrl);
         }
-        emit urlRedirected(url, redirectUrl);
+        if (url == redirectUrl) {
+            qCWarning(CardPictureLoaderWorkerWorkLog) << "recusive redirect detected!";
```
Comment (ebbit1q) [inline cockatrice/src/interface/card_picture_loader/card_picture_loader_worker_work.cpp:81]: typo, sigh
