### PR TITLE
[PrintingSelector] Sync modified and history state on bulk selection

### LINKED ISSUE #6232: PrintingSelector bulk selection forgets card amounts
Using the PrintingSelector bulk selection feature will sometimes overwrite cards with instances where their number is set to 1 instead of whatever it was before.

### LINKED ISSUE #6375: bulk edit "remove all printing info" does not set modified flag
**System Information:**

linux, current master version adee671

<details><summary>Debug Log:</summary>

</details>

_______________________________________________________________________________________

when using the option bulk edit "remove all printing info" it does not set the modified flag in either deck editor

_______________________________________________________________________________________

**Steps to reproduce:**
 - open a deck in either deck editor
 - right click a card to open the printing selector
 - click bulk edit
 - click remove all printing info
 - the deck modified flag is not set and saving is not available, expected: the deck modified flag is set and the * appears in the tab title and saving is available

### PR DESCRIPTION
**Pull request by BruebachL**
## Related Ticket(s)
- Fixes #6232
- Fixes #6375

## What will change with this Pull Request?
- this
- and this

### CODE REVIEW

File: cockatrice/src/interface/widgets/dialogs/dlg_select_set_for_cards.cpp [hunk 1]
```diff
@@ -145,31 +145,47 @@ void DlgSelectSetForCards::retranslateUi()
 void DlgSelectSetForCards::actOK()
 {
     QMap<QString, QStringList> modifiedSetsAndCardsMap = getModifiedCards();
+
+    if (!modifiedSetsAndCardsMap.isEmpty()) {
```
Comment (ebbit1q) [inline cockatrice/src/interface/widgets/dialogs/dlg_select_set_for_cards.cpp]: why not just immediately return on empty? nothing in this function does anything when it is

**Review by RickyRister — APPROVED** [review]
Works on my end. Seems fine.
