### PR TITLE
better null check

### LINKED ISSUE #3035: Crash
Mac Crash when closing game. Will investigate

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtWidgets      	0x000000010633b749 QWidget::insertAction(QAction*, QAction*) + 297
1   com.cockatrice.Cockatrice     	0x0000000105557654 Player::updateCardMenu(CardItem const*) + 356
2   org.qt-project.QtCore         	0x000000010760aca9 QMetaObject::activate(QObject*, int, int, void**) + 3113
3   com.cockatrice.Cockatrice     	0x00000001056b55c0 AbstractCardItem::updateCardMenu(AbstractCardItem*) + 64
4   com.cockatrice.Cockatrice     	0x0000000105561691 CardItem::prepareDelete() + 273
5   com.cockatrice.Cockatrice     	0x000000010556197e CardItem::deleteLater() + 14
6   com.cockatrice.Cockatrice     	0x000000010555d08b CardZone::clearContents() + 187
7   com.cockatrice.Cockatrice     	0x000000010553e9ad Player::clear() + 173
8   com.cockatrice.Cockatrice     	0x000000010553de28 Player::~Player() + 408
9   com.cockatrice.Cockatrice     	0x000000010553eb0e Player::~Player() + 14
10  com.cockatrice.Cockatrice     	0x00000001055dce7a TabGame::~TabGame() + 234
11  com.cockatrice.Cockatrice     	0x00000001055dd8ee TabGame::~TabGame() + 14
12  org.qt-project.QtCore         	0x0000000107602a20 QObject::event(QEvent*) + 128
13  org.qt-project.QtWidgets      	0x0000000106348bf3 QWidget::event(QEvent*) + 5731
14  org.qt-project.QtWidgets      	0x0000000106458535 QMainWindow::event(QEvent*) + 1733
15  org.qt-project.QtWidgets      	0x000000010630760d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 301
16  org.qt-project.QtWidgets      	0x00000001063089b1 QApplication::notify(QObject*, QEvent*) + 369
17  org.qt-project.QtCore         	0x00000001075d8f84 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
18  org.qt-project.QtCore         	0x00000001075d9fab QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 891
19  libqcocoa.dylib               	0x0000000106fbe30e 0x106f99000 + 152334
20  libqcocoa.dylib               	0x0000000106fbebd1 0x106f99000 + 154577
21  com.apple.CoreFoundation      	0x00007fff4482e5a1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
22  com.apple.CoreFoundation      	0x00007fff448e835c __CFRunLoopDoSource0 + 108
23  com.apple.CoreFoundation      	0x00007fff44811040 __CFRunLoopDoSources0 + 208
24  com.apple.CoreFoundation      	0x00007fff448104bd __CFRunLoopRun + 1293
25  com.apple.CoreFoundation      	0x00007fff4480fd23 CFRunLoopRunSpecific + 483
26  com.apple.HIToolbox           	0x00007fff43b27e26 RunCurrentEventLoopInMode + 286
27  com.apple.HIToolbox           	0x00007fff43b27a9f ReceiveNextEventCommon + 366
28  com.apple.HIToolbox           	0x00007fff43b27914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
29  com.apple.AppKit              	0x00007fff41df2f5f _DPSNextEvent + 2085
30  com.apple.AppKit              	0x00007fff42588b4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
31  com.apple.AppKit              	0x00007fff41de7d6d -[NSApplication run] + 764
32  libqcocoa.dylib               	0x0000000106fbd933 0x106f99000 + 149811
33  org.qt-project.QtCore         	0x00000001075d5291 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 417
34  org.qt-project.QtCore         	0x00000001075d95f7 QCoreApplication::exec() + 343
35  com.cockatrice.Cockatrice     	0x0000000105516534 main + 1652
36  libdyld.dylib                 	0x00007fff6c113115 start + 1
```

### PR DESCRIPTION
**Pull request by ZeldaZach**
Fix #3035 

Seems we call `c->deleteLater()` without checking if `c` is a valid pointer. I believe this was the cause of the crash and have caught it in `player.cpp`.

### CODE REVIEW

**Comment by ancestral** [comment]
Seems fine, as I look things over.

File: cockatrice/src/player.cpp [hunk 1]
```diff
@@ -1896,9 +1898,13 @@ void Player::addCard(CardItem *c)
 void Player::deleteCard(CardItem *c)
 {
     if (dialogSemaphore)
```
Comment (ctrlaltca) [inline cockatrice/src/player.cpp]: If you want to check for `c` to be not null, better do it before the `if`, since both branches needs `c` ito be a valid pointer.

File: cockatrice/src/player.cpp [hunk 2]
```diff
@@ -2552,7 +2558,7 @@ void Player::updateCardMenu(const CardItem *card)
     bool writeableCard = getLocal();
     if (card->getZone() && card->getZone()->getIsView())
     {
-        ZoneViewZone *view = static_cast<ZoneViewZone *>(card->getZone());
+        auto *view = dynamic_cast<ZoneViewZone *>(card->getZone());
```
Comment (ctrlaltca) [inline cockatrice/src/player.cpp]: Is there a reason for this change?

File: cockatrice/src/tab_game.cpp [hunk 3]
```diff
@@ -434,12 +434,14 @@ void TabGame::emitUserEvent() {
 
 TabGame::~TabGame()
 {
-    if(replay)
-        delete replay;
+    delete replay;
```
Comment (ctrlaltca) [inline cockatrice/src/tab_game.cpp]: Why has this check been removed?

File: cockatrice/src/cardzone.cpp [hunk 4]
```diff
@@ -31,12 +31,13 @@ void CardZone::retranslateUi()
...
 {
-    for (int i = 0; i < cards.size(); i++) {
+    for (int i = 0; i < cards.size(); i++)
+    {
         // If an incorrectly implemented server doesn't return attached cards to whom they belong before dropping a player,
         // we have to return them to avoid a crash.
         const QList<CardItem *> &attachedCards = cards[i]->getAttachedCards();
-        for (int j = 0; j < attachedCards.size(); ++j)
-            attachedCards[j]->setParentItem(attachedCards[j]->getZone());
+        for (auto attachedCard : attachedCards)
```
Comment (Daenyth) [inline cockatrice/src/cardzone.cpp]: Modern cpp is so much nicer :)

File: cockatrice/src/player.cpp (hunk 2 above)
Comment (ZeldaZach) [reply cockatrice/src/player.cpp]: I was requested to by CLion as this isn't a static change apparently

File: cockatrice/src/tab_game.cpp (hunk 3 above)
Comment (ZeldaZach) [reply cockatrice/src/tab_game.cpp]: Clion informed me that "delete Object" and "delete nullptr" are both fine, so the check is superfluous

File: cockatrice/src/cardzone.cpp (hunk 4 above)
Comment (ZeldaZach) [reply cockatrice/src/cardzone.cpp]: Yup!

File: cockatrice/src/player.cpp (hunk 1 above)
Comment (ZeldaZach) [reply cockatrice/src/player.cpp]: addressed

File: cockatrice/src/tab_game.cpp (hunk 3 above)
Comment (ctrlaltca) [reply cockatrice/src/tab_game.cpp]: Yep, c++11, you are right.

File: cockatrice/src/player.cpp (hunk 2 above)
Comment (ctrlaltca) [reply cockatrice/src/player.cpp]: `CardItem::getZone()` returns a `CardZone*`, and `ZoneViewZone` inherits from`SelectZone` that inherits from `CardZone`. To be clear:
```cpp
class CardItem {
  CardZone *getZone() const { return zone; }
 ...
};
class SelectZone : public CardZone { ... };
class ZoneViewZone : public SelectZone { ... };

```

This is a "cast down" and should work fine with `static_cast` as long as nothing `virtual` is involved.
Using `static_cast`, if we ever make a change that breaks this behaviour, the compiler will shout out an error.
With `dynamic_cast` instead, we won't notice anything until crash logs starts to appear because `dynamic_cast` is failing and returning `nullptr` instead of a valid value, and we have no check in place.

Comment (ZeldaZach) [reply cockatrice/src/player.cpp]: I'll keep this in mind for future changes
