### PR TITLE
Change filter hint text to "Games shown: X / Y" and fix user-game segfault

### LINKED ISSUE #3068: Add text hint that filter are applied to the game list
Taken from https://github.com/Cockatrice/Cockatrice/issues/3067#issuecomment-362619646
The idea is to clarify to the user that the game list doesn't show all available games right now.

>There could be a simple little hint text **only showing** when filters are active:
filter hint
>
>I totally see people adding filters to find a suitable game, then close trice and come back a week later to wonder why there are just a few games shown. (Cockatrice remembers used filters, which is a nice feature!)

### LINKED ISSUE #3979: Cockatrice segfaults when viewing another user's games
Client Version: 2.7.5-beta.2 (2020-04-23)
Client Operating System: Pop!_OS 19.10
Build Architecture: 64-bit
Qt Version: 5.11.3
System Locale: en_GB
Install Mode: Standard
_______________________________________________________________________________________

Cockatrice segfaults when you click show this user's games:

1. connect to a server
2. go to account tab
3. right click an online buddy
4. click show this user's games
5. segfault

Stack trace:
```
#0  0x00005555557d2e80 in GamesProxyModel::getNumberOfAlteredFilters() const ()
#1  0x0000555555808682 in GameSelector::retranslateUi() ()
#2  0x0000555555809af0 in GameSelector::GameSelector(AbstractClient*, TabSupervisor const*, TabRoom*, QMap<int, QString> const&, QMap<int, QMap<int, QString> > const&, bool, bool, QWidget*) ()
#3  0x000055555589e723 in UserContextMenu::gamesOfUserReceived(Response const&, CommandContainer const&) ()
#4  0x00007ffff69b1e4a in QObject::event(QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff787da86 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff7886e00 in QApplication::notify(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff6985a2a in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff69886a8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff69de037 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff595e8bd in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff595eb40 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff595ebe3 in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff69dd635 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff69845cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff698c336 in QCoreApplication::exec() ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x000055555577583d in main ()
```

### PR DESCRIPTION
**Pull request by knitknit**
## Related Ticket(s)
- Fixes #3068 (reverts https://github.com/Cockatrice/Cockatrice/pull/3946)
- Fixes #3979 (crash caused in #3946)
- Makes #3957 less obvious to users (though I think there's still something wrong there)

## Short roundup of the initial problem
Cockatrice remembers filters applied between sessions, but users were not alerted if any filters were altered from their default values.

## What will change with this Pull Request?
- Revert https://github.com/Cockatrice/Cockatrice/pull/3946
- Instead, change the hint text to read "Games shown: 13 / 42"
- Update hint text on interesting events, like games being added or newly meeting/not meeting filter criteria
- Fix segfault that occurred when viewing user's games

## Screenshots
Screenshot of "Games shown" text:
Screen Shot 2020-04-30 at 8 16 55 PM

Screenshot of viewing user's games, client did not crash before/during/after:
Screen Shot 2020-04-30 at 8 17 12 PM

### CODE REVIEW

**Comment by knitknit** [comment]
@tooomm @ZeldaZach this appears to work the way I would expect, though I'm wondering if there's a more efficient way to do it?

Once we agree on general approach, I'll wire in the changes to also update the hint text as the game list is updated, if we want to. Thanks!

File: cockatrice/src/gameselector.cpp [hunk 1]
```diff
@@ -290,13 +292,15 @@ void GameSelector::actSelectedGameChanged(const QModelIndex &current, const QMod
...
-        } else {
-            alteredFiltersLabel->setText(tr("%1 filter(s) applied").arg(numAlteredFilters));
-        }
+    if (filteredGamesLabel != nullptr && gameListProxyModel != nullptr &&
+        gameListModel != nullptr) {
+        const int totalGames = gameListModel->rowCount();
+        const int shownGames = totalGames - gameListProxyModel->getNumFilteredGames();
+        filteredGamesLabel->setText(tr("Games shown: %1 / %2").arg(shownGames).arg(totalGames));
+    } else {
+        filteredGamesLabel->setText(tr("Games shown: NaN / NaN"));
```
Comment (ZeldaZach) [inline cockatrice/src/gameselector.cpp:303]: Wouldn't show a weird error to a user like this. Would silently fail

File: cockatrice/src/gameselector.cpp [hunk 2]
```diff
@@ -290,13 +292,15 @@ void GameSelector::actSelectedGameChanged(const QModelIndex &current, const QMod
...
-void GameSelector::setAlteredFiltersText(const int numAlteredFilters)
+void GameSelector::setFilteredGamesLabel()
 {
-    if (alteredFiltersLabel != nullptr) {
-        if (numAlteredFilters == 0) {
-            alteredFiltersLabel->setText(tr("Default filters applied"));
-        } else {
-            alteredFiltersLabel->setText(tr("%1 filter(s) applied").arg(numAlteredFilters));
-        }
+    if (filteredGamesLabel != nullptr && gameListProxyModel != nullptr &&
```
Comment (ZeldaZach) [inline cockatrice/src/gameselector.cpp:297]:
```suggestion
    if (filteredGamesLabel && gameListProxyModel && gameListModel)
```

How often would one of these conditions fail?

File: cockatrice/src/gameselector.cpp (hunk 1 above)
Comment (knitknit) [reply cockatrice/src/gameselector.cpp:303]: Oh sure, that was more for my own debugging :) is there somewhere we'd want to log an error, or is this trivial enough to not be useful?

Comment (ZeldaZach) [reply cockatrice/src/gameselector.cpp:303]: I find it trivial, but you can dump to qDebug() so we can trace it later if needed

File: cockatrice/src/gamesmodel.cpp [hunk 3]
```diff
@@ -314,11 +314,26 @@ void GamesProxyModel::setMaxPlayersFilter(int _maxPlayersFilterMin, int _maxPlay
     invalidateFilter();
 }
 
+int GamesProxyModel::getNumFilteredGames() const
+{
+    GamesModel *model = qobject_cast<GamesModel *>(sourceModel());
```
Comment (ebbit1q) [inline cockatrice/src/gamesmodel.cpp:319]: This segfaults when I click "show this user's games" like #3979 but inside the sourceModel() call.

Comment (knitknit) [reply cockatrice/src/gamesmodel.cpp:319]: Oh yikes, thanks for the heads up! Seems reasonable for someone to cleanly revert https://github.com/Cockatrice/Cockatrice/pull/3946 since this change will undo it anyway; @ZeldaZach would you like me to create a PR?

Comment (ZeldaZach) [reply cockatrice/src/gamesmodel.cpp:319]: Yes please

File: cockatrice/src/gameselector.cpp (hunk 2 above)
Comment (knitknit) [reply cockatrice/src/gameselector.cpp:297]: Oh fair point - everything is set in the constructor; I think I can safely remove this check.

File: cockatrice/src/gameselector.cpp (hunk 1 above)
Comment (knitknit) [reply cockatrice/src/gameselector.cpp:303]: (Removing this check per other discussion)

File: cockatrice/src/gamesmodel.cpp (hunk 3 above)
Comment (knitknit) [reply cockatrice/src/gamesmodel.cpp:319]: Done, #3988. I'll double check this behavior with this PR (I think it needed to be guarded behind "showfilters")

Comment (knitknit) [reply cockatrice/src/gamesmodel.cpp:319]: Confirmed this should be fixed with next commit :)

**Comment by ebbit1q** [comment]
Still crashes when trying to view a user's games, did you test this locally? You can follow the steps in #3979 to reproduce.

**Comment by knitknit** [comment]
> Still crashes when trying to view a user's games, did you test this locally? You can follow the steps in #3979 to reproduce.

So strange! I just brought up a fresh build with the change again and I don't see it crashing. Maybe this is a difference between Mac and Windows?

Just to make sure we're talking about the same thing - what do you mean by crash? I assume the client totally freezes and/or exits out? Or does it appear fine to a user but show errors in a console somewhere? (Sorry if these are silly questions, still a new contributor.)

**Comment by ebbit1q** [comment]
There are no silly questions, by crash I mean it segfaults the same as in the linked ticket I made, anyway I must have messed up building (probably was still on master) because I built it again and it now works fine.

**Comment by tooomm** [comment]
Will finally get around to check this later today, sorry. 🙈

**Comment by ebbit1q** [comment]
Travis finished but doesn't update on github https://travis-ci.org/github/Cockatrice/Cockatrice/builds/683312387

This is really annoying cus it blocks merge

**Comment by knitknit** [comment]
> Travis finished but doesn't update on github https://travis-ci.org/github/Cockatrice/Cockatrice/builds/683312387
> 
> This is really annoying cus it blocks merge

Anything I can help with from my end to re-run or update it?

**Comment by ebbit1q** [comment]
No, this is an issue with our ci system that automatically validates pull requests, if someone else tests this pr to work well I'll instead merge it manually circumventing the web interface.

**Comment by tooomm** [comment]
Hmm, this took me a while as I'm still not sure what (or how) to write (it) exactly...

First things first:
The feature seems to work. I also prefer this over the initial approach in #3946. 👍 

<br>

**Note:** This PR adds the counter of currently visible/shown games requested in https://github.com/Cockatrice/Cockatrice/issues/583 and extends it for the number of total games in this specific room on the server. With a different location to display it. :)

<br>

**But...**
I created the requesting issue (#3068) with the problem in mind, that a user should quickly & easily know once **default filters are altered**. I realized that I worded that not ideal as I also wrote "clarify to the user that the game list doesn't show all available games" next to its title and the quote.

<br>

### To wrap it up - what this PR basically does
- Show number of displayed games
- Show number of total games in this room (not on all server, which is good!)
- `Clear filter` button is disabled after click (👍)

### What this PR doesn't
From this PR description:
>Short roundup of the initial problem
>
>Cockatrice remembers filters applied between sessions, but **users were not alerted if any filters were altered from their default values.**

I'm still pretty sure - even with this PR - users don't know if default filters do apply or if they are altered.
Showing all existing games /= default filter settings!
Most of the created games are not relevant to the user normally as they are already running/filled up (=unavailable games). Hence they are not shown on default.
Only hitting the clear button indicates the user that default values are used, because it disables the button. On the other hand, setting default values manually still shows the button active...

<br>

What to do with this PR now? It still adds a nice value to the client.

I propose to also disable the `Clear filter` button if default filters are set by hand.
Additionally, IMO the ideal solution would be to move the game count to the headline above the game list, and just show a simple text hint next to the filter buttons once default is altered.

Thoughts?

**Comment by ebbit1q** [comment]
The main issue this addresses is the people complaining about not seeing any games going on. I'd like the amount of games shown in the ui somewhere merged as quickly as possible. The reset filter button behavior can be split off if need be.

**Comment by knitknit** [comment]
Sounds good, thanks all! @tooomm feel free to reopen and assign #3068 to me and we can discuss the idea of default filters there, if we'd like to tweak it?
