### PR TITLE
fix bug with phase highlighting in replays

### LINKED ISSUE #5160: Phase marker highlighting in replays glitches out after backwards skips
While watching a replay, after doing some backward skips, the phase marker will have multiple phases highlighted.
Screenshot 2024-11-05 at 1 30 03 AM

_______________________________________________________________________________________

**Steps to reproduce:**
- Watch a replay
- Skip to end of replay
- Backwards skip a few time through the replay, making sure to skip back through multiple phase changes.

### PR DESCRIPTION
**Pull request by RickyRister**
## Related Ticket(s)
- Fixes #5160

## Short roundup of the initial problem
When watching a replay, if you do backward skips, the phase button highlighting will bug out. Multiple phases will stay highlighted.

## What will change with this Pull Request?
- The `rewound()` signal from `ReplayTimelineWidget` will now trigger `TabGame` to properly reset the phases.
- Added a `reset()` method to the phase toolbar classes that will immediately reset the `PhaseButton`, skipping any animations.
- Also did some minor refactoring of `PhaseButton::updateAnimation()` when fixing a new bug that I introduced while fixing this bug.

### CODE REVIEW

**Review by ZeldaZach — APPROVED** [review]

File: cockatrice/src/client/ui/phases_toolbar.cpp [hunk 1]
```diff
@@ -74,13 +74,26 @@ void PhaseButton::updateAnimation()
...
+}
+
+/**
+ * @brief Immediately resets the button to the inactive state, without going through the animation.
+ */
+void PhaseButton::reset()
+{
+    activeAnimationTimer->stop();
+    active = false;
+    activeAnimationCounter = highlightable ? 0 : 9;
```
Comment (ebbit1q) [inline cockatrice/src/client/ui/phases_toolbar.cpp:96]: I think this'd read better as a simple if statement
```suggestion
    if (highlightable) {
        activeAnimationCounter = 0;
    }
```

**Review by ebbit1q — APPROVED** [review]
thank you
