### PR TITLE
Split card handling added to cmc filter

### LINKED ISSUE #3071: cmc filter for split/aftermath cards not working
<b>Info:</b>
Client Version: 2.5.0-custom(3372007) (2018-01-31)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.3

__________

The filter for cmc in the deck editor isn't working for split and aftermath cards.
No matter if you filter for `4`, `6` or `10` cmc... [Commit // Memory](https://scryfall.com/card/akh/211) isn't found.

### PR DESCRIPTION
**Pull request by Vafthrudnir**
## Related Ticket(s)
- Fixes #3071 

## Short roundup of the initial problem
CMC filter didn't work on split cards in the deck builder

## Screenshots
split_card_filter

### CODE REVIEW

**Comment by tooomm** [comment]
I found a very similar issue than #3071 --> #2546

Will test both later today.

**Comment by Vafthrudnir** [comment]
Thanks @Daenyth !
Rarity filter still doesn't work on split cards, because rarity isn't saved for them to the cards.xml for some reason. The rest seemed to be ok.

File: cockatrice/src/filtertree.cpp [hunk 1]
```diff
@@ -231,7 +231,22 @@ bool FilterItem::acceptManaCost(const CardInfoPtr info) const
 
 bool FilterItem::acceptCmc(const CardInfoPtr info) const
 {
-    return relationCheck(info->getCmc().toInt());
+    bool convertSuccess;
+    int cmcInt = info->getCmc().toInt(&convertSuccess);
+    // if conversion failed, check for the "//" separator used in split cards
+    if (!convertSuccess) {
+        int cmcSum = 0;
+        foreach (QString cmc, info->getCmc().split("//")) {
```
Comment (ZeldaZach) [inline cockatrice/src/filtertree.cpp]: can you change this to `for(QString cmc : info->getCMC().split("//")) {` ? I'm trying to remove the foreach from the codebase as it's not proper C++

Comment (Vafthrudnir) [reply cockatrice/src/filtertree.cpp]: sure

**Comment by tooomm** [comment]
>Rarity filter still doesn't work on split cards, because rarity isn't saved for them to the cards.xml for some reason. The rest seemed to be ok.

Good that you mention something like that, I guess we were not aware of that as of now. Thanks :)
Issue created:  #3091

File: cockatrice/src/filtertree.cpp (hunk 1 above)
Comment (Daenyth) [reply cockatrice/src/filtertree.cpp]: We should see if we can add a custom lint rule to codacy
