### PR TITLE
Braces left in for split mana costs in xml

### LINKED ISSUE #3017: Cards with split mana have their mana cost wrong
It looks like all split mana cards with more than 1cmc like the ones below have their mana cost wrong:
split mana cards

It should be `GG/GW/WW` (or `GG/WG/WW`) for the selected Guildmage.
But it only wrongly shows `G/WG/W`.

In cards.xml the data is also wrong: `<manacost>G/WG/W</manacost>`
In AllSets.json all occurrences of the card have correct data: `"manaCost": "{G/W}{G/W}",`

### PR DESCRIPTION
**Pull request by Vafthrudnir**
## Related Ticket(s)
- Fixes #3017

## Short roundup of the initial problem
Split mana costs were not displayed correctly: without the braces `{G/W}{G/W}` looked like `G/WG/W`, which can be easily misinterpreted.

## Screenshots
split_mana_costs

### CODE REVIEW

File: oracle/src/oracleimporter.cpp [hunk 1]
```diff
@@ -78,9 +78,17 @@ CardInfoPtr OracleImporter::addCard(const QString &setName,
...
+        // Remove {} around mana costs, except if it's split cost
+        QStringList symbols = cardCost.split("}");
+        QString formattedCardCost = QString();
+        for (QString symbol : symbols) {
+            if (symbol.contains(QRegExp("[BWUGR]/[BWUGR]"))) {
+                symbol.append("}");
+            } else {
+                symbol.remove(QChar('{'));
+            }
+            formattedCardCost.append(symbol);
```
Comment (ctrlaltca) [inline oracle/src/oracleimporter.cpp]: How is this working at all if `formattedCardCost` is not used anywhere?
