### PR TITLE
Fix game phases not being translated in game log

### LINKED ISSUE #5789: Game Phases are not translated in game log
**System Information:**
Win10

_______________________________________________________________________________________

Game phases are not translated in the game log even though matching strings exist.
If this is inteded behavior ignore and close this issue.

Image

Image

_______________________________________________________________________________________

**Steps to reproduce:**

Enter any game in a language that's not english and change turn phases.

### PR DESCRIPTION
**Pull request by RickyRister**
## Related Ticket(s)
- Fixes #5789 

## Short roundup of the initial problem

Phase names aren't being translated because the translation happens in the `Phase`'s constructor, but Cockatrice creates a const static array of `Phase`s and uses that for the entire runtime of the program

## What will change with this Pull Request?

https://github.com/user-attachments/assets/a9e9ea86-f60f-4185-a1be-97602d8d66a7

- Change `Phase`'s `name` into a private field with a getter.
  - translate the name in the getter.

### CODE REVIEW

**Review by ebbit1q — APPROVED** [review]
seems good

File: cockatrice/src/game/phase.cpp [hunk 1]
```diff
@@ -1,8 +1,16 @@
...
 {
-    name = tr(_name);
+}
+
+/**
+ * @return The translated name for the phase
+ */
+QString Phase::getName() const
+{
+    return tr(name.toUtf8().data());
```
Comment (ebbit1q) [inline cockatrice/src/game/phase.cpp:13]: does tr require it to be a char array? doesn't it work on qstrings too?

Comment (RickyRister) [reply cockatrice/src/game/phase.cpp:13]: surprisingly enough, no

**Review by ZeldaZach — APPROVED** [review]
