### PR TITLE
additional null checks in player.cpp

### LINKED ISSUE #2489: Client Crash
<b>OS:</b>
Mac 10.12.3

<b>Cockatrice version:</b>
Version a8a4557 (2017-03-16)

___

This has happened twice in 5 minutes, so something is obv triggering it.

```
Process:               cockatrice [71624]
Path:                  /Applications/cockatrice.app/Contents/MacOS/cockatrice
Identifier:            com.cockatrice.Cockatrice
Version:               0.0.1~git20170316.a8a4557 (0.0.1~git20170316.a8a4557)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           cockatrice [71624]
User ID:               501

Date/Time:             2017-03-17 00:41:49.942 -0400
OS Version:            Mac OS X 10.12.3 (16D32)
Report Version:        12
Anonymous UUID:        E150293E-C093-D738-4100-6D0B5D37A6C4

Sleep/Wake UUID:       71D2BA49-D6DA-4EA6-AAB7-49171DC548CD

Time Awake Since Boot: 970000 seconds
Time Since Wake:       11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
*** error for object 0x7fd9035734a8: incorrect checksum for freed object - object was probably modified after being freed.
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffcdab0dd6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffcdb9c787 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffcda16420 abort + 129
3   libsystem_malloc.dylib        	0x00007fffcdb10f21 szone_error + 626
4   libsystem_malloc.dylib        	0x00007fffcdb05c44 tiny_malloc_from_free_list + 1148
5   libsystem_malloc.dylib        	0x00007fffcdb044ca szone_malloc_should_clear + 400
6   libsystem_malloc.dylib        	0x00007fffcdb042da malloc_zone_malloc + 107
7   libsystem_malloc.dylib        	0x00007fffcdb03258 malloc + 24
8   com.apple.CoreGraphics        	0x00007fffb88ef4be std::__1::list<CG::Chunk, CG::Allocator<CG::Chunk> >::list(std::__1::list<CG::Chunk, CG::Allocator<CG::Chunk> > const&) + 70
9   com.apple.CoreGraphics        	0x00007fffb88ef6c9 std::__1::vector<CG::Path::Subpath, CG::Allocator<CG::Path::Subpath> >::__swap_out_circular_buffer(std::__1::__split_buffer<CG::Path::Subpath, CG::Allocator<CG::Path::Subpath>&>&) + 49
10  com.apple.CoreGraphics        	0x00007fffb88ef66b void std::__1::vector<CG::Path::Subpath, CG::Allocator<CG::Path::Subpath> >::__push_back_slow_path<CG::Path::Subpath const&>(CG::Path::Subpath const&&&) + 241
11  com.apple.CoreGraphics        	0x00007fffb88eeecc CG::Path::Sequence::append(CG::Path::Shape*, CGAffineTransform const*) + 154
12  com.apple.CoreGraphics        	0x00007fffb8b85b23 CGPathAddRects + 200
13  com.apple.CoreGraphics        	0x00007fffb8aea35a CGContextClipToRects + 141
14  com.apple.AppKit              	0x00007fffb60b48da -[NSView _drawRect:clip:] + 1733
15  com.apple.AppKit              	0x00007fffb60b35f3 -[NSView _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:] + 4870
16  com.apple.AppKit              	0x00007fffb60b1e0f -[NSThemeFrame _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:] + 334
17  com.apple.AppKit              	0x00007fffb60b0238 -[NSView _displayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:] + 2452
18  com.apple.AppKit              	0x00007fffb60abb25 -[NSView displayIfNeeded] + 1748
19  com.apple.AppKit              	0x00007fffb60ab437 -[NSWindow displayIfNeeded] + 230
20  com.apple.AppKit              	0x00007fffb6809f3f ___NSWindowGetDisplayCycleObserver_block_invoke.6228 + 277
21  com.apple.AppKit              	0x00007fffb60aaf15 __37+[NSDisplayCycle currentDisplayCycle]_block_invoke + 454
22  com.apple.QuartzCore          	0x00007fffbe159a96 CA::Transaction::run_commit_handlers(CATransactionPhase) + 46
23  com.apple.QuartzCore          	0x00007fffbe261800 CA::Context::commit_transaction(CA::Transaction*) + 160
24  com.apple.QuartzCore          	0x00007fffbe158631 CA::Transaction::commit() + 475
25  com.apple.AppKit              	0x00007fffb638df1d __37+[NSDisplayCycle currentDisplayCycle]_block_invoke.31 + 323
26  com.apple.CoreFoundation      	0x00007fffb844a397 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
27  com.apple.CoreFoundation      	0x00007fffb844a307 __CFRunLoopDoObservers + 391
28  com.apple.CoreFoundation      	0x00007fffb842af39 __CFRunLoopRun + 873
29  com.apple.CoreFoundation      	0x00007fffb842a974 CFRunLoopRunSpecific + 420
30  com.apple.HIToolbox           	0x00007fffb79b6a5c RunCurrentEventLoopInMode + 240
31  com.apple.HIToolbox           	0x00007fffb79b6891 ReceiveNextEventCommon + 432
32  com.apple.HIToolbox           	0x00007fffb79b66c6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
33  com.apple.AppKit              	0x00007fffb5f5c5b4 _DPSNextEvent + 1120
34  com.apple.AppKit              	0x00007fffb66d6d6b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2789
35  com.apple.AppKit              	0x00007fffb5f50f35 -[NSApplication run] + 926
36  libqcocoa.dylib               	0x000000010d1e2143 0x10d1bd000 + 151875
37  org.qt-project.QtCore         	0x000000010b47b811 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 417
38  org.qt-project.QtCore         	0x000000010b4800a7 QCoreApplication::exec() + 343
39  com.cockatrice.Cockatrice     	0x00000001096b24ac main + 1660
40  libdyld.dylib                 	0x00007fffcd982255 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fffcdab14e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffcdb99791 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffcdb991ed start_wqthread + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fffcdab14e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffcdb99791 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffcdb991ed start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fffcdab14e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffcdb99791 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffcdb991ed start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fffcdab14e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffcdb99791 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffcdb991ed start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fffcdab14e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffcdb99791 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffcdb991ed start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fffcdab14e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffcdb995fe _pthread_wqthread + 1023
2   libsystem_pthread.dylib       	0x00007fffcdb991ed start_wqthread + 13

Thread 7:: Qt bearer thread
0   libsystem_kernel.dylib        	0x00007fffcdab2232 poll + 10
1   org.qt-project.QtCore         	0x000000010b4d2580 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 544
2   org.qt-project.QtCore         	0x000000010b4d3c47 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 871
3   org.qt-project.QtCore         	0x000000010b47b811 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 417
4   org.qt-project.QtCore         	0x000000010b2b8fe3 QThread::exec() + 115
5   org.qt-project.QtCore         	0x000000010b2bc9ba 0x10b292000 + 174522
6   libsystem_pthread.dylib       	0x00007fffcdb99aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffcdb999f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffcdb991fd thread_start + 13

Thread 8:: QThread
0   libsystem_kernel.dylib        	0x00007fffcdab2232 poll + 10
1   org.qt-project.QtCore         	0x000000010b4d23d0 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 112
2   org.qt-project.QtCore         	0x000000010b4d3c47 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 871
3   org.qt-project.QtCore         	0x000000010b47b811 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 417
4   org.qt-project.QtCore         	0x000000010b2b8fe3 QThread::exec() + 115
5   org.qt-project.QtCore         	0x000000010b2bc9ba 0x10b292000 + 174522
6   libsystem_pthread.dylib       	0x00007fffcdb99aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffcdb999f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffcdb991fd thread_start + 13

Thread 9:
0   libsystem_kernel.dylib        	0x00007fffcdab14e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffcdb99791 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffcdb991ed start_wqthread + 13

Thread 10:: QFileInfoGatherer
0   libsystem_kernel.dylib        	0x00007fffcdab0c86 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffcdb9a96a _pthread_cond_wait + 712
2   org.qt-project.QtCore         	0x000000010b2bdf3b 0x10b292000 + 180027
3   org.qt-project.QtCore         	0x000000010b2bded2 QWaitCondition::wait(QMutex*, unsigned long) + 162
4   org.qt-project.QtWidgets      	0x000000010aa42fb2 0x10a7ef000 + 2441138
5   org.qt-project.QtCore         	0x000000010b2bc9ba 0x10b292000 + 174522
6   libsystem_pthread.dylib       	0x00007fffcdb99aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffcdb999f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffcdb991fd thread_start + 13

Thread 11:: QFileInfoGatherer
0   libsystem_kernel.dylib        	0x00007fffcdab0c86 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffcdb9a96a _pthread_cond_wait + 712
2   org.qt-project.QtCore         	0x000000010b2bdf3b 0x10b292000 + 180027
3   org.qt-project.QtCore         	0x000000010b2bded2 QWaitCondition::wait(QMutex*, unsigned long) + 162
4   org.qt-project.QtWidgets      	0x000000010aa42fb2 0x10a7ef000 + 2441138
5   org.qt-project.QtCore         	0x000000010b2bc9ba 0x10b292000 + 174522
6   libsystem_pthread.dylib       	0x00007fffcdb99aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffcdb999f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffcdb991fd thread_start + 13

Thread 12:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fffcdaa938a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fffcdaa87d7 mach_msg + 55
2   com.apple.CoreFoundation      	0x00007fffb842bc94 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation      	0x00007fffb842b121 __CFRunLoopRun + 1361
4   com.apple.CoreFoundation      	0x00007fffb842a974 CFRunLoopRunSpecific + 420
5   com.apple.AppKit              	0x00007fffb60a9a62 _NSEventThread + 205
6   libsystem_pthread.dylib       	0x00007fffcdb99aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffcdb999f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffcdb991fd thread_start + 13

Thread 13:: QThread
0   libsystem_kernel.dylib        	0x00007fffcdab2232 poll + 10
1   org.qt-project.QtCore         	0x000000010b4d2580 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 544
2   org.qt-project.QtCore         	0x000000010b4d3c47 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 871
3   org.qt-project.QtCore         	0x000000010b47b811 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 417
4   org.qt-project.QtCore         	0x000000010b2b8fe3 QThread::exec() + 115
5   org.qt-project.QtCore         	0x000000010b2bc9ba 0x10b292000 + 174522
6   libsystem_pthread.dylib       	0x00007fffcdb99aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffcdb999f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffcdb991fd thread_start + 13

Thread 14:
0   libsystem_kernel.dylib        	0x00007fffcdab14e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffcdb99791 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffcdb991ed start_wqthread + 13

Thread 15:: QNetworkAccessManager thread
0   libsystem_kernel.dylib        	0x00007fffcdab2232 poll + 10
1   org.qt-project.QtCore         	0x000000010b4d23d0 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 112
2   org.qt-project.QtCore         	0x000000010b4d3c47 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 871
3   org.qt-project.QtCore         	0x000000010b47b811 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 417
4   org.qt-project.QtCore         	0x000000010b2b8fe3 QThread::exec() + 115
5   org.qt-project.QtCore         	0x000000010b2bc9ba 0x10b292000 + 174522
6   libsystem_pthread.dylib       	0x00007fffcdb99aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffcdb999f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffcdb991fd thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff5659d8e8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007fff5659d910  rsp: 0x00007fff5659d8e8
   r8: 0x00000000fffffff0   r9: 0x00007fff565a0c68  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x0000000000000001  r13: 0x000000010db8f000  r14: 0x00007fffd67cf3c0  r15: 0x000000010a45c000
  rip: 0x00007fffcdab0dd6  rfl: 0x0000000000000206  cr2: 0x00007fffd67b1128
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133


Binary Images:
       0x10965f000 -        0x109e29fff +com.cockatrice.Cockatrice (0.0.1~git20170316.a8a4557 - 0.0.1~git20170316.a8a4557) <89C9AC54-EC91-33FB-A798-AB69174C2250> /Applications/cockatrice.app/Contents/MacOS/cockatrice
       0x10a349000 -        0x10a3beffb +org.qt-project.QtMultimedia (5.8 - 5.8.0) <04CB5AE0-FDBD-3C63-8E10-49304DBE2EB1> /Applications/cockatrice.app/Contents/Frameworks/QtMultimedia.framework/Versions/5/QtMultimedia
       0x10a40e000 -        0x10a439ff7 +org.qt-project.QtPrintSupport (5.8 - 5.8.0) <F2E506B8-77BA-3891-B45B-81BA70D7A1D0> /Applications/cockatrice.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x10a45f000 -        0x10a493fff +org.qt-project.QtSvg (5.8 - 5.8.0) <C01B43AE-9910-31E1-A4B4-3A7D5AE39DE1> /Applications/cockatrice.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
       0x10a4b2000 -        0x10a5baff3 +libprotobuf.12.dylib (0) <F8C8E761-318E-3D1A-B9BC-46784C1F7F28> /Applications/cockatrice.app/Contents/MacOS/libprotobuf.12.dylib
       0x10a6aa000 -        0x10a7abff7 +org.qt-project.QtNetwork (5.8 - 5.8.0) <A1AE009D-BEC1-3AF8-9CD3-840BE8A4E3BF> /Applications/cockatrice.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10a7ef000 -        0x10ac54ff3 +org.qt-project.QtWidgets (5.8 - 5.8.0) <317A278B-EF4E-35C6-B2D4-E57DA0B78E9B> /Applications/cockatrice.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10adb6000 -        0x10b1a0ff3 +org.qt-project.QtGui (5.8 - 5.8.0) <C420B169-71D3-3AC7-815A-EF64D5817DD3> /Applications/cockatrice.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10b292000 -        0x10b750ff7 +org.qt-project.QtCore (5.8 - 5.8.0) <6B4B8877-A22A-3BB7-82F5-AFDAAB75069B> /Applications/cockatrice.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10b7ff000 -        0x10b803ffb  com.apple.agl (3.3.1 - AGL-3.3.1) <4E968AA4-9FB1-3425-AC1D-4853BC1182E3> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
       0x10d1bd000 -        0x10d30dff3 +libqcocoa.dylib (0) <BF4EF742-5F4C-31D4-8A43-F9320D754FCF> /Applications/cockatrice.app/Contents/Plugins/platforms/libqcocoa.dylib
       0x10db4a000 -        0x10db50fff +libqgif.dylib (0) <5A685475-2D6B-3CC6-85FC-798F10EFAE97> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqgif.dylib
       0x10db9b000 -        0x10dba2ffb +libqicns.dylib (0) <AC6DD03F-03E8-378B-AE53-C6282758E289> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqicns.dylib
       0x10dba7000 -        0x10dbacff7 +libqmacjp2.dylib (0) <E5B74F3F-48E4-3A0F-A23B-8747304FC9E8> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqmacjp2.dylib
       0x110625000 -        0x110b73ff7  com.apple.driver.AppleIntelHD5000GraphicsGLDriver (10.22.29 - 10.2.2) <7FC0294C-B7AA-3247-9728-227622A83AEF> /System/Library/Extensions/AppleIntelHD5000GraphicsGLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsGLDriver
       0x110d84000 -        0x110dfbfff  com.apple.driver.AppleIntelHD5000GraphicsMTLDriver (10.22.29 - 10.2.2) <320C9191-9ACF-3128-A131-B93E4EBFE265> /System/Library/Extensions/AppleIntelHD5000GraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsMTLDriver
       0x110ee9000 -        0x110eeeff3 +libqico.dylib (0) <589E7CB5-CF9C-33BC-A60E-224E01E247E6> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqico.dylib
       0x110ef3000 -        0x110ef7fff +libqsvg.dylib (0) <16742A59-57F4-3EC3-A552-68D9C147C805> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqsvg.dylib
       0x1111d2000 -        0x11120cff7 +libqjpeg.dylib (0) <F0CE734B-2433-3DF7-A7A9-ADB6763F5469> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqjpeg.dylib
       0x111212000 -        0x111216fff +libqtga.dylib (0) <993C895A-1B86-3007-8D76-256DF48490A4> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqtga.dylib
       0x11121a000 -        0x11126cff7 +libqtiff.dylib (0) <E3756568-9B6D-3980-83B8-0AD98C377E87> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqtiff.dylib
       0x111274000 -        0x111278fff +libqwbmp.dylib (0) <8E714D9F-228B-3063-B465-7C9B727F0DA0> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqwbmp.dylib
       0x11127c000 -        0x11130dff3 +libqwebp.dylib (0) <637813AE-BAD1-3360-BE8A-D04E73C7255C> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqwebp.dylib
       0x1143d6000 -        0x114413267  dyld (421.2) <947FC440-80F9-32F7-A773-6FC418FE1AB7> /usr/lib/dyld
       0x11c3c0000 -        0x11c3c4fff  libFontRegistryUI.dylib (196.3) <FA631B39-8678-372D-B320-FD2DAD848DD6> /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Resources/libFontRegistryUI.dylib
    0x7fffb39de000 -     0x7fffb422afff  com.apple.GeForceGLDriver (10.14.20 - 10.1.4) <E96D52FC-436A-304B-9C89-81DF0923A16D> /System/Library/Extensions/GeForceGLDriver.bundle/Contents/MacOS/GeForceGLDriver
    0x7fffb422b000 -     0x7fffb4af9ff3  libclh.dylib (4.0.3 - 4.0.3) <17D1CEB7-CFC3-356B-92B3-CE3E4E9A4618> /System/Library/Extensions/GeForceGLDriver.bundle/Contents/MacOS/libclh.dylib
    0x7fffb4afa000 -     0x7fffb4c0aff7  com.apple.GeForceMTLDriver (10.14.20 - 10.1.4) <F2438C2D-0DF4-35D6-BD4D-5A8551038779> /System/Library/Extensions/GeForceMTLDriver.bundle/Contents/MacOS/GeForceMTLDriver
    0x7fffb4f37000 -     0x7fffb4f37fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <D700DBDF-69AE-37A2-B9C7-0961CF0B6841> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fffb4f38000 -     0x7fffb4f4fffb  libCGInterfaces.dylib (331.5) <518D3064-6E1E-3DF6-881B-57867DFE9B1E> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fffb4f50000 -     0x7fffb5469feb  com.apple.vImage (8.1 - ???) <6408805B-67E9-3874-8D32-0BB814CE5CDA> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fffb546a000 -     0x7fffb55daff3  libBLAS.dylib (1185) <C7E42BBE-2337-3AEF-9C45-A2F2CB1A5B3E> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fffb55db000 -     0x7fffb55efffb  libBNNS.dylib (14) <CFDEE88D-E002-347C-BC68-83099651585B> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fffb55f0000 -     0x7fffb59e6fef  libLAPACK.dylib (1185) <2E8201CB-9A41-3D65-853E-841917FCE77B> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fffb59e7000 -     0x7fffb59fdfff  libLinearAlgebra.dylib (1185) <8CC29DE1-A231-3D5E-B5F1-DCC309036FE0> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fffb59fe000 -     0x7fffb5a04fff  libQuadrature.dylib (3) <120F6228-A3D4-3184-89D7-785ADC2AC715> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fffb5a05000 -     0x7fffb5a19ff7  libSparseBLAS.dylib (1185) <C35235B7-CFA6-39A7-BD6E-79F4D9CAFD36> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fffb5a1a000 -     0x7fffb5ba1fe7  libvDSP.dylib (600) <F59348AA-E1D3-3A27-8AB5-F546D38BFB76> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fffb5ba2000 -     0x7fffb5c54ffb  libvMisc.dylib (600) <70D4B548-47EE-3C6B-A93B-3EA6B60701E0> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fffb5c55000 -     0x7fffb5c55fff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <A395B521-8E54-30F2-B4FE-355D68900DAF> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fffb5f15000 -     0x7fffb6ce7ff3  com.apple.AppKit (6.9 - 1504.81.100) <0CCB2E18-076E-3D8A-A777-A6E57EF2570A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fffb6cf9000 -     0x7fffb6cf9fff  com.apple.ApplicationServices (48 - 48) <237200C2-28A6-3C19-B34B-53C953F8AE42> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fffb6cfa000 -     0x7fffb6d68ff7  com.apple.ApplicationServices.ATS (377 - 422.2) <3680281F-DB99-3CA2-9C76-CABFC8DBC980> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fffb6e02000 -     0x7fffb6f31fff  libFontParser.dylib (194.6) <F3DF2CF7-B25D-30BB-9EE6-1EA9F3B8A066> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
    0x7fffb6f32000 -     0x7fffb6f7cfff  libFontRegistry.dylib (196.3) <855AF921-EAE0-3D07-B161-5EF09806B643> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fffb6fd9000 -     0x7fffb700cff7  libTrueTypeScaler.dylib (194.6) <D0D7DA50-DF52-3D24-AFD2-03B336AA1929> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
    0x7fffb7078000 -     0x7fffb7122ff7  com.apple.ColorSync (4.12.0 - 502.1) <5F244DE3-A6E8-335F-AE3B-25F0E407DD62> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fffb7123000 -     0x7fffb7173ff7  com.apple.HIServices (1.22 - 591) <34C950CC-1084-354A-BCE6-9396EDB29DF8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fffb7174000 -     0x7fffb7183ff3  com.apple.LangAnalysis (1.7.0 - 1.7.0) <47D1A017-91A4-37F3-93E0-3923CD6ED2DE> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fffb7184000 -     0x7fffb71d1fff  com.apple.print.framework.PrintCore (12 - 491) <B7CC15C1-AF50-37F3-8AF6-65F8CDC323F0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fffb71d2000 -     0x7fffb720dfff  com.apple.QD (3.12 - 310) <8F718290-DD82-36CE-9AF0-EFB6D31A49F4> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fffb720e000 -     0x7fffb7219ff7  com.apple.speech.synthesis.framework (6.3.3 - 6.3.3) <629831B1-B13C-30F5-AE16-6BB9037E3753> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fffb721a000 -     0x7fffb742afff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <A1B98513-C19E-376F-8DAF-71BB2F263C5F> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fffb742b000 -     0x7fffb742bfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <55C6A958-D52B-3D81-B230-EB949212B5D9> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fffb7594000 -     0x7fffb7967ff7  com.apple.CFNetwork (807.2.14 - 807.2.14) <9702C8B9-2984-3DD9-9C59-A83499C2DBC4> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fffb7981000 -     0x7fffb7981fff  com.apple.Carbon (154 - 157) <1BF9C0EB-45A0-3584-85DC-F64A9914F40D> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fffb7982000 -     0x7fffb7985fff  com.apple.CommonPanels (1.2.6 - 98) <6A71E8CB-3BF7-3A49-A5F7-0579BAE1219D> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fffb7986000 -     0x7fffb7c8eff7  com.apple.HIToolbox (2.1.1 - 856.13) <98D5D2A7-55A6-31A7-9056-CC48EBB16654> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fffb7c8f000 -     0x7fffb7c92ff7  com.apple.help (1.3.5 - 49) <27C5F9FE-838F-3807-A4AC-D99470185B10> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fffb7c93000 -     0x7fffb7c98fff  com.apple.ImageCapture (9.0 - 9.0) <E3E757FD-4060-33A4-A2AC-85EFBD987FCE> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fffb7c99000 -     0x7fffb7d30ff3  com.apple.ink.framework (10.9 - 219) <B44BA36D-7549-3EB2-8CF6-E171885194FB> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fffb7d31000 -     0x7fffb7d4bfff  com.apple.openscripting (1.7 - 172) <B204BF70-C4AA-3699-8493-66E6645A92A8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fffb7d4c000 -     0x7fffb7d4dff3  com.apple.print.framework.Print (12 - 267) <CA7E9448-0903-34C8-AAF6-9070B52BF70E> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fffb7d4e000 -     0x7fffb7d50ff7  com.apple.securityhi (9.0 - 55006) <ACD20DC1-FBDE-3E1B-91BF-867FE7849CBC> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fffb7d51000 -     0x7fffb7d57ff7  com.apple.speech.recognition.framework (6.0.1 - 6.0.1) <A20B0F7B-C32A-3FF1-BB75-BAC0EE4EF889> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fffb7e36000 -     0x7fffb7e36fff  com.apple.Cocoa (6.11 - 22) <CF1AD0E9-2257-35FE-B719-760B58E405C9> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fffb7f76000 -     0x7fffb8006ff7  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <A38A11A5-130B-39CE-BEBA-F5427F6801DC> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fffb8007000 -     0x7fffb801afff  com.apple.CoreBluetooth (1.0 - 1) <76AFC4B4-A9FD-3434-B168-90087E71F5C4> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fffb801b000 -     0x7fffb8315feb  com.apple.CoreData (120 - 752.8) <FE3F152B-4C35-3A58-A0CB-D04EE5908818> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fffb8316000 -     0x7fffb83a2fff  com.apple.CoreDisplay (1.0 - 1) <48B568C0-1E12-34F4-943D-EAB447FBA1BE> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fffb83a3000 -     0x7fffb883dfff  com.apple.CoreFoundation (6.9 - 1348.28) <A40AA224-7A50-3989-95D0-5A228A0E2FAF> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fffb883e000 -     0x7fffb8ec0fff  com.apple.CoreGraphics (2.0 - 1070.13.2) <0685658F-21AE-31D9-8C9A-B92528CDFB59> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fffb8ec1000 -     0x7fffb9103fff  com.apple.CoreImage (12.2.0 - 451.3.1) <CDAD60F3-74F6-3EA5-A8B5-B42476E350FD> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fffb9268000 -     0x7fffb9268fff  com.apple.CoreServices (775.9.7 - 775.9.7) <A5C444F3-408B-3062-AF4B-BF8CD919F221> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fffb9269000 -     0x7fffb92bafff  com.apple.AE (712.2 - 712.2) <342A13C0-4A6A-3947-B66B-0F624A4A7B52> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fffb92bb000 -     0x7fffb9596ff7  com.apple.CoreServices.CarbonCore (1159.5 - 1159.5) <11CC2194-0C9C-397A-B7F9-CDAB9B68D87D> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fffb9597000 -     0x7fffb95cafff  com.apple.DictionaryServices (1.2 - 274) <864F3808-FFDD-3C4B-A5B7-F1A6C4668A86> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fffb95cb000 -     0x7fffb95d3ffb  com.apple.CoreServices.FSEvents (1230 - 1230) <13A2FC17-8F8C-35BF-9584-59FDFB738E2B> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fffb95d4000 -     0x7fffb9740ff7  com.apple.LaunchServices (775.9.7 - 775.9.7) <E350E4F6-822A-3F04-B59B-468A39AF5C64> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fffb9741000 -     0x7fffb97f1fff  com.apple.Metadata (10.7.0 - 1075.28) <DBB524CD-6938-3623-99C2-4B1EC1E1BE58> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fffb97f2000 -     0x7fffb9851fff  com.apple.CoreServices.OSServices (775.9.7 - 775.9.7) <E9625B0B-9AE7-3024-9FEF-FEE0A1876D9D> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fffb9852000 -     0x7fffb98c2fff  com.apple.SearchKit (1.4.0 - 1.4.0) <F1B3EF8D-E820-317C-AC7F-8F056C246874> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fffb98c3000 -     0x7fffb9909ff7  com.apple.coreservices.SharedFileList (38 - 38) <E1400999-1F08-35A1-9D07-27D80A2AF89A> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fffb9996000 -     0x7fffb9ae2ff7  com.apple.CoreText (352.0 - 544.5) <E90EA1D8-3491-3014-9043-9928C4E4349C> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fffb9ae3000 -     0x7fffb9b18fff  com.apple.CoreVideo (1.8 - 234.0) <48C31E93-87C2-31F4-97E7-9E54C1EA8E7D> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fffb9b19000 -     0x7fffb9b8affb  com.apple.framework.CoreWLAN (11.0 - 1200.25.1) <BEBE9C03-3B9A-3948-99E3-CC8148FA2AB5> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fffb9c89000 -     0x7fffb9c8efff  com.apple.DiskArbitration (2.7 - 2.7) <16EA6D93-A2EC-31DB-BF52-C4764E7B1630> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fffb9e1d000 -     0x7fffba1c4ff3  com.apple.Foundation (6.9 - 1349.25) <D820A498-2E62-367D-BC72-5845B14C06E3> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fffba1f0000 -     0x7fffba221fff  com.apple.GSS (4.0 - 2.0) <95FAD1F9-1610-3428-B9B4-D32F67C26574> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fffba2e1000 -     0x7fffba384ffb  com.apple.Bluetooth (5.0.3 - 5.0.3f1) <CCB4E097-1ED0-3439-8450-2B6EFFBC4608> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fffba385000 -     0x7fffba41aff7  com.apple.framework.IOKit (2.0.2 - 1324.30.13) <163BE7FA-B29A-348F-8B5F-E301F2E8C964> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fffba41b000 -     0x7fffba421ffb  com.apple.IOSurface (153.3 - 153.3) <3DD3BF22-0800-31F2-B179-87F87D6F0548> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fffba473000 -     0x7fffba5ccfef  com.apple.ImageIO.framework (3.3.0 - 1582) <564168E7-BEC0-35E3-9BF0-59B65C17225E> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fffba5cd000 -     0x7fffba5d1fff  libGIF.dylib (1582) <040243CD-3A68-3ADC-805C-FE1D17C80028> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fffba5d2000 -     0x7fffba6c2ff7  libJP2.dylib (1582) <A55870F9-F27F-3BD0-BE89-981BFF63D485> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fffba6c3000 -     0x7fffba6e6ffb  libJPEG.dylib (1582) <58C01E72-10A0-313F-8139-ED6E9D087ABB> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fffba6e7000 -     0x7fffba70eff7  libPng.dylib (1582) <F2CC3750-3520-311B-9C66-9D86036375B7> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fffba70f000 -     0x7fffba711ff3  libRadiance.dylib (1582) <C3E9CE5C-1A25-391B-9ACB-556AA065B985> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fffba712000 -     0x7fffba76bff3  libTIFF.dylib (1582) <71ADCD24-67C9-31B5-8E48-A4B89AFBB19F> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fffbb33b000 -     0x7fffbb354ff7  com.apple.Kerberos (3.0 - 1) <49DCBE1A-130C-3FBF-AAEA-AF9A518913AC> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fffbbb52000 -     0x7fffbbbaafff  com.apple.Metal (86.18 - 86.18) <7DFE0437-25A8-3E87-8318-91573C895742> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fffbc47e000 -     0x7fffbc486fff  com.apple.NetFS (6.0 - 4.0) <6614F9B8-0861-338B-8FF0-8E402F96141C> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fffbc65b000 -     0x7fffbc663ff7  libcldcpuengine.dylib (2.8.5) <341EBC48-CCF4-3292-9097-F61715AC573E> /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/libcldcpuengine.dylib
    0x7fffbc82c000 -     0x7fffbc87aff3  com.apple.opencl (2.8.6 - 2.8.6) <553BFCCA-5ACB-3DB0-B958-4BF2DE91838F> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fffbc87b000 -     0x7fffbc894ffb  com.apple.CFOpenDirectory (10.12 - 194) <88E97774-6767-3A01-808B-C923F9310E20> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fffbc895000 -     0x7fffbc8a0ff7  com.apple.OpenDirectory (10.12 - 194) <0E4E32DD-6592-3860-9793-BAED6915AE0D> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fffbc8a1000 -     0x7fffbc8a3fff  libCVMSPluginSupport.dylib (13.0.10) <43D037C3-9254-3601-9F5B-CD637D517758> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fffbc8a4000 -     0x7fffbc8a7ff7  libCoreFSCache.dylib (151.1) <1910EF80-DE30-3817-8FDF-63F3C8B4BA37> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fffbc8a8000 -     0x7fffbc8abfff  libCoreVMClient.dylib (151.1) <8C8E9295-1918-3763-A0B7-6397EB181EF4> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fffbc8ac000 -     0x7fffbc8b4ffb  libGFXShared.dylib (13.0.10) <52E92D3C-25EA-31F9-9885-DC0D886D9143> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fffbc8b5000 -     0x7fffbc8c0fff  libGL.dylib (13.0.10) <B40728B5-13D2-3423-9C39-885B1098698D> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fffbc8c1000 -     0x7fffbc8fdfe7  libGLImage.dylib (13.0.10) <3E856113-9217-3B13-98AD-4D0D356931B6> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fffbc8fe000 -     0x7fffbca74ffb  libGLProgrammability.dylib (13.0.10) <4C3FD24A-1C43-343E-8EBA-BE1FDCE3F74C> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
    0x7fffbca75000 -     0x7fffbcab5ff3  libGLU.dylib (13.0.10) <BBCAA457-BA34-3D13-8845-803C63960E08> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fffbd41d000 -     0x7fffbd42bfff  com.apple.opengl (13.0.10 - 13.0.10) <B11A2E1B-4B1D-3ECD-BADA-3508BE5775BF> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fffbd42c000 -     0x7fffbd5d2fff  GLEngine (13.0.10) <62CCEC13-1EB3-3A65-9224-3DCD2838E0C7> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
    0x7fffbd5d3000 -     0x7fffbd5fdffb  GLRendererFloat (13.0.10) <E508ABC7-3E67-3845-989F-5B764D36FE12> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
    0x7fffbe148000 -     0x7fffbe343ff7  com.apple.QuartzCore (1.11 - 449.41.15) <3CD775C0-683D-3B4E-8EC2-AB1DAC4C3AE9> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fffbe8a9000 -     0x7fffbebc8fff  com.apple.security (7.0 - 57740.31.2) <A47D7BAE-0591-3184-8E44-FB2EB08A19C2> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fffbebc9000 -     0x7fffbec3fff7  com.apple.securityfoundation (6.0 - 55132.20.1) <9407620B-B230-3320-B0B7-5AE59F1D135C> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fffbec69000 -     0x7fffbec6cff3  com.apple.xpc.ServiceManagement (1.0 - 1) <4E24C12E-6164-3A7A-8EB8-C2523492BAE8> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fffbeff3000 -     0x7fffbf064ff7  com.apple.SystemConfiguration (1.14 - 1.14) <D9A57D90-E54F-3E1A-AA2F-F5A694BCE4BB> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fffc169e000 -     0x7fffc16b9ff3  com.apple.AppContainer (4.0 - 307.30.3) <EF4C3C83-6F51-38F7-A3D2-2D46EE4560EB> /System/Library/PrivateFrameworks/AppContainer.framework/Versions/A/AppContainer
    0x7fffc16ba000 -     0x7fffc16c7ff3  com.apple.AppSandbox (4.0 - 307.30.3) <D2C978EB-F4F1-3E79-9DB1-BEE2A92590CE> /System/Library/PrivateFrameworks/AppSandbox.framework/Versions/A/AppSandbox
    0x7fffc16c8000 -     0x7fffc16eaffb  com.apple.framework.Apple80211 (12.0 - 1200.41) <360012DB-DAE7-3EEF-85F0-E5BE1DE3425D> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fffc16eb000 -     0x7fffc16fafdb  com.apple.AppleFSCompression (88 - 1.0) <B6E2148F-BFBF-3F1B-A7DF-0F39190B4C20> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fffc17e9000 -     0x7fffc187497f  com.apple.AppleJPEG (1.0 - 1) <B4C3209B-58A5-359F-A898-F61B6C40E5E9> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fffc1c99000 -     0x7fffc1d17fff  com.apple.backup.framework (1.8.3 - 1.8.3) <B2E28A7A-1727-3052-AA73-CBC108286C07> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fffc299d000 -     0x7fffc29c4ffb  com.apple.ChunkingLibrary (172 - 172) <83E91936-305D-32A4-A256-5582B96B1852> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/Versions/A/ChunkingLibrary
    0x7fffc32ed000 -     0x7fffc32f6ffb  com.apple.CommonAuth (4.0 - 2.0) <830B940B-3523-38DE-996D-695739616D10> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fffc3a16000 -     0x7fffc3a26fff  com.apple.CoreEmoji (1.0 - 39.1) <0A46D6BF-22F3-39AD-B3DC-DE1EE5C442CC> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fffc3d09000 -     0x7fffc3d39ff3  com.apple.CoreServicesInternal (276.2 - 276.2) <7D8DEF04-72F1-39F4-BBFB-09E65D7B8C10> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fffc3fc9000 -     0x7fffc4053fff  com.apple.CoreSymbolication (61050) <F4B7C798-F7B7-3977-AA08-59A03F00308E> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fffc4054000 -     0x7fffc4192fd7  com.apple.coreui (2.1 - 430.6) <99D08D71-3E9D-300C-9EB2-A73F1B5E228C> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fffc4193000 -     0x7fffc4243ff3  com.apple.CoreUtils (5.0 - 500.9) <5567181B-721C-339E-A3DC-579E36D92341> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fffc4293000 -     0x7fffc42f8ff3  com.apple.framework.CoreWiFi (12.0 - 1200.25.1) <BEFA276C-D284-3160-8641-7DD47E38C9D7> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fffc42f9000 -     0x7fffc4306ff7  com.apple.CrashReporterSupport (10.12 - 817) <CB5251B1-5BE5-308B-B30B-0050065E04CC> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fffc4378000 -     0x7fffc4382ff7  com.apple.framework.DFRFoundation (1.0 - 104.14) <258B6CFE-FD64-31C5-9973-2FD80597ECDA> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fffc43b8000 -     0x7fffc442fff7  com.apple.datadetectorscore (7.0 - 539.1) <E9892E38-3D5F-36CF-BDC5-E4E3C5516B55> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fffc446c000 -     0x7fffc44abfff  com.apple.DebugSymbols (137 - 137) <B229F3F7-250B-3151-8048-CEA7BF80FA52> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fffc44ac000 -     0x7fffc45bdfff  com.apple.desktopservices (1.11.3 - 1.11.3) <CCE689AA-85F3-3587-AE12-1231E8ED127E> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fffc48a1000 -     0x7fffc4cd2ff7  com.apple.vision.FaceCore (3.3.2 - 3.3.2) <DEB42099-6927-332C-8D3E-D45096318D25> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fffc6027000 -     0x7fffc6027fff  libmetal_timestamp.dylib (600.0.48.32) <31DF1B9E-0BBF-308B-B78D-11CCE72DAA68> /System/Library/PrivateFrameworks/GPUCompiler.framework/libmetal_timestamp.dylib
    0x7fffc6034000 -     0x7fffc603fff3  libGPUSupportMercury.dylib (13.0.10) <7CC5CEF8-D132-3234-A078-6D080DFC599F> /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib
    0x7fffc62f3000 -     0x7fffc630fff3  com.apple.GenerationalStorage (2.0 - 259.2) <00BF8427-967F-3693-A86F-DA0F29B49BF3> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
    0x7fffc6a0d000 -     0x7fffc6a83fff  com.apple.Heimdal (4.0 - 2.0) <00F00E7E-7EF4-3254-86D3-ADA4F67938CF> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fffc6a84000 -     0x7fffc6a95fff  com.apple.HelpData (2.1.11 - 100) <86213EE9-C049-3084-8824-2A17A8DE2D6B> /System/Library/PrivateFrameworks/HelpData.framework/Versions/A/HelpData
    0x7fffc70a6000 -     0x7fffc70adffb  com.apple.IOAccelerator (289.32 - 289.32) <6395ACEE-5AD7-3536-AF12-FD6565415D94> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fffc70af000 -     0x7fffc70c3ff3  com.apple.IOPresentment (1.0 - 25) <40934217-996A-3DDB-A8C4-484CA0F0222B> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fffc70c4000 -     0x7fffc70e6fff  com.apple.IconServices (74.3 - 74.3) <3F0BD358-D019-3083-82F2-69CCAD5E5D66> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fffc71c9000 -     0x7fffc737ffff  com.apple.LanguageModeling (1.0 - 123.2.4) <FEB98F96-A9BB-3E6C-85B4-B466825B8C92> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fffc7c43000 -     0x7fffc7cbcff7  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <6A759DBA-B7DF-363B-9827-AB1D1129BB34> /System/Library/PrivateFrameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fffc7e3e000 -     0x7fffc7e66fff  com.apple.MultitouchSupport.framework (368.7 - 368.7) <A29E6031-E9A6-353A-BDE5-D8DF20FD393C> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fffc7f15000 -     0x7fffc7f1ffff  com.apple.NetAuth (6.0 - 6.0) <1E7765FC-4580-3CE4-A0F1-CAA22006AE43> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fffc879b000 -     0x7fffc87dcff7  com.apple.PerformanceAnalysis (1.145 - 145) <12640C1F-433D-3CD9-B2A8-048D57B8B56D> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fffc8e7f000 -     0x7fffc8e99fff  com.apple.ProtocolBuffer (1 - 249) <D8B7694B-B598-3728-8583-9C4CC0F05B64> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fffc8eb3000 -     0x7fffc8ed6ff3  com.apple.RemoteViewServices (2.0 - 124) <4765DC2E-CF05-38CF-9564-1FBACB7E167C> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fffc9b42000 -     0x7fffc9b45fff  com.apple.SecCodeWrapper (4.0 - 307.30.3) <1B0B2122-C230-3E3F-8A81-EBD58818586B> /System/Library/PrivateFrameworks/SecCodeWrapper.framework/Versions/A/SecCodeWrapper
    0x7fffc9bd4000 -     0x7fffc9c51ff7  com.apple.Sharing (696.1.22 - 696.1.22) <D0A5C682-8996-3851-B332-AD05301E6FA3> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fffc9c52000 -     0x7fffc9c71ff7  com.apple.shortcut (2.16 - 98) <A7D38F28-73EB-3DF5-AE77-A95E4CB60DB9> /System/Library/PrivateFrameworks/Shortcut.framework/Versions/A/Shortcut
    0x7fffc9c72000 -     0x7fffc9ed1fe7  com.apple.SkyLight (1.600.0 - 122.8) <2B8B6734-2B70-3BD8-BB8E-3338FB2708EE> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fffca0b2000 -     0x7fffca0beff7  com.apple.SpeechRecognitionCore (3.3.2 - 3.3.2) <F9F0FCED-3A72-3639-91F2-B7EF248ED1B9> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fffca7a7000 -     0x7fffca813ff3  com.apple.Symbolication (61080.2) <27A57DC2-FEB7-3D23-AEB5-E3E76C5AAE79> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fffcac0d000 -     0x7fffcac13ff7  com.apple.TCC (1.0 - 1) <956F7C1A-D457-3FE0-9CFE-3F1719F0865C> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fffcaca2000 -     0x7fffcae6aff7  com.apple.TextureIO (1.41 - 1.41) <3A9D9FD9-8997-3BD1-8046-76D0BF709806> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fffcaede000 -     0x7fffcaedffff  com.apple.TrustEvaluationAgent (2.0 - 28) <07C1F711-A1E0-3BAC-8F4D-977516D50925> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fffcaee0000 -     0x7fffcb070ff3  com.apple.UIFoundation (1.0 - 490.7) <047781ED-9E79-361F-8E04-71FF90C650F3> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fffcbacc000 -     0x7fffcbb8fff7  com.apple.ViewBridge (280 - 280) <6D4F6019-5ECC-377B-AF7D-9796E96841CB> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fffcbfb9000 -     0x7fffcbfbffff  com.apple.XPCService (2.0 - 1) <BC3FCE26-6219-3316-949F-37F7005C9A0F> /System/Library/PrivateFrameworks/XPCService.framework/Versions/A/XPCService
    0x7fffcc090000 -     0x7fffcc092ffb  com.apple.loginsupport (1.0 - 1) <4449ACBA-27A8-3311-BD92-CB7E63583FC6> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fffcc0e7000 -     0x7fffcc102ff7  libCRFSuite.dylib (34) <BACC371B-6153-36B5-BC54-3BCF26FBB221> /usr/lib/libCRFSuite.dylib
    0x7fffcc103000 -     0x7fffcc10efff  libChineseTokenizer.dylib (21) <09E74E18-ADB2-30D2-A858-13691CB1186C> /usr/lib/libChineseTokenizer.dylib
    0x7fffcc1a0000 -     0x7fffcc1a1ff3  libDiagnosticMessagesClient.dylib (102) <422911A4-E273-3E88-BFC4-DF6470E48242> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fffcc1a2000 -     0x7fffcc3b5fff  libFosl_dynamic.dylib (16.38) <8232FA8A-F16A-3DC0-AE68-B61EFCD5F4A4> /usr/lib/libFosl_dynamic.dylib
    0x7fffcc3d1000 -     0x7fffcc3d8fff  libMatch.1.dylib (27) <5D52A207-E2AF-3E05-8C51-91C1D82FCEE8> /usr/lib/libMatch.1.dylib
    0x7fffcc3d9000 -     0x7fffcc3d9fff  libOpenScriptingUtil.dylib (172) <D025E180-BB3B-3FFA-98FC-B6835354D723> /usr/lib/libOpenScriptingUtil.dylib
    0x7fffcc3da000 -     0x7fffcc3deff3  libScreenReader.dylib (477.20.6) <8158E263-B7DF-3B0C-BABE-4FE94A53DFE5> /usr/lib/libScreenReader.dylib
    0x7fffcc3df000 -     0x7fffcc3e0ff3  libSystem.B.dylib (1238) <9CB018AF-54E9-300F-82BE-81FE553C9154> /usr/lib/libSystem.B.dylib
    0x7fffcc44c000 -     0x7fffcc477ffb  libarchive.2.dylib (41.41.1) <D53F0A5C-7FAA-3FCF-8A27-B7DF032C4221> /usr/lib/libarchive.2.dylib
    0x7fffcc478000 -     0x7fffcc4f4fc7  libate.dylib (1.12.13) <8A963F37-CB4F-37FB-BFA5-273917C42437> /usr/lib/libate.dylib
    0x7fffcc4f8000 -     0x7fffcc4f8ff3  libauto.dylib (187) <5BBF6A00-CC76-389D-84E7-CA88EDADE683> /usr/lib/libauto.dylib
    0x7fffcc4f9000 -     0x7fffcc509ff3  libbsm.0.dylib (34) <20084796-B04D-3B35-A003-EA11459557A9> /usr/lib/libbsm.0.dylib
    0x7fffcc50a000 -     0x7fffcc518ff7  libbz2.1.0.dylib (38) <6FD3B63F-0F86-3A25-BD5B-E243F58792C9> /usr/lib/libbz2.1.0.dylib
    0x7fffcc519000 -     0x7fffcc56fff7  libc++.1.dylib (307.4) <BEE86868-F831-384C-919E-2B286ACFE87C> /usr/lib/libc++.1.dylib
    0x7fffcc570000 -     0x7fffcc59afff  libc++abi.dylib (307.2) <1CEF8ABB-7E6D-3C2F-8E0A-E7884478DD23> /usr/lib/libc++abi.dylib
    0x7fffcc59b000 -     0x7fffcc5abffb  libcmph.dylib (6) <2B5D405E-2D0B-3320-ABD6-622934C86ABE> /usr/lib/libcmph.dylib
    0x7fffcc5ac000 -     0x7fffcc5c1fc3  libcompression.dylib (34) <1691D6F2-46CD-3DA6-B44F-24CDD9BD0E4E> /usr/lib/libcompression.dylib
    0x7fffcc5c2000 -     0x7fffcc5c2ff7  libcoretls.dylib (121.31.1) <BCC32537-4831-3E9F-876E-8C9F4CF52FD3> /usr/lib/libcoretls.dylib
    0x7fffcc5c3000 -     0x7fffcc5c4ff3  libcoretls_cfhelpers.dylib (121.31.1) <6F37C5AD-7999-3D31-A52F-7AEED935F32D> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fffcc67e000 -     0x7fffcc763ff7  libcrypto.0.9.8.dylib (64.30.2) <D41E1901-06DD-3860-BB4F-B3ACE0284C01> /usr/lib/libcrypto.0.9.8.dylib
    0x7fffcc901000 -     0x7fffcc954ff7  libcups.2.dylib (450) <78243BA4-43AB-3364-8111-8D54D3382621> /usr/lib/libcups.2.dylib
    0x7fffcc9cf000 -     0x7fffcc9cffff  libenergytrace.dylib (15) <A1B040A2-7977-3097-9ADF-34FF181EB970> /usr/lib/libenergytrace.dylib
    0x7fffcc9df000 -     0x7fffcc9e4ff7  libheimdal-asn1.dylib (498.30.1) <4ED9F6E3-83BC-3302-B004-C25399DA0333> /usr/lib/libheimdal-asn1.dylib
    0x7fffcc9e5000 -     0x7fffccad7ff7  libiconv.2.dylib (50) <42125B35-81D7-3FC4-9475-A26DBE10884D> /usr/lib/libiconv.2.dylib
    0x7fffccad8000 -     0x7fffcccfdffb  libicucore.A.dylib (57149.0.1) <6B5FDA93-AA88-318F-9608-C2A33D602EC7> /usr/lib/libicucore.A.dylib
    0x7fffccd03000 -     0x7fffccd04fff  liblangid.dylib (126) <3F4530C9-8BE1-3AA7-9A82-98694D240866> /usr/lib/liblangid.dylib
    0x7fffccd05000 -     0x7fffccd1effb  liblzma.5.dylib (10) <44BD0279-99DD-36B5-8A6E-C11432E2098D> /usr/lib/liblzma.5.dylib
    0x7fffccd1f000 -     0x7fffccd35ff7  libmarisa.dylib (5) <2183D484-032D-3DE5-8984-3A14006E034E> /usr/lib/libmarisa.dylib
    0x7fffccd36000 -     0x7fffccfddff7  libmecabra.dylib (744.5) <EF046855-CB9C-32D8-B2F1-C85B526E386F> /usr/lib/libmecabra.dylib
    0x7fffcd010000 -     0x7fffcd089ff7  libnetwork.dylib (856.30.16) <66C6E4D6-B39C-3309-80C1-CBBE170DDD51> /usr/lib/libnetwork.dylib
    0x7fffcd08a000 -     0x7fffcd45ad97  libobjc.A.dylib (706) <F9AFE665-A3A2-3285-9495-19803A565861> /usr/lib/libobjc.A.dylib
    0x7fffcd45d000 -     0x7fffcd461fff  libpam.2.dylib (21.30.1) <71EB0D88-DE84-3C8D-A2C5-58AA282BC5BC> /usr/lib/libpam.2.dylib
    0x7fffcd462000 -     0x7fffcd492ff7  libpcap.A.dylib (67) <450DB888-2C0C-3085-A5F1-69324DFE902C> /usr/lib/libpcap.A.dylib
    0x7fffcd4b0000 -     0x7fffcd4ccffb  libresolv.9.dylib (64) <A244AE4C-00B0-396C-98FF-97FE4DB3DA30> /usr/lib/libresolv.9.dylib
    0x7fffcd4cd000 -     0x7fffcd506fff  libsandbox.1.dylib (592.31.1) <0B3D5690-EF2C-39A6-B63C-CFB8CBAC0956> /usr/lib/libsandbox.1.dylib
    0x7fffcd51c000 -     0x7fffcd664fe3  libsqlite3.dylib (253) <B5BA5C96-AB13-34A0-8237-DD52A0181DFE> /usr/lib/libsqlite3.dylib
    0x7fffcd759000 -     0x7fffcd766fff  libxar.1.dylib (357) <58BFB84B-66FE-3299-AA3D-BBA178ADEE39> /usr/lib/libxar.1.dylib
    0x7fffcd76a000 -     0x7fffcd859ffb  libxml2.2.dylib (30.11) <E12AF929-0FA5-3214-840F-C81E6AC9F36E> /usr/lib/libxml2.2.dylib
    0x7fffcd85a000 -     0x7fffcd883fff  libxslt.1.dylib (15.8) <FFF5DD45-F544-34B2-BE3C-DB877DC60081> /usr/lib/libxslt.1.dylib
    0x7fffcd884000 -     0x7fffcd895ff3  libz.1.dylib (67) <46E3FFA2-4328-327A-8D34-A03E20BFFB8E> /usr/lib/libz.1.dylib
    0x7fffcd8a4000 -     0x7fffcd8a8ff7  libcache.dylib (79) <0C8092D3-600F-3ADD-A036-F225B6CDCA43> /usr/lib/system/libcache.dylib
    0x7fffcd8a9000 -     0x7fffcd8b4ff7  libcommonCrypto.dylib (60092.30.2) <B16E29B6-EC8D-3A8F-9A89-DD9CF35F7C4B> /usr/lib/system/libcommonCrypto.dylib
    0x7fffcd8b5000 -     0x7fffcd8bcfff  libcompiler_rt.dylib (62) <E992E8D9-037C-3454-A366-A25E4D31D6BB> /usr/lib/system/libcompiler_rt.dylib
    0x7fffcd8bd000 -     0x7fffcd8c5fff  libcopyfile.dylib (138) <64E285D9-5485-333B-AEE7-8B0C8FB9275F> /usr/lib/system/libcopyfile.dylib
    0x7fffcd8c6000 -     0x7fffcd949fdf  libcorecrypto.dylib (442.30.20) <2074B932-FD79-30A9-8E90-AF25C49F2AF1> /usr/lib/system/libcorecrypto.dylib
    0x7fffcd94a000 -     0x7fffcd97cfff  libdispatch.dylib (703.30.5) <EA0CC14E-D559-3802-B4B2-0E8C7579AAC4> /usr/lib/system/libdispatch.dylib
    0x7fffcd97d000 -     0x7fffcd982ff3  libdyld.dylib (421.2) <6F506653-FFF6-3DB8-84F1-109AE3C52F32> /usr/lib/system/libdyld.dylib
    0x7fffcd983000 -     0x7fffcd983ffb  libkeymgr.dylib (28) <1A318923-1200-3B06-B432-5007D82F195D> /usr/lib/system/libkeymgr.dylib
    0x7fffcd984000 -     0x7fffcd990ffb  libkxld.dylib (3789.41.3) <87550136-9353-348B-9CD9-C342B48C5AAF> /usr/lib/system/libkxld.dylib
    0x7fffcd991000 -     0x7fffcd991fff  liblaunch.dylib (972.30.7) <15FACC21-079A-3BDF-9AFB-4253EFDEB587> /usr/lib/system/liblaunch.dylib
    0x7fffcd992000 -     0x7fffcd997fff  libmacho.dylib (894) <A2F38EC1-C37C-3B93-B0E4-36B07C177F8C> /usr/lib/system/libmacho.dylib
    0x7fffcd998000 -     0x7fffcd99aff3  libquarantine.dylib (85) <C1D7749F-5F5F-3BB9-BEFC-1F0B9DA941FD> /usr/lib/system/libquarantine.dylib
    0x7fffcd99b000 -     0x7fffcd99cffb  libremovefile.dylib (45) <CD42974E-BE0B-39FC-9BFC-8A7540A04DC6> /usr/lib/system/libremovefile.dylib
    0x7fffcd99d000 -     0x7fffcd9b5ff7  libsystem_asl.dylib (349.30.2) <EFAC72D7-CB13-3DF7-ADF3-EC6635C6F1EA> /usr/lib/system/libsystem_asl.dylib
    0x7fffcd9b6000 -     0x7fffcd9b6ff7  libsystem_blocks.dylib (67) <B8C3701D-5A91-3D35-999D-2DC8D5393525> /usr/lib/system/libsystem_blocks.dylib
    0x7fffcd9b7000 -     0x7fffcda44fef  libsystem_c.dylib (1158.30.7) <2F881962-03CB-3B9D-A782-D98C1BBA4E3D> /usr/lib/system/libsystem_c.dylib
    0x7fffcda45000 -     0x7fffcda48ffb  libsystem_configuration.dylib (888.30.2) <4FE3983C-E4ED-3939-A578-03AD29C99788> /usr/lib/system/libsystem_configuration.dylib
    0x7fffcda49000 -     0x7fffcda4cfff  libsystem_coreservices.dylib (41.4) <1A572B9E-0C47-320F-8C64-7990D0A5FB5A> /usr/lib/system/libsystem_coreservices.dylib
    0x7fffcda4d000 -     0x7fffcda65ff3  libsystem_coretls.dylib (121.31.1) <4676F06D-274D-31BE-B61C-4D7A4AEF4858> /usr/lib/system/libsystem_coretls.dylib
    0x7fffcda66000 -     0x7fffcda6cfff  libsystem_dnssd.dylib (765.30.11) <DC708D84-ED7D-3936-B996-A67C66B8DDAA> /usr/lib/system/libsystem_dnssd.dylib
    0x7fffcda6d000 -     0x7fffcda96ff7  libsystem_info.dylib (503.30.1) <9ED9121C-F111-3FAD-BC2F-C95DEE1C9362> /usr/lib/system/libsystem_info.dylib
    0x7fffcda97000 -     0x7fffcdab9ff7  libsystem_kernel.dylib (3789.41.3) <B75B128C-7D7A-3318-91CD-82B5A69C5329> /usr/lib/system/libsystem_kernel.dylib
    0x7fffcdaba000 -     0x7fffcdb01fe7  libsystem_m.dylib (3121.4) <266DB92B-A86F-3691-80FB-1B26AD73CFF3> /usr/lib/system/libsystem_m.dylib
    0x7fffcdb02000 -     0x7fffcdb20ff7  libsystem_malloc.dylib (116.30.3) <F40DEE3B-386A-3529-A3F7-98117ED55BF4> /usr/lib/system/libsystem_malloc.dylib
    0x7fffcdb21000 -     0x7fffcdb78ffb  libsystem_network.dylib (856.30.16) <4AE368E9-605D-379D-B04C-2AC7455B8250> /usr/lib/system/libsystem_network.dylib
    0x7fffcdb79000 -     0x7fffcdb82ff3  libsystem_networkextension.dylib (563.30.15) <EB020B0C-7DF0-3EEF-8E3C-15DA3C01D687> /usr/lib/system/libsystem_networkextension.dylib
    0x7fffcdb83000 -     0x7fffcdb8cff3  libsystem_notify.dylib (165.20.1) <E7FD3A7C-DD07-36E2-9FA4-7561F9F114DA> /usr/lib/system/libsystem_notify.dylib
    0x7fffcdb8d000 -     0x7fffcdb95fe7  libsystem_platform.dylib (126.1.2) <3CA06D4E-C00A-36DE-AA65-3A390097D1F6> /usr/lib/system/libsystem_platform.dylib
    0x7fffcdb96000 -     0x7fffcdba0ff7  libsystem_pthread.dylib (218.30.1) <C869ED7C-BE29-3532-8E69-3A8DA1447EDC> /usr/lib/system/libsystem_pthread.dylib
    0x7fffcdba1000 -     0x7fffcdba4ff7  libsystem_sandbox.dylib (592.31.1) <7BBFDF96-293F-3DD9-B3A4-7C168280B441> /usr/lib/system/libsystem_sandbox.dylib
    0x7fffcdba5000 -     0x7fffcdba6fff  libsystem_secinit.dylib (24) <5C1F1E47-0F7D-3E25-8DEB-D9DB1F902281> /usr/lib/system/libsystem_secinit.dylib
    0x7fffcdba7000 -     0x7fffcdbaefff  libsystem_symptoms.dylib (532.30.6) <5D990CF5-B58F-39F7-B375-99B4EC62CFBD> /usr/lib/system/libsystem_symptoms.dylib
    0x7fffcdbaf000 -     0x7fffcdbcfff7  libsystem_trace.dylib (518.30.7) <6D34D1EA-2A3C-3D2D-803E-A666E6AEEE52> /usr/lib/system/libsystem_trace.dylib
    0x7fffcdbd0000 -     0x7fffcdbd5ffb  libunwind.dylib (35.3) <9F7C2AD8-A9A7-3DE4-828D-B0F0F166AAA0> /usr/lib/system/libunwind.dylib
    0x7fffcdbd6000 -     0x7fffcdbffff7  libxpc.dylib (972.30.7) <65E41BB6-EBD5-3D93-B0BE-B190CEE4DD93> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 761409
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=302.6M resident=0K(0%) swapped_out_or_unallocated=302.6M(100%)
Writable regions: Total=549.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=549.4M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        4 
Activity Tracing                   256K        2 
CG backing stores                 28.5M        7 
CG image                           148K       15 
CoreAnimation                      128K        9 
CoreUI image data                 4336K       28 
CoreUI image file                  288K        5 
Foundation                           4K        2 
Kernel Alloc Once                    8K        2 
MALLOC                           484.0M       95 
MALLOC guard page                   48K       10 
Memory Tag 242                      12K        2 
STACK GUARD                       56.1M       17 
Stack                             15.6M       17 
VM_ALLOCATE                        128K       23 
__DATA                            32.5M      252 
__GLSLBUILTINS                    2588K        2 
__IMAGE                            528K        2 
__LINKEDIT                       122.3M       27 
__TEXT                           180.3M      246 
__UNICODE                          556K        2 
mapped file                      258.8M       40 
shared memory                     16.4M       17 
===========                     =======  ======= 
TOTAL                              1.2G      803 

Model: MacBookPro11,3, BootROM MBP112.0138.B21, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.21.171.68.1a5)
Bluetooth: Version 5.0.3f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
```

### PR DESCRIPTION
**Pull request by ZeldaZach**
Crash came from a nullptr in this file, so I added checks where ever pointers were used just in case. Fixed many nullptr issues throughout a few files that led to 3 different types of crashes.

Fix #2489

### CODE REVIEW

File: cockatrice/src/gameselector.cpp [hunk 1]
```diff
@@ -129,6 +130,11 @@ void GameSelector::actClearFilter()
 
 void GameSelector::actCreate()
 {
+    if (room == nullptr) {
+        qDebug() << "Attempted to create game, error caught!";
```
Comment (Daenyth) [inline cockatrice/src/gameselector.cpp]: Terrible message. Also I think it should be qWarn()
