### PR TITLE
fix compiling on arch

### LINKED ISSUE #6761: Linux Arch builds started to fail in CI
See e.g. https://github.com/Cockatrice/Cockatrice/actions/runs/23659485867/job/69303010627 on `master`.

### PR DESCRIPTION
**Pull request by ebbit1q**
## Related Ticket(s)
- Fixes #6761

## Short roundup of the initial problem
new version of protobuf adds no discard to parsing functions

## What will change with this Pull Request?
- use the return values
- log when they fail

please tell me how you'd like me to log these properly

### CODE REVIEW

File: cockatrice/src/interface/widgets/tabs/tab_replays.cpp [hunk 1]
```diff
@@ -265,9 +265,11 @@ void TabReplays::actOpenLocalReplay()
         f.close();
 
         GameReplay *replay = new GameReplay;
-        replay->ParseFromArray(_data.data(), _data.size());
-
-        emit openReplay(replay);
+        if (replay->ParseFromArray(_data.data(), _data.size())) {
+            emit openReplay(replay);
+        } else {
+            qDebug() << "could not parse replay!";
```
Comment (RickyRister) [inline cockatrice/src/interface/widgets/tabs/tab_replays.cpp]: unexpected failures should be logged at warning level.

Also, I'd prefer if we set up the logger properly and used qCDebug
