### PR TITLE
Fix deck loader with spaces

### LINKED ISSUE #2998: Cards from clipboard in deck builder without quantity given have first word replaced by quantity
<b>OS: Win 10 Home 64-bit</b>
<b>Cockatrice version: 2.4.1</b>

Open Cockatrice and try to add a card or list of cards from the clipboard in deck builder (Ctrl + Shift + V) without quantities specified. Like _Notion Thief_ instead of _1x Notion Thief_. They're supposed to become _1x Notion Thief_ but become _1x  Thief_ instead. The first word is eaten by the quantity prepended to the card name. This affects every card I tested; length of the first word in the card name doesn't matter.

### PR DESCRIPTION
**Pull request by ZeldaZach**
Fixes #2998 

Tested with 
```
Quicksilver Elemental
3x Craterhoof Behemoth
2 Elvish Mystic
Progenitus
2x Abrade
1 Absorb
```

Before:
screenshot 2018-01-10 19 59 07

After:
screenshot 2018-01-10 19 58 50

### CODE REVIEW

File: common/decklist.cpp [hunk 1]
```diff
@@ -555,21 +613,37 @@ bool DeckList::loadFromStream_Plain(QTextStream &in)
         rx.setPattern("\\|.*$");
         line.remove(rx);
 
+        // If the user inputs "Quicksilver Elemental" then it will cut it off
```
Comment (ZeldaZach) [inline common/decklist.cpp]: The actual fix is in this file. Cleanup was done on all files touched to meet new coding standards.

File: common/decklist.cpp [hunk 2]
```diff
@@ -555,21 +613,37 @@ bool DeckList::loadFromStream_Plain(QTextStream &in)
...
-            i--;
+        if (i > 0)
+        {
+            // If the count ends with an 'x', ignore it. For example,
+            // "4x Storm Crow" will count 4 correctly.
+            if (line.at(i-1) == 'x')
+            {
+                i--;
+            }
+            else if (! line.at(i-1).isDigit())
```
Comment (ctrlaltca) [inline common/decklist.cpp]: For other readers: here's the main change of this PR

File: common/decklist.h [hunk 3]
```diff
@@ -12,6 +12,7 @@
 // Required on Mac. Forward declaration doesn't work. Don't ask why.
 #include <QtCore/QXmlStreamReader>
 #include <QtCore/QXmlStreamWriter>
+#include <utility>
```
Comment (ctrlaltca) [inline common/decklist.h]: I failed to see where this is needed
