### PR TITLE
Fix WWW link error

### LINKED ISSUE #1135: AutoLink Error
When people type messages that contain three (3) www's in a row, the system thinks they're trying to link to something and makes the incorrect conversion.

A simple fix should just be instead of searching for "www" it should search for "www." but maybe there's something more intuitive to prevent false linking.

screen shot 2015-06-11 at 11 49 17 pm
screen shot 2015-06-11 at 11 49 27 pm

### PR DESCRIPTION
**Pull request by ZeldaZach**
This will fix the linking issue of somebody typing something like "wowwwwww" in chat.

**WILL LINK:**
`http://example.com`
`https://example.com`
`www.example.com`

**WILL NOT LINK:**
`wowwwwww`
`wowwwwww.`
`wowwww...... That's not fair`
`wowwww....U stink`
`this is so sillyyyyyywowwwww.example.com`
`wwwwwwwwow`
`wwwwwwwwow.`
`wwwwwowwwow..... That's not fair`
`wwwwwow.U stink`

This will also pull out the Regex's from the file to improve efficiency.

Fix #1135

### CODE REVIEW

File: cockatrice/src/chatview.cpp [hunk 1]
```diff
@@ -168,7 +168,7 @@ void ChatView::appendMessage(QString message, QString sender, UserLevelFlags use
         // search for the first [ or @
         bracketFirstIndex = message.indexOf('[');
         mentionFirstIndex = mentionEnabled ? message.indexOf('@') : -1;
-        urlFirstIndex = message.indexOf(QRegExp("https?://|www."));
+        urlFirstIndex = message.indexOf(QRegExp("https?://|www\\.\\w"));
```
Comment (Daenyth) [inline cockatrice/src/chatview.cpp]: What about `|\\<www\\.\\w`? I believe that `woowww.x` would match yours

Comment (ZeldaZach) [inline cockatrice/src/chatview.cpp]: You are correct that

**Comment by Nightfirecat** [comment]
How about examples where the strings start with `www`?

* `wwwwwwwwow`
* `wwwwwwwwow.`
* `wowwwow..... That's not fair`
* `wwwwwow.U stink`

**Comment by ZeldaZach** [comment]
@Nightfirecat There has to be a match of `www.` otherwise it doesn't matter. With the old way (how it is now in the master repo), it would auto link on any `www` no matter what.

**Comment by Nightfirecat** [comment]
Got it.

**Comment by ZeldaZach** [comment]
Were you able to test this @Nightfirecat ?

**Comment by poixen** [comment]
When I originally coded this I added an IsValid() call. I assumed it would check if the link can be used. It seems it only checks url syntax though.

**Comment by Daenyth** [comment]
The docs seem to suggest that it just checks for non-empty and correctly url-encoded

**Comment by Daenyth** [comment]
:shipit:
