### PR TITLE
Fix crash on logger; make log window modalless

### LINKED ISSUE #2297: Crash on Observation
<b>OS:</b>
10.12.1 (Sierra)

<b>Cockatrice version:</b>
c90c4ea4

___
Seems like I crashed while observing a game. The only information I can provide is: A user played Dwynen's Elite and I presume he attempted to make a token, which crashed me.

Edit: The crash happened again in the same room. Game log can be found [here (Game#22111)](https://dl.dropboxusercontent.com/u/86044339/replay_48632.cor)

Crash log: http://pastebin.com/hdSZ6a9b

### LINKED ISSUE #2581: Crashed on Spectator Mode
<details><summary>Stack trace</summary>

```
Process:               cockatrice [36884]
Path:                  /Applications/cockatrice.app/Contents/MacOS/cockatrice
Identifier:            com.cockatrice.Cockatrice
Version:               0.0.1~git20170331.ef7670a (0.0.1~git20170331.ef7670a)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           cockatrice [36884]
User ID:               501

Date/Time:             2017-04-09 01:03:51.466 -0400
OS Version:            Mac OS X 10.12.4 (16E195)
Report Version:        12
Anonymous UUID:        E150293E-C093-D738-4100-6D0B5D37A6C4

Sleep/Wake UUID:       E16C3046-4480-4B44-A469-30FC0C845F96

Time Awake Since Boot: 300000 seconds
Time Since Wake:       15000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
BUG IN CLIENT OF LIBPLATFORM: Unlock of an os_unfair_lock not owned by current thread

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	0x00007fffbb1fcb97 _os_unfair_lock_unowned_abort + 23
1   libsystem_platform.dylib      	0x00007fffbb1fc4d9 _os_unfair_lock_unlock_slow + 95
2   libsystem_malloc.dylib        	0x00007fffbb18416e free_tiny_botch + 69
3   libsystem_malloc.dylib        	0x00007fffbb16fcf6 szone_realloc + 2941
4   libsystem_malloc.dylib        	0x00007fffbb16f121 malloc_zone_realloc + 115
5   libsystem_malloc.dylib        	0x00007fffbb16f010 realloc + 256
6   org.qt-project.QtCore         	0x00000001028e0e37 QListData::append() + 135
7   com.cockatrice.Cockatrice     	0x000000010101402f QList<QString>::append(QString const&) + 79
8   com.cockatrice.Cockatrice     	0x00000001011bb794 Logger::log(QtMsgType, QMessageLogContext const&, QString const&) + 36
9   org.qt-project.QtCore         	0x000000010287d5bd qt_message_output(QtMsgType, QMessageLogContext const&, QString const&) + 13
10  org.qt-project.QtCore         	0x0000000102972bd0 QDebug::~QDebug() + 96
11  com.cockatrice.Cockatrice     	0x0000000101102ac8 TabGame::processGameEventContainer(GameEventContainer const&, AbstractClient*) + 1224
12  org.qt-project.QtCore         	0x0000000102a7738c QObject::event(QEvent*) + 156
13  org.qt-project.QtWidgets      	0x0000000101df8abe QWidget::event(QEvent*) + 4254
14  org.qt-project.QtWidgets      	0x0000000101db758d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
15  org.qt-project.QtWidgets      	0x0000000101db9ed2 QApplication::notify(QObject*, QEvent*) + 5906
16  org.qt-project.QtCore         	0x0000000102a4d544 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
17  org.qt-project.QtCore         	0x0000000102a4e1c8 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 600
18  libqcocoa.dylib               	0x0000000102ee9f5e 0x102ec3000 + 159582
19  libqcocoa.dylib               	0x0000000102eea821 0x102ec3000 + 161825
20  com.apple.CoreFoundation      	0x00007fffa58a73c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
21  com.apple.CoreFoundation      	0x00007fffa58882cd __CFRunLoopDoSources0 + 557
22  com.apple.CoreFoundation      	0x00007fffa58877c6 __CFRunLoopRun + 934
23  com.apple.CoreFoundation      	0x00007fffa58871c4 CFRunLoopRunSpecific + 420
24  com.apple.HIToolbox           	0x00007fffa4de8ebc RunCurrentEventLoopInMode + 240
25  com.apple.HIToolbox           	0x00007fffa4de8cf1 ReceiveNextEventCommon + 432
26  com.apple.HIToolbox           	0x00007fffa4de8b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
27  com.apple.AppKit              	0x00007fffa3383e24 _DPSNextEvent + 1120
28  com.apple.AppKit              	0x00007fffa3aff85e -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
29  com.apple.AppKit              	0x00007fffa33787ab -[NSApplication run] + 926
30  libqcocoa.dylib               	0x0000000102ee96bf 0x102ec3000 + 157375
31  org.qt-project.QtCore         	0x0000000102a49781 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
32  org.qt-project.QtCore         	0x0000000102a4dbb5 QCoreApplication::exec() + 341
33  com.cockatrice.Cockatrice     	0x0000000101047b6a main + 1626
34  libdyld.dylib                 	0x00007fffbafea235 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fffbb11944e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffbb203695 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffbb2030f1 start_wqthread + 13

Thread 2:: Qt bearer thread
0   libsystem_kernel.dylib        	0x00007fffbb11a19e poll + 10
1   org.qt-project.QtCore         	0x0000000102a9fa90 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 544
2   org.qt-project.QtCore         	0x0000000102aa0f75 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 885
3   org.qt-project.QtCore         	0x0000000102a49781 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
4   org.qt-project.QtCore         	0x0000000102887eee QThread::exec() + 110
5   org.qt-project.QtCore         	0x000000010288b85a 0x102861000 + 174170
6   libsystem_pthread.dylib       	0x00007fffbb2039af _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffbb2038fb _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffbb203101 thread_start + 13

Thread 3:: QThread
0   libsystem_kernel.dylib        	0x00007fffbb11a19e poll + 10
1   org.qt-project.QtCore         	0x0000000102a9f8e0 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 112
2   org.qt-project.QtCore         	0x0000000102aa0f75 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 885
3   org.qt-project.QtCore         	0x0000000102a49781 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
4   org.qt-project.QtCore         	0x0000000102887eee QThread::exec() + 110
5   org.qt-project.QtCore         	0x000000010288b85a 0x102861000 + 174170
6   libsystem_pthread.dylib       	0x00007fffbb2039af _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffbb2038fb _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffbb203101 thread_start + 13

Thread 4:: QFileInfoGatherer
0   libsystem_kernel.dylib        	0x00007fffbb118bf2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffbb20486e _pthread_cond_wait + 712
2   org.qt-project.QtCore         	0x000000010288ce9b 0x102861000 + 179867
3   org.qt-project.QtCore         	0x000000010288cd42 QWaitCondition::wait(QMutex*, unsigned long) + 162
4   org.qt-project.QtWidgets      	0x0000000101ff86b2 0x101da6000 + 2434738
5   org.qt-project.QtCore         	0x000000010288b85a 0x102861000 + 174170
6   libsystem_pthread.dylib       	0x00007fffbb2039af _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffbb2038fb _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffbb203101 thread_start + 13

Thread 5:: QFileInfoGatherer
0   libsystem_kernel.dylib        	0x00007fffbb118bf2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffbb20486e _pthread_cond_wait + 712
2   org.qt-project.QtCore         	0x000000010288ce9b 0x102861000 + 179867
3   org.qt-project.QtCore         	0x000000010288cd42 QWaitCondition::wait(QMutex*, unsigned long) + 162
4   org.qt-project.QtWidgets      	0x0000000101ff86b2 0x101da6000 + 2434738
5   org.qt-project.QtCore         	0x000000010288b85a 0x102861000 + 174170
6   libsystem_pthread.dylib       	0x00007fffbb2039af _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffbb2038fb _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffbb203101 thread_start + 13

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fffbb11134a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fffbb110797 mach_msg + 55
2   com.apple.CoreFoundation      	0x00007fffa58884e4 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation      	0x00007fffa5887971 __CFRunLoopRun + 1361
4   com.apple.CoreFoundation      	0x00007fffa58871c4 CFRunLoopRunSpecific + 420
5   com.apple.AppKit              	0x00007fffa34d12d2 _NSEventThread + 205
6   libsystem_pthread.dylib       	0x00007fffbb2039af _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffbb2038fb _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffbb203101 thread_start + 13

Thread 7:: QThread
0   libsystem_kernel.dylib        	0x00007fffbb11a19e poll + 10
1   org.qt-project.QtCore         	0x0000000102a9fa90 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 544
2   org.qt-project.QtCore         	0x0000000102aa0f75 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 885
3   org.qt-project.QtCore         	0x0000000102a49781 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
4   org.qt-project.QtCore         	0x0000000102887eee QThread::exec() + 110
5   org.qt-project.QtCore         	0x000000010288b85a 0x102861000 + 174170
6   libsystem_pthread.dylib       	0x00007fffbb2039af _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffbb2038fb _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffbb203101 thread_start + 13

Thread 8:: QNetworkAccessManager thread
0   libsystem_kernel.dylib        	0x00007fffbb11a19e poll + 10
1   org.qt-project.QtCore         	0x0000000102a9f8e0 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 112
2   org.qt-project.QtCore         	0x0000000102aa0f75 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 885
3   org.qt-project.QtCore         	0x0000000102a49781 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
4   org.qt-project.QtCore         	0x0000000102887eee QThread::exec() + 110
5   org.qt-project.QtCore         	0x000000010288b85a 0x102861000 + 174170
6   libsystem_pthread.dylib       	0x00007fffbb2039af _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffbb2038fb _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffbb203101 thread_start + 13

Thread 9:
0   libsystem_kernel.dylib        	0x00007fffbb11944e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffbb203695 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffbb2030f1 start_wqthread + 13

Thread 10:
0   libsystem_kernel.dylib        	0x00007fffbb11944e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffbb203695 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffbb2030f1 start_wqthread + 13

Thread 11:
0   libsystem_kernel.dylib        	0x00007fffbb11944e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffbb203695 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffbb2030f1 start_wqthread + 13

Thread 12:
0   libsystem_kernel.dylib        	0x00007fffbb11944e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffbb203502 _pthread_wqthread + 1023
2   libsystem_pthread.dylib       	0x00007fffbb2030f1 start_wqthread + 13

Thread 13:
0   libsystem_kernel.dylib        	0x00007fffbb11944e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffbb203695 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffbb2030f1 start_wqthread + 13

Thread 14:
0   libsystem_kernel.dylib        	0x00007fffbb11944e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffbb203695 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffbb2030f1 start_wqthread + 13

Thread 15:
0   libsystem_kernel.dylib        	0x00007fffbb11944e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffbb203695 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffbb2030f1 start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000001  rbx: 0x0000000102dd2600  rcx: 0x00007fffbb1fec0b  rdx: 0x0000000000000307
  rdi: 0x0000000000000001  rsi: 0x0000000000000000  rbp: 0x00007fff5ebfe550  rsp: 0x00007fff5ebfe538
   r8: 0x9e3779b97f4a7c55   r9: 0x0000000000000004  r10: 0x00007fde4ed00000  r11: 0x0000000000003c00
  r12: 0x0000000000000200  r13: 0x00000001019a5000  r14: 0x00007fde4edbc220  r15: 0x00007fde4abc9400
  rip: 0x00007fffbb1fcb97  rfl: 0x0000000000010213  cr2: 0x000070000bfd5f28
  
Logical CPU:     6
Error Code:      0x00000000
Trap Number:     6


Binary Images:
       0x100fff000 -        0x1016d2ff7 +com.cockatrice.Cockatrice (0.0.1~git20170331.ef7670a - 0.0.1~git20170331.ef7670a) <D4B96AE5-D56F-362A-8EA0-07954EE962A5> /Applications/cockatrice.app/Contents/MacOS/cockatrice
       0x1018e0000 -        0x101956ff7 +org.qt-project.QtMultimedia (5.8 - 5.8.0) <00AD8F99-B5A0-37BE-BC0D-5BF32B6A239F> /Applications/cockatrice.app/Contents/Frameworks/QtMultimedia.framework/Versions/5/QtMultimedia
       0x1019ac000 -        0x1019d7ff7 +org.qt-project.QtPrintSupport (5.8 - 5.8.0) <07F167B6-A2C3-32AF-879B-683F0E99C7E9> /Applications/cockatrice.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x1019fc000 -        0x101a30fff +org.qt-project.QtSvg (5.8 - 5.8.0) <720751B1-F4B9-3D09-BFD7-ED77B8B368D1> /Applications/cockatrice.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
       0x101a4f000 -        0x101b65fff +libprotobuf.12.dylib (0) <E5180A08-027E-332C-ADEB-A0CEC9A75E85> /Applications/cockatrice.app/Contents/MacOS/libprotobuf.12.dylib
       0x101c5f000 -        0x101d5cfff +org.qt-project.QtNetwork (5.8 - 5.8.0) <1A97FCA2-861D-3010-AA7F-51B1D5D97616> /Applications/cockatrice.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x101da6000 -        0x10220afff +org.qt-project.QtWidgets (5.8 - 5.8.0) <61BFF62F-BFCA-3F3C-8637-E3A3ABC1FA3C> /Applications/cockatrice.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x102368000 -        0x102769fef +org.qt-project.QtGui (5.8 - 5.8.0) <FD81651A-12A4-3CA5-B666-280959476E5F> /Applications/cockatrice.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x102861000 -        0x102d1efff +org.qt-project.QtCore (5.8 - 5.8.0) <9F6D2D06-C079-347D-B61D-90DB13264562> /Applications/cockatrice.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x102ec3000 -        0x103010fff +libqcocoa.dylib (0) <C6D0934B-4633-3324-97A0-F91C9E085649> /Applications/cockatrice.app/Contents/Plugins/platforms/libqcocoa.dylib
       0x103055000 -        0x10306cffb  libCGInterfaces.dylib (331.5) <E0CA9D83-7F26-3D65-9249-F9231C1CB7DB> /System/Library/Frameworks/Accelerate.framework/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
       0x10349e000 -        0x1034a4ff7 +libqgif.dylib (0) <E7C2B3B7-F09E-3F1D-B341-8B4E76890685> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqgif.dylib
       0x1034ef000 -        0x1034f6fff +libqicns.dylib (0) <778F71AB-C3F7-36EF-9980-9B11766D4590> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqicns.dylib
       0x1034fb000 -        0x1034fffff +libqmacjp2.dylib (0) <18752167-137B-3B05-B02C-B9E58E85B923> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqmacjp2.dylib
       0x10350f000 -        0x103539fff  GLRendererFloat (14.0.16) <768ADC3B-C0E6-3936-801C-35990D62CAE7> /System/Library/Frameworks/OpenGL.framework/Resources/GLRendererFloat.bundle/GLRendererFloat
       0x103610000 -        0x10364ddc7  dyld (433.5) <8239D0D7-66F6-3C44-A77F-586F74525DA3> /usr/lib/dyld
       0x10580c000 -        0x105811fff +libqico.dylib (0) <9AF006F5-94C6-3578-96A8-97E367C32310> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqico.dylib
       0x105816000 -        0x10581afff +libqsvg.dylib (0) <A6096004-A974-3F32-A688-93B035F34593> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqsvg.dylib
       0x105853000 -        0x105857ff7 +libqtga.dylib (0) <8846CD63-3EF0-34B8-B6A6-A9DB73BF195B> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqtga.dylib
       0x107daf000 -        0x107f55fff  GLEngine (14.0.16) <E67A2652-EEBB-38BF-9FF2-6C64ED0ABA9B> /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
       0x107f94000 -        0x1084efff7  com.apple.driver.AppleIntelHD5000GraphicsGLDriver (10.24.45 - 10.2.4) <841A5F5A-0B40-3746-87EA-81F148645B9D> /System/Library/Extensions/AppleIntelHD5000GraphicsGLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsGLDriver
       0x108702000 -        0x10877afff  com.apple.driver.AppleIntelHD5000GraphicsMTLDriver (10.24.45 - 10.2.4) <D8034390-8A45-3A88-86D7-631B7076FD03> /System/Library/Extensions/AppleIntelHD5000GraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsMTLDriver
       0x108aa8000 -        0x108ae2fff +libqjpeg.dylib (0) <A5468A1F-9028-3F14-8476-BD68F990457F> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqjpeg.dylib
       0x108ae8000 -        0x108b3bfff +libqtiff.dylib (0) <855F2E0C-5395-3B8C-A03D-4062C29BF3C7> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqtiff.dylib
       0x108b43000 -        0x108b47fff +libqwbmp.dylib (0) <33596709-6CDE-3719-AF4F-54BF43B79883> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqwbmp.dylib
       0x108b4b000 -        0x108bc0ff7 +libqwebp.dylib (0) <6639FFA9-A7A2-3CAE-8017-8D4FB3BB27C9> /Applications/cockatrice.app/Contents/Plugins/imageformats/libqwebp.dylib
       0x114897000 -        0x11489bfff  libFontRegistryUI.dylib (196.4) <4EEE5715-A024-3A4B-BF0E-D55325B8E129> /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Resources/libFontRegistryUI.dylib
       0x1148c9000 -        0x1148e3ff7  com.apple.security.csparser (3.0 - 57740.51.3) <8470F4B5-CACA-3FDC-9686-3BA237A61F2C> /System/Library/Frameworks/Security.framework/PlugIns/csparser.bundle/Contents/MacOS/csparser
    0x7fffa04b4000 -     0x7fffa07f9fff  com.apple.RawCamera.bundle (7.02 - 899) <EB92C4A8-6A1D-349A-8107-59B265512B2A> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera
    0x7fffa0e06000 -     0x7fffa1653fff  com.apple.GeForceGLDriver (10.16.34 - 10.1.6) <E2F65916-324C-3FF3-933E-25670A3CF8B1> /System/Library/Extensions/GeForceGLDriver.bundle/Contents/MacOS/GeForceGLDriver
    0x7fffa1654000 -     0x7fffa1f19ff3  libclh.dylib (4.0.3 - 4.0.3) <724139ED-ED81-39BE-A226-B080DD404719> /System/Library/Extensions/GeForceGLDriver.bundle/Contents/MacOS/libclh.dylib
    0x7fffa1f1a000 -     0x7fffa202aff7  com.apple.GeForceMTLDriver (10.16.34 - 10.1.6) <6BABB0D8-05C7-3AF3-BB54-D86BD65C25A9> /System/Library/Extensions/GeForceMTLDriver.bundle/Contents/MacOS/GeForceMTLDriver
    0x7fffa202b000 -     0x7fffa202fffb  com.apple.agl (3.3.1 - AGL-3.3.1) <EEB77D74-9B6B-331F-B103-5A62A029BCE2> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fffa2030000 -     0x7fffa21f1fff  com.apple.avfoundation (2.0 - 1187.36) <474E9FF4-4A97-3D48-8D4F-46FD3CADBBD6> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fffa21f2000 -     0x7fffa2294ff7  com.apple.audio.AVFAudio (1.0 - ???) <7997D588-B542-3EBB-B822-D719C1114BB4> /System/Library/Frameworks/AVFoundation.framework/Versions/A/Frameworks/AVFAudio.framework/Versions/A/AVFAudio
    0x7fffa235f000 -     0x7fffa235ffff  com.apple.Accelerate (1.11 - Accelerate 1.11) <E559CE70-1A9A-3C5C-9FB7-C51FDF82F03C> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fffa2378000 -     0x7fffa2891feb  com.apple.vImage (8.1 - ???) <3992178B-0FF2-3B05-8830-6894BE8FD6D6> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fffa2892000 -     0x7fffa2a03ff3  libBLAS.dylib (1185.50.4) <4087FFE0-627E-3623-96B4-F0A9A1991E09> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fffa2a04000 -     0x7fffa2a18ffb  libBNNS.dylib (15) <254698C7-7D36-3FFF-864E-ADEEEE543076> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fffa2a19000 -     0x7fffa2e0ffef  libLAPACK.dylib (1185.50.4) <C35FFB2F-A0E6-3903-8A3C-113A74BCBCA2> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fffa2e10000 -     0x7fffa2e26fff  libLinearAlgebra.dylib (1185.50.4) <345CAACF-7263-36EF-B69B-793EA8B390AF> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fffa2e27000 -     0x7fffa2e2dfff  libQuadrature.dylib (3) <EF56C8E6-DE22-3C69-B543-A8648F335FDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fffa2e2e000 -     0x7fffa2e42ff7  libSparseBLAS.dylib (1185.50.4) <67BA432E-FB59-3C78-A8BE-ED4274CBC359> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fffa2e43000 -     0x7fffa2fcafe7  libvDSP.dylib (600) <02EC87E3-EA41-36DF-8696-B84E7551168E> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fffa2fcb000 -     0x7fffa307dffb  libvMisc.dylib (600) <1093AAB8-090A-3A6C-9E52-583B081079D2> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fffa307e000 -     0x7fffa307efff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <2F018865-ACDE-3115-8014-5D8A6A33EDA4> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fffa307f000 -     0x7fffa30bcffb  com.apple.Accounts (113 - 113) <7350A7B1-75AF-379A-8AC5-9F2526B89D00> /System/Library/Frameworks/Accounts.framework/Versions/A/Accounts
    0x7fffa30bd000 -     0x7fffa333cff7  com.apple.AddressBook.framework (10.0 - 1756.20) <EF74B8FF-3AFE-3336-82B0-02792B17406C> /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
    0x7fffa333d000 -     0x7fffa4116ffb  com.apple.AppKit (6.9 - 1504.82.104) <C295FF09-9984-34C3-953B-B263EF2107AB> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fffa4128000 -     0x7fffa4128fff  com.apple.ApplicationServices (48 - 48) <847E54B5-DEA4-3B50-93CE-4FC67789F179> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fffa4129000 -     0x7fffa4197ff7  com.apple.ApplicationServices.ATS (377 - 422.2) <012ACEE0-9A90-3998-8495-734E105117C0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fffa4231000 -     0x7fffa4360ff7  libFontParser.dylib (194.11) <635DF6EF-18DF-3D06-90AA-88C509B43068> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
    0x7fffa4361000 -     0x7fffa43abfff  libFontRegistry.dylib (196.4) <EA96AE47-3369-3DEA-BB82-98348ADBD85B> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fffa4408000 -     0x7fffa443bfff  libTrueTypeScaler.dylib (194.11) <D951545E-3D83-3A3E-A3FE-22A23D485ACD> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
    0x7fffa44a7000 -     0x7fffa4551ff7  com.apple.ColorSync (4.12.0 - 502.2) <ACA4001E-A0E3-33F6-9CD6-EEC2AA15E322> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fffa4552000 -     0x7fffa45a2ff7  com.apple.HIServices (1.22 - 591) <D16A5699-F3A2-3AF5-93B1-9E2F487F1577> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fffa45a3000 -     0x7fffa45b2ff3  com.apple.LangAnalysis (1.7.0 - 1.7.0) <2CBE7F61-2056-3F96-99A1-0D527796AFA6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fffa45b3000 -     0x7fffa4600fff  com.apple.print.framework.PrintCore (12 - 491) <5027FD58-F0EE-33E4-8577-934CA06CD2AF> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fffa4601000 -     0x7fffa463cfff  com.apple.QD (3.12 - 313) <B339C41D-8CDF-3342-8414-F9717DCCADD4> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fffa463d000 -     0x7fffa4648ff7  com.apple.speech.synthesis.framework (6.3.3 - 6.3.3) <5808F070-8199-36C9-B3C9-F9B98D5AA359> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fffa4649000 -     0x7fffa4855fff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <6EEF498D-8233-3622-B34B-49FDD9D4DF14> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fffa4856000 -     0x7fffa4856fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <3D374973-8632-3F15-982C-E0508E6E5B1A> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fffa49bf000 -     0x7fffa4d99ff7  com.apple.CFNetwork (811.4.18 - 811.4.18) <9CE329E8-6177-3474-976D-F5C63FC875CD> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fffa4db3000 -     0x7fffa4db3fff  com.apple.Carbon (154 - 157) <7F6DA3B9-CAE8-3F75-B06A-CC710244970F> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fffa4db4000 -     0x7fffa4db7fff  com.apple.CommonPanels (1.2.6 - 98) <BF04BB22-D54C-309E-9F5C-897D969CAF70> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fffa4db8000 -     0x7fffa50c1fff  com.apple.HIToolbox (2.1.1 - 857.8) <40254D9A-E477-3F33-B2A2-807D399BF71C> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fffa50c2000 -     0x7fffa50c5ff7  com.apple.help (1.3.5 - 49) <B1A930E3-5907-3677-BACD-858EF68B172D> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fffa50c6000 -     0x7fffa50cbfff  com.apple.ImageCapture (9.0 - 9.0) <341252B4-E082-361A-B756-6A330259C741> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fffa50cc000 -     0x7fffa5163ff3  com.apple.ink.framework (10.9 - 219) <1BD40B45-FD33-3177-A935-565EE5FC79D7> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fffa5164000 -     0x7fffa517efff  com.apple.openscripting (1.7 - 172) <31CFBB35-24BD-3E12-9B6B-1FA842FB605B> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fffa517f000 -     0x7fffa5180ff3  com.apple.print.framework.Print (12 - 267) <E2F82F1F-DC27-3EF0-9F75-B354F701450A> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fffa5181000 -     0x7fffa5183ff7  com.apple.securityhi (9.0 - 55006) <BC45C266-A612-33E9-A729-99987C28801D> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fffa5184000 -     0x7fffa518aff7  com.apple.speech.recognition.framework (6.0.1 - 6.0.1) <082895DC-3AC7-3DEF-ADCA-5B018C19C9D3> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fffa518b000 -     0x7fffa526affb  com.apple.cloudkit.CloudKit (651.14 - 651.14) <99B370B1-8D3A-3DEB-8E89-5911DDBF4670> /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit
    0x7fffa526b000 -     0x7fffa526bfff  com.apple.Cocoa (6.11 - 22) <85EDFBE1-75F0-369E-8CA8-C6A639B98FA6> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fffa53b5000 -     0x7fffa5442fff  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <184D9C49-248F-3374-944C-FD1A99A6B32E> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fffa5443000 -     0x7fffa5456fff  com.apple.CoreBluetooth (1.0 - 1) <BCB78777-76F0-3CC1-8443-9E61AEF7EF63> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fffa5457000 -     0x7fffa5752fff  com.apple.CoreData (120 - 754.2) <2397A0D1-03FC-349C-865D-9F114DC86A63> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fffa5753000 -     0x7fffa57fffff  com.apple.CoreDisplay (1.0 - 1) <461540AF-14C1-38F4-8F85-FD96BD51C856> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fffa5800000 -     0x7fffa5c99ff7  com.apple.CoreFoundation (6.9 - 1349.65) <F79384D1-FA3F-38CA-A847-B2625EBB790E> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fffa5c9a000 -     0x7fffa631cfff  com.apple.CoreGraphics (2.0 - 1070.22) <3C0EEAC8-2475-38BD-81DC-C1F7F6C8E82F> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fffa631d000 -     0x7fffa6560ffb  com.apple.CoreImage (12.4.0 - 451.4.9) <988872A1-9C33-3FD7-9BF9-881F13A30392> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fffa6561000 -     0x7fffa65c6ff7  com.apple.corelocation (2101.0.62) <A2C2DF22-8E30-371D-BC9B-9DCA2A70175B> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fffa65c7000 -     0x7fffa6678fff  com.apple.CoreMedia (1.0 - 1907.58) <9A25B3CA-A006-39D2-A405-194F2BBF9061> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fffa6679000 -     0x7fffa66c4ff7  com.apple.CoreMediaIO (805.0 - 4932) <E011AFEF-0B47-3A58-AC53-DE7E44A7B4BF> /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/CoreMediaIO
    0x7fffa66c5000 -     0x7fffa66c5fff  com.apple.CoreServices (775.19 - 775.19) <8AA95E32-AB13-3792-B248-FA150D8E6583> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fffa66c6000 -     0x7fffa6717fff  com.apple.AE (712.5 - 712.5) <F0B36ABC-C0D4-370E-8257-11A7F351EC7F> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fffa6718000 -     0x7fffa69f3ff7  com.apple.CoreServices.CarbonCore (1159.6 - 1159.6) <08AC074C-965B-3EDF-8E45-0707C8DE9EAD> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fffa69f4000 -     0x7fffa6a27fff  com.apple.DictionaryServices (1.2 - 274) <D23866E2-F7C8-3984-A9D4-96552CCDE573> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fffa6a28000 -     0x7fffa6a30ff3  com.apple.CoreServices.FSEvents (1230.50.1 - 1230.50.1) <2AD1B0E5-7214-37C4-8D11-A27C9CAC0F74> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fffa6a31000 -     0x7fffa6b9dff7  com.apple.LaunchServices (775.19 - 775.19) <1CF81B5F-BA1A-3FC6-B4F9-E0A319AE94D0> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fffa6b9e000 -     0x7fffa6c4effb  com.apple.Metadata (10.7.0 - 1075.40) <F205A001-250D-3D9A-8375-0F7A834C46E6> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fffa6c4f000 -     0x7fffa6caefff  com.apple.CoreServices.OSServices (775.19 - 775.19) <724312AC-5CE8-333C-BC35-BC5AB1583D9A> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fffa6caf000 -     0x7fffa6d1ffff  com.apple.SearchKit (1.4.0 - 1.4.0) <7A6DDA2B-03F1-3137-BA9E-1CC211973E26> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fffa6d20000 -     0x7fffa6d65ff7  com.apple.coreservices.SharedFileList (38 - 38) <DA096678-93AB-3291-BDE2-482F1D544589> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fffa6dee000 -     0x7fffa6f3aff3  com.apple.CoreText (352.0 - 544.12) <1ED17C4A-9E2D-3537-8C5F-FB675492A002> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fffa6f3b000 -     0x7fffa6f70ff3  com.apple.CoreVideo (1.8 - 235.3) <AC11D5FB-C77B-34F5-B942-F698E84C229F> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fffa6f71000 -     0x7fffa6fe2ffb  com.apple.framework.CoreWLAN (11.0 - 1200.31) <3A83EBE9-68C5-37DD-AD6F-AF4B37813480> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fffa7015000 -     0x7fffa7020ff3  com.apple.DirectoryService.Framework (10.12 - 194) <85778AAA-B306-3617-B245-CBC9BB07BC86> /System/Library/Frameworks/DirectoryService.framework/Versions/A/DirectoryService
    0x7fffa7021000 -     0x7fffa70dfff7  com.apple.DiscRecording (9.0.3 - 9030.4.5) <88544E99-217A-33D9-8AC7-F54D2716658D> /System/Library/Frameworks/DiscRecording.framework/Versions/A/DiscRecording
    0x7fffa70e0000 -     0x7fffa70e5fff  com.apple.DiskArbitration (2.7 - 2.7) <A4DCD470-D8EA-37E9-BDCA-A2B469754C12> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fffa7277000 -     0x7fffa761dff3  com.apple.Foundation (6.9 - 1349.64) <49C8DA40-9E5B-33F9-B092-F50115B59E95> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fffa7649000 -     0x7fffa767aff7  com.apple.GSS (4.0 - 2.0) <6FADED0B-0425-3567-A75A-040C5A4638EB> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fffa773a000 -     0x7fffa77ddffb  com.apple.Bluetooth (5.0.4 - 5.0.4f18) <00D257AA-283D-3395-B9B0-FEB70764080B> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fffa77de000 -     0x7fffa7873fff  com.apple.framework.IOKit (2.0.2 - 1324.50.21) <BA7DC917-35A9-3D1B-BBEC-ADF4495A166D> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fffa7874000 -     0x7fffa787affb  com.apple.IOSurface (159.6 - 159.6) <661BFCC0-85AB-3343-853E-3797932871D4> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fffa787b000 -     0x7fffa78ccfff  com.apple.ImageCaptureCore (7.0 - 7.0) <22A35555-6025-3EB8-993B-B91141668C6A> /System/Library/Frameworks/ImageCaptureCore.framework/Versions/A/ImageCaptureCore
    0x7fffa78cd000 -     0x7fffa7a2cfe7  com.apple.ImageIO.framework (3.3.0 - 1599.7) <2BDE099C-94BA-390E-9CB5-6BE969532EB6> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fffa7a2d000 -     0x7fffa7a31fff  libGIF.dylib (1599.7) <B0D5A8F5-9DF3-33D7-B860-05C1CBF3C11E> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fffa7a32000 -     0x7fffa7b22ff7  libJP2.dylib (1599.7) <8AF4DA0A-7D10-3082-9523-FEA4F51E1568> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fffa7b23000 -     0x7fffa7b46ffb  libJPEG.dylib (1599.7) <D6530D83-840B-360D-B444-C06FFF64DEEA> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fffa7b47000 -     0x7fffa7b6eff7  libPng.dylib (1599.7) <EB2FC33D-A7CC-37C1-8A22-7D8069EB3FE8> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fffa7b6f000 -     0x7fffa7b71ff3  libRadiance.dylib (1599.7) <FA599313-8434-3F68-B33B-A49B7B46B783> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fffa7b72000 -     0x7fffa7bc0feb  libTIFF.dylib (1599.7) <1C2B6B4D-D77C-3F48-8D04-E5F4F2EAAECA> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fffa7d1e000 -     0x7fffa8926ff3  com.apple.JavaScriptCore (12603 - 12603.1.30.0.34) <42993DA4-E18A-3A41-86F8-23A6656273F9> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fffa8927000 -     0x7fffa8940ff7  com.apple.Kerberos (3.0 - 1) <B9D242EB-E325-3A21-9812-C77CBBFB0D51> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fffa8941000 -     0x7fffa8977fff  com.apple.LDAPFramework (2.4.28 - 194.5) <492ACA22-373E-3DD9-BAEB-9EF6AA962FD5> /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
    0x7fffa8bc9000 -     0x7fffa8bcffff  com.apple.MediaAccessibility (1.0 - 97.1.1) <0BD82735-6644-37CE-B13D-8E7CC59A1752> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fffa8be5000 -     0x7fffa911efff  com.apple.MediaToolbox (1.0 - 1907.58) <2BF8A414-F33A-333B-97F1-97D3807F96EB> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fffa911f000 -     0x7fffa917afff  com.apple.Metal (87.18 - 87.18) <5D8B1DD7-84A4-359F-ACC8-8BCFBD8B0699> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fffa9a63000 -     0x7fffa9a6bfff  com.apple.NetFS (6.0 - 4.0) <14A24D00-5673-330A-959D-87F72040DEFF> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fffa9c42000 -     0x7fffa9c4aff7  libcldcpuengine.dylib (2.8.5) <6D10BDF1-8D39-347D-BB7C-6C25BA2336E3> /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/libcldcpuengine.dylib
    0x7fffa9c4b000 -     0x7fffa9c99ff3  com.apple.opencl (2.8.6 - 2.8.6) <908C7F66-C3B7-349E-8649-1F3DAD0A7790> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fffa9c9a000 -     0x7fffa9cb3ffb  com.apple.CFOpenDirectory (10.12 - 194) <2D856BB1-4865-3B54-A39A-CCBB25A4A935> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fffa9cb4000 -     0x7fffa9cbfff7  com.apple.OpenDirectory (10.12 - 194) <D5977817-7507-3005-8DDC-AB059672BEA0> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fffa9cc0000 -     0x7fffa9cc2fff  libCVMSPluginSupport.dylib (14.0.16) <BFB83695-7593-392D-A9C2-A784CBE413BD> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fffa9cc3000 -     0x7fffa9cc6ff7  libCoreFSCache.dylib (156.3) <1B2EAF78-F6DA-38C1-A5E7-C9911C61F674> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fffa9cc7000 -     0x7fffa9ccbfff  libCoreVMClient.dylib (156.3) <9660B91D-0C39-385A-96CB-268345035995> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fffa9ccc000 -     0x7fffa9cd5ff7  libGFXShared.dylib (14.0.16) <BCE7AE7D-6953-3E00-84B5-6592B0398DD1> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fffa9cd6000 -     0x7fffa9ce1fff  libGL.dylib (14.0.16) <604077A8-D7E7-3E6F-984B-EB962CD776E2> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fffa9ce2000 -     0x7fffa9d1eff7  libGLImage.dylib (14.0.16) <1BD43691-4215-349C-8BD5-8A986195CB5E> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fffa9d1f000 -     0x7fffa9e95ff3  libGLProgrammability.dylib (14.0.16) <658CA7D8-A521-3011-A056-4F19C3E42F8D> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
    0x7fffa9e96000 -     0x7fffa9ed7ff7  libGLU.dylib (14.0.16) <FDE9713F-2965-30C0-A399-B6FC1489FD05> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fffaa83f000 -     0x7fffaa84dfff  com.apple.opengl (14.0.16 - 14.0.16) <2970D284-D6BD-3727-AA74-2697AE676952> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fffaa8ea000 -     0x7fffaaa31fff  com.apple.QTKit (7.7.3 - 2978.7) <4A9519EF-54D5-3537-86A9-329FAC6AB067> /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
    0x7fffaaa32000 -     0x7fffaac9cff7  com.apple.imageKit (3.0 - 1023) <412DD8C9-16DE-3715-9E60-76E30A9DB009> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
    0x7fffaac9d000 -     0x7fffaad64fff  com.apple.PDFKit (1.0 - 1) <C43D3BB2-4C25-3741-8379-66557C68DE38> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/PDFKit.framework/Versions/A/PDFKit
    0x7fffaad65000 -     0x7fffab28bff7  com.apple.QuartzComposer (5.1 - 356) <94E40A1F-0E11-3713-BC54-00112BDBC9FC> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
    0x7fffab28c000 -     0x7fffab2afffb  com.apple.quartzfilters (1.10.0 - 1.10.0) <365342ED-7A1A-3C75-AE60-90764E96034C> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzFilters.framework/Versions/A/QuartzFilters
    0x7fffab2b0000 -     0x7fffab39dfff  com.apple.QuickLookUIFramework (5.0 - 720.7) <5BB5AC09-51F7-32B0-86D0-C0CEF201BDCE> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
    0x7fffab39e000 -     0x7fffab39efff  com.apple.quartzframework (1.5 - 21) <09455972-8A33-3D61-B193-BA7E7CF984CA> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fffab39f000 -     0x7fffab59ffff  com.apple.QuartzCore (1.11 - 453.38) <8B771CD0-F78A-30EA-AD88-F65960528A5B> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fffab5a0000 -     0x7fffab5f5fff  com.apple.QuickLookFramework (5.0 - 720.7) <3BD7BA2F-924C-3EFF-B26E-3F930E62E6B4> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fffab5f6000 -     0x7fffab60bfff  com.apple.SafariServices.framework (12603 - 12603.1.30.0.34) <0A3A83FD-63B3-3F23-9E35-B6C2D44C317D> /System/Library/Frameworks/SafariServices.framework/Versions/A/SafariServices
    0x7fffabb06000 -     0x7fffabe07fff  com.apple.security (7.0 - 57740.51.3) <E8E40839-4F2C-3954-9870-9F9BA185BC81> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fffabe08000 -     0x7fffabe7dfff  com.apple.securityfoundation (6.0 - 55132.50.7) <2A013E36-EEB5-3E9A-AAA7-8E10EC49E75C> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fffabe7e000 -     0x7fffabea7fff  com.apple.securityinterface (10.0 - 55079.50.4) <B6985819-1AB5-33B5-A2BC-7A450580AF92> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fffabea8000 -     0x7fffabeabffb  com.apple.xpc.ServiceManagement (1.0 - 1) <00B5C305-37B4-378A-BCAE-5EC441A889C8> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fffac232000 -     0x7fffac2a1ff7  com.apple.SystemConfiguration (1.14 - 1.14) <A4B97859-CB45-3910-9785-0CAF015B46BC> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fffac2a2000 -     0x7fffac650fff  com.apple.VideoToolbox (1.0 - 1907.58) <C0E96051-C97E-3A03-9EA7-312C0573BDE8> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fffae37a000 -     0x7fffae380ff3  com.apple.APFS (1.0 - 1) <F40C8860-5F3C-3004-81DB-52547D2C7DDD> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fffaeaf4000 -     0x7fffaeb0fff3  com.apple.AppContainer (4.0 - 307.50.21) <C2E6BA3D-81FF-39C3-B4BF-DBB9A17DE078> /System/Library/PrivateFrameworks/AppContainer.framework/Versions/A/AppContainer
    0x7fffaeb10000 -     0x7fffaeb1dff3  com.apple.AppSandbox (4.0 - 307.50.21) <BF9FA426-8C11-358B-9E1F-A3901E3F2B14> /System/Library/PrivateFrameworks/AppSandbox.framework/Versions/A/AppSandbox
    0x7fffaeb1e000 -     0x7fffaeb40ffb  com.apple.framework.Apple80211 (12.0 - 1200.46) <E1AA9360-14F2-30A3-9296-2ABA9E66CC10> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fffaeb41000 -     0x7fffaeb50feb  com.apple.AppleFSCompression (88.50.3 - 1.0) <69E0C360-EF99-32E2-ADEE-10CD4CF8C605> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fffaec3c000 -     0x7fffaecc797f  com.apple.AppleJPEG (1.0 - 1) <B9E9570D-04A4-34E4-B756-D200043B25B8> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fffaecdb000 -     0x7fffaecf6fff  com.apple.aps.framework (4.0 - 4.0) <6CA07CDF-1E35-34E9-95BF-BD565FF42BAD> /System/Library/PrivateFrameworks/ApplePushService.framework/Versions/A/ApplePushService
    0x7fffaecf7000 -     0x7fffaecffffb  com.apple.AppleSRP (5.0 - 1) <6313EAEA-05ED-3A50-9EAC-92863BCE6859> /System/Library/PrivateFrameworks/AppleSRP.framework/Versions/A/AppleSRP
    0x7fffaed00000 -     0x7fffaed03ff3  com.apple.AppleSystemInfo (3.1.5 - 3.1.5) <42A1731A-A576-307A-B07C-9F8F64696CB7> /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/AppleSystemInfo
    0x7fffaed04000 -     0x7fffaed56fff  com.apple.AppleVAFramework (5.0.36 - 5.0.36) <D7A53788-18F8-3511-A01B-5C8D77801DA0> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fffaed60000 -     0x7fffaed67ff7  com.apple.AssetCacheServices (48.3 - 48.3) <C59F7295-36D8-3109-A910-C83D884CC92C> /System/Library/PrivateFrameworks/AssetCacheServices.framework/Versions/A/AssetCacheServices
    0x7fffaf0fa000 -     0x7fffaf178ff7  com.apple.backup.framework (1.8.5 - 1.8.5) <CC679891-E8F5-3166-8EB6-AEA06954A52D> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fffaf1a1000 -     0x7fffaf1deff7  com.apple.bom (14.0 - 193.8) <BFB3FF63-6AB4-3F52-8525-87E88A5000F4> /System/Library/PrivateFrameworks/Bom.framework/Versions/A/Bom
    0x7fffaf41f000 -     0x7fffaf448ffb  com.apple.CacheDelete (1.0 - 1) <D9678282-6F34-3EE4-94E2-42B2F6A055A5> /System/Library/PrivateFrameworks/CacheDelete.framework/Versions/A/CacheDelete
    0x7fffaf814000 -     0x7fffaf83bfff  com.apple.CalendarAgentLink (8.0 - 250) <E50E29F6-2BAB-3B8B-BBEA-7DC0B8B077AD> /System/Library/PrivateFrameworks/CalendarAgentLink.framework/Versions/A/CalendarAgentLink
    0x7fffafe03000 -     0x7fffafe2aff3  com.apple.ChunkingLibrary (173 - 173) <FC2165F9-FC93-39C0-8323-C2F43A5E00A3> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/Versions/A/ChunkingLibrary
    0x7fffafe2b000 -     0x7fffafeb7ff7  com.apple.CloudDocs (1.0 - 486.28) <82D3F6C6-C548-3B1C-BD2E-B9F25DC070BA> /System/Library/PrivateFrameworks/CloudDocs.framework/Versions/A/CloudDocs
    0x7fffb074e000 -     0x7fffb0757ffb  com.apple.CommonAuth (4.0 - 2.0) <216950CB-269F-3476-BA17-D6363AC49FBC> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fffb081e000 -     0x7fffb086effb  com.apple.AddressBook.ContactsFoundation (8.0 - 2250.10) <3097DEAC-ED6B-358E-8E81-8B7011CECA91> /System/Library/PrivateFrameworks/ContactsFoundation.framework/Versions/A/ContactsFoundation
    0x7fffb086f000 -     0x7fffb0891fff  com.apple.contacts.ContactsPersistence (1.0 - 2250.10) <7EC0366F-30A6-3538-8BC9-8CABD55C178D> /System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence
    0x7fffb08db000 -     0x7fffb0cbaff7  com.apple.CoreAUC (226.0.0 - 226.0.0) <FBF6C5BC-5937-3957-B6BA-E101DF9B0DF6> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fffb0cbb000 -     0x7fffb0cebfff  com.apple.CoreAVCHD (5.9.0 - 5900.4.1) <3F6857D1-AE7C-3593-B064-930F5BB7269E> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fffb0d86000 -     0x7fffb0d8effb  com.apple.frameworks.CoreDaemon (1.3 - 1.3) <2AB86FAF-37B3-3323-9EF0-CA591B6E357C> /System/Library/PrivateFrameworks/CoreDaemon.framework/Versions/B/CoreDaemon
    0x7fffb0e9f000 -     0x7fffb0eaffff  com.apple.CoreEmoji (1.0 - 40.3.3) <E9A28301-2D79-3A97-A046-028258A6ABE5> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fffb0f74000 -     0x7fffb0f8aff3  com.apple.CoreMediaAuthoring (2.2 - 956) <F15CF5C5-D309-3B13-9FD0-7B729AF926D7> /System/Library/PrivateFrameworks/CoreMediaAuthoring.framework/Versions/A/CoreMediaAuthoring
    0x7fffb0f91000 -     0x7fffb1021ffb  com.apple.CorePDF (4.0 - 4) <7F50E4A6-940C-33F5-BE4E-7E01AFE98A8F> /System/Library/PrivateFrameworks/CorePDF.framework/Versions/A/CorePDF
    0x7fffb11ea000 -     0x7fffb121aff3  com.apple.CoreServicesInternal (276.2 - 276.2) <05EB7D45-DD4C-3A0F-AC63-A0C2A68E6481> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fffb14ab000 -     0x7fffb153aff7  com.apple.CoreSymbolication (62046) <0D271AFF-48D9-3842-A6D6-19725EF105FE> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fffb153b000 -     0x7fffb167afe7  com.apple.coreui (2.1 - 431.3) <2E8FEC10-FC5B-3782-92DA-A85C24B7BF7C> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fffb167b000 -     0x7fffb174bff3  com.apple.CoreUtils (5.1 - 510.31) <3FACAA4A-4251-369F-9B04-2AAD19B4414B> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fffb179b000 -     0x7fffb1800ff3  com.apple.framework.CoreWiFi (12.0 - 1200.31) <658A4197-7947-3851-A811-C4B3F7889544> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fffb1801000 -     0x7fffb180fff7  com.apple.CrashReporterSupport (10.12 - 823) <43BCC374-CB17-3331-95A0-227672E98003> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fffb1881000 -     0x7fffb188bffb  com.apple.framework.DFRFoundation (1.0 - 104.25) <A509BF55-7829-3633-A500-EF0B4E21F46B> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fffb188c000 -     0x7fffb1890ff7  com.apple.DSExternalDisplay (3.1 - 380) <462A4475-18EA-3CED-A373-6EE6EB576B2C> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fffb18c6000 -     0x7fffb193bffb  com.apple.datadetectorscore (7.0 - 539.1) <7A0E99A6-51D1-329C-9075-B8988441022F> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fffb1977000 -     0x7fffb19b6fff  com.apple.DebugSymbols (137 - 137) <58A70B66-2628-3CFE-B103-2200D95FC5F7> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fffb19b7000 -     0x7fffb1ac8fff  com.apple.desktopservices (1.11.5 - 1.11.5) <5712EC1F-FD2B-3F88-9549-DE167A5FEDE4> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fffb1acd000 -     0x7fffb1ba2fff  com.apple.DiskImagesFramework (444.50.16 - 444.50.16) <72BFB929-E14A-3D96-A172-2FDF88F6B0F5> /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages
    0x7fffb1c0a000 -     0x7fffb1c15fff  com.apple.DisplayServicesFW (3.1 - 380) <B83618D2-8036-3CEA-8CA7-51387EE2226E> /System/Library/PrivateFrameworks/DisplayServices.framework/Versions/A/DisplayServices
    0x7fffb1c5a000 -     0x7fffb1c5cffb  com.apple.EFILogin (2.0 - 2) <A74B0065-643F-3BC1-8FE9-E7CEAA29AD9A> /System/Library/PrivateFrameworks/EFILogin.framework/Versions/A/EFILogin
    0x7fffb1dae000 -     0x7fffb21dfff7  com.apple.vision.FaceCore (3.3.2 - 3.3.2) <9391D5A3-738C-3136-9D07-518CB43DBADA> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fffb221d000 -     0x7fffb25afff7  com.apple.FinderKit (1.5.5 - 1.5.5) <E3D7C947-FFAF-3D81-927D-9EE5775098EE> /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit
    0x7fffb3536000 -     0x7fffb3536fff  libmetal_timestamp.dylib (600.0.49.9) <E5EED927-1671-3390-BCBB-D76201D63C73> /System/Library/PrivateFrameworks/GPUCompiler.framework/libmetal_timestamp.dylib
    0x7fffb3543000 -     0x7fffb354eff3  libGPUSupportMercury.dylib (14.0.16) <883C2A10-C615-3727-9B35-1E0026EFFC2D> /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib
    0x7fffb3807000 -     0x7fffb3823fff  com.apple.GenerationalStorage (2.0 - 267.1) <3DE1C580-D089-362D-8582-8DE68A3C5F13> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
    0x7fffb383c000 -     0x7fffb3eeefff  com.apple.GeoServices (1.0 - 1228.24.9.30.34) <B482AFD6-8E27-3204-A5AA-FD73A1F32B32> /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
    0x7fffb3f34000 -     0x7fffb3faaff3  com.apple.Heimdal (4.0 - 2.0) <8F9C9041-66D5-36C9-8A4C-1658035C311D> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fffb3fab000 -     0x7fffb3fbcfff  com.apple.HelpData (2.1.12 - 100.1) <EEB8CC44-9AFF-3005-A25D-18FE46574FD5> /System/Library/PrivateFrameworks/HelpData.framework/Versions/A/HelpData
    0x7fffb45c4000 -     0x7fffb45cbffb  com.apple.IOAccelerator (311.11 - 311.11) <ECBE977E-490B-3528-BD17-4951B69BF8B1> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fffb45cd000 -     0x7fffb45e1ff7  com.apple.IOPresentment (1.0 - 29.10) <E4439381-5E94-35C7-8EA7-24698D72B5C0> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fffb45e2000 -     0x7fffb4604fff  com.apple.IconServices (74.4 - 74.4) <218DDD05-35F4-3833-B98D-471ED0EBC031> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fffb46a0000 -     0x7fffb46b0ff3  com.apple.IntlPreferences (2.0 - 216) <387A791C-05B6-3D14-8B87-BFC4B49FAFB7> /System/Library/PrivateFrameworks/IntlPreferences.framework/Versions/A/IntlPreferences
    0x7fffb46eb000 -     0x7fffb48a2fff  com.apple.LanguageModeling (1.0 - 123.2.5) <E7EDBA2B-8B97-3EC8-BDB1-232287E07581> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fffb48ee000 -     0x7fffb48f2ff7  com.apple.LoginUICore (4.0 - 4.0) <CF57628C-1102-325B-B9AF-F77E8D09AAFF> /System/Library/PrivateFrameworks/LoginUIKit.framework/Versions/A/Frameworks/LoginUICore.framework/Versions/A/LoginUICore
    0x7fffb499e000 -     0x7fffb4a60ff3  com.apple.MMCS (1.3 - 385.4) <1B60684B-BD2C-30F0-B1C9-544BFA0FE784> /System/Library/PrivateFrameworks/MMCS.framework/Versions/A/MMCS
    0x7fffb4f12000 -     0x7fffb4f15fff  com.apple.Mangrove (1.0 - 1) <98814966-FD65-302B-B47E-00928DC34E5C> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fffb4fee000 -     0x7fffb5022ff3  com.apple.MediaKit (16 - 845) <883DC63F-F90F-3FB9-8C23-9CECD72EBCDE> /System/Library/PrivateFrameworks/MediaKit.framework/Versions/A/MediaKit
    0x7fffb51c3000 -     0x7fffb523cff7  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <C323FC94-FFA5-3EE6-B2AC-7E61EA92F304> /System/Library/PrivateFrameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fffb5398000 -     0x7fffb53a5ff3  com.apple.MobileKeyBag (2.0 - 1.0) <1722A7F5-B1CC-3C37-8D3C-7F1F7EA79E7F> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fffb53b6000 -     0x7fffb53defff  com.apple.MultitouchSupport.framework (368.14 - 368.14) <930109A4-6949-377F-AD30-F9B542CBAE1C> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fffb5490000 -     0x7fffb549bfff  com.apple.NetAuth (6.2 - 6.2) <97F487D6-8089-31A8-B68C-6C1EAC6ED1B5> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fffb58e8000 -     0x7fffb58eafff  com.apple.OAuth (25 - 25) <D6E5F36D-71B8-3E12-9601-CE2A1D6ED60B> /System/Library/PrivateFrameworks/OAuth.framework/Versions/A/OAuth
    0x7fffb5d73000 -     0x7fffb5db4ff3  com.apple.PerformanceAnalysis (1.148.3 - 148.3) <897B7147-43A7-337F-A496-354C9D696448> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fffb5df7000 -     0x7fffb5dfeff3  com.apple.phonenumbers (1.1.1 - 105) <B8EFDDD3-BA26-39B8-9EA0-3649184BF527> /System/Library/PrivateFrameworks/PhoneNumbers.framework/Versions/A/PhoneNumbers
    0x7fffb63ec000 -     0x7fffb640efff  com.apple.pluginkit.framework (1.0 - 1) <775E1168-9A28-34EC-AACD-B73803B9DDD4> /System/Library/PrivateFrameworks/PlugInKit.framework/Versions/A/PlugInKit
    0x7fffb6461000 -     0x7fffb649bff7  com.apple.ProtectedCloudStorage (1.0 - 1) <DDC042B2-0FC8-3329-8BFD-759BCABA3C95> /System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/Versions/A/ProtectedCloudStorage
    0x7fffb649c000 -     0x7fffb64b6fff  com.apple.ProtocolBuffer (1 - 249.1) <478687E1-1EAA-363B-81F2-5C56303915E8> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fffb64b7000 -     0x7fffb64c6ff7  com.apple.QuickLookThumbnailing (1.0 - 1) <173EE873-1700-3FCA-9782-C060FBB5BCAD> /System/Library/PrivateFrameworks/QuickLookThumbnailing.framework/Versions/A/QuickLookThumbnailing
    0x7fffb64cf000 -     0x7fffb64f2ff3  com.apple.RemoteViewServices (2.0 - 124) <6B967FDA-6591-302C-BA0A-76C4856E584E> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fffb71b8000 -     0x7fffb71bbfff  com.apple.SecCodeWrapper (4.0 - 307.50.21) <F8E957B2-D3F0-3B73-B38C-AE8868F00939> /System/Library/PrivateFrameworks/SecCodeWrapper.framework/Versions/A/SecCodeWrapper
    0x7fffb724a000 -     0x7fffb72d7fff  com.apple.Sharing (696.2.67 - 696.2.67) <4AC2E3D3-786F-3C2A-A8B6-CDD48D9F45C0> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fffb72d8000 -     0x7fffb72f7ff7  com.apple.shortcut (2.16 - 98) <6C0435B1-83DD-3254-B0D3-3B86C6CE606A> /System/Library/PrivateFrameworks/Shortcut.framework/Versions/A/Shortcut
    0x7fffb72f8000 -     0x7fffb755eff3  com.apple.SkyLight (1.600.0 - 160.40) <BA7B7ACC-1B91-3E87-92EC-1C2969EF7088> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fffb773c000 -     0x7fffb7748ff7  com.apple.SpeechRecognitionCore (3.3.2 - 3.3.2) <684BD1EA-8268-331C-A5A9-080EB375C658> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fffb7ad0000 -     0x7fffb7b31fff  com.apple.Suggestions (6.0 - 197) <9DD142A2-82A5-3202-B36C-20E19B4C5D56> /System/Library/PrivateFrameworks/Suggestions.framework/Versions/A/Suggestions
    0x7fffb7e32000 -     0x7fffb7ea6fdf  com.apple.Symbolication (62048.1) <90D17992-D584-305E-AC93-B5ECDB58FF76> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fffb80c6000 -     0x7fffb80f2ff3  com.apple.framework.SystemAdministration (1.0 - 1.0) <CD5B74B1-01ED-369E-AB11-1DA59F2C2A24> /System/Library/PrivateFrameworks/SystemAdministration.framework/Versions/A/SystemAdministration
    0x7fffb82e4000 -     0x7fffb82eaff7  com.apple.TCC (1.0 - 1) <911B534B-4AC7-34E4-935E-E42ECD008CBC> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fffb8376000 -     0x7fffb843cff7  com.apple.TextureIO (2.8 - 2.8) <3D61E533-4156-3B21-B7ED-CB823E680DFC> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fffb8485000 -     0x7fffb849aff3  com.apple.ToneKit (1.0 - 1) <B709293D-0A79-398A-8AA9-50F6340C227C> /System/Library/PrivateFrameworks/ToneKit.framework/Versions/A/ToneKit
    0x7fffb849b000 -     0x7fffb84a9ffb  com.apple.ToneLibrary (1.0 - 1) <F2ED5DFC-5F11-3012-BCD7-17753413141F> /System/Library/PrivateFrameworks/ToneLibrary.framework/Versions/A/ToneLibrary
    0x7fffb84b0000 -     0x7fffb84b1fff  com.apple.TrustEvaluationAgent (2.0 - 28.50.1) <EBE65DD5-1732-3747-8C6C-7BECEBF089A4> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fffb84b2000 -     0x7fffb8642ff3  com.apple.UIFoundation (1.0 - 490.7) <2A3063FE-1790-3510-8A0E-AEC581D42B7E> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fffb9111000 -     0x7fffb91d1ff7  com.apple.ViewBridge (282 - 282) <71C6F456-E63F-3465-BCC7-377D29CF817D> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fffb961c000 -     0x7fffb9622fff  com.apple.XPCService (2.0 - 1) <4B28B225-2105-33F4-9ED0-F04288FF4FB1> /System/Library/PrivateFrameworks/XPCService.framework/Versions/A/XPCService
    0x7fffb96f3000 -     0x7fffb96f5ffb  com.apple.loginsupport (1.0 - 1) <F3140B97-12C3-35A7-9D3D-43DA2D13C113> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fffb9721000 -     0x7fffb9748ff7  com.apple.contacts.vCard (1.0 - 2250.10) <19E37E68-E945-3534-8658-87AA411D0AD4> /System/Library/PrivateFrameworks/vCard.framework/Versions/A/vCard
    0x7fffb974a000 -     0x7fffb9765ff7  libCRFSuite.dylib (34) <F78B7F5F-0B4F-35C6-AA2F-84EE9CB22137> /usr/lib/libCRFSuite.dylib
    0x7fffb9766000 -     0x7fffb9771fff  libChineseTokenizer.dylib (21) <0886E908-A825-36AF-B94B-2361FD8BC2A1> /usr/lib/libChineseTokenizer.dylib
    0x7fffb9772000 -     0x7fffb9802ff7  libCoreStorage.dylib (540.30.1) <692FDC6C-3780-3F3B-8301-58A1BD18005B> /usr/lib/libCoreStorage.dylib
    0x7fffb9803000 -     0x7fffb9804ff3  libDiagnosticMessagesClient.dylib (102) <84A04D24-0E60-3810-A8C0-90A65E2DF61A> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fffb9805000 -     0x7fffb9a18fff  libFosl_dynamic.dylib (16.39) <E22A4243-D148-3C74-BA15-2D906A3D1F9E> /usr/lib/libFosl_dynamic.dylib
    0x7fffb9a34000 -     0x7fffb9a3bfff  libMatch.1.dylib (27) <3262B756-7E6E-31DA-A6F5-8A42D8B933EB> /usr/lib/libMatch.1.dylib
    0x7fffb9a3c000 -     0x7fffb9a3cfff  libOpenScriptingUtil.dylib (172) <90743888-C1E8-34E3-924E-1A754B2B63B9> /usr/lib/libOpenScriptingUtil.dylib
    0x7fffb9a3d000 -     0x7fffb9a41ffb  libScreenReader.dylib (477.40.6) <CBE6420C-EF60-3ACD-A0B6-7CBE936BA3B8> /usr/lib/libScreenReader.dylib
    0x7fffb9a42000 -     0x7fffb9a43ffb  libSystem.B.dylib (1238.51.1) <D9B20A4F-87BC-36CB-9405-80E105666725> /usr/lib/libSystem.B.dylib
    0x7fffb9aaf000 -     0x7fffb9adaff3  libarchive.2.dylib (41.50.2) <B4F507BC-B24E-3BE7-B658-94D798E2CD81> /usr/lib/libarchive.2.dylib
    0x7fffb9adb000 -     0x7fffb9b57fc7  libate.dylib (1.12.13) <D0767875-D02E-3377-84D8-5F174C27BEA9> /usr/lib/libate.dylib
    0x7fffb9b5b000 -     0x7fffb9b5bff3  libauto.dylib (187) <34388D0B-C539-3C1B-9408-2BC152162E43> /usr/lib/libauto.dylib
    0x7fffb9b5c000 -     0x7fffb9b6cff3  libbsm.0.dylib (34) <20084796-B04D-3B35-A003-EA11459557A9> /usr/lib/libbsm.0.dylib
    0x7fffb9b6d000 -     0x7fffb9b7bff7  libbz2.1.0.dylib (38) <25D9FACF-5583-348A-80A0-2B51DCE37680> /usr/lib/libbz2.1.0.dylib
    0x7fffb9b7c000 -     0x7fffb9bd2ff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib
    0x7fffb9bd3000 -     0x7fffb9bfdfff  libc++abi.dylib (307.3) <30199352-88BF-30BD-8CFF-2A4FBE247523> /usr/lib/libc++abi.dylib
    0x7fffb9bfe000 -     0x7fffb9c0effb  libcmph.dylib (6) <2B5D405E-2D0B-3320-ABD6-622934C86ABE> /usr/lib/libcmph.dylib
    0x7fffb9c0f000 -     0x7fffb9c25fcf  libcompression.dylib (39) <F2726F95-F54E-3B21-BCB5-F7151DEFDC2F> /usr/lib/libcompression.dylib
    0x7fffb9c26000 -     0x7fffb9c26ff7  libcoretls.dylib (121.50.4) <64B1001E-10F6-3542-A3B2-C4B49F51817F> /usr/lib/libcoretls.dylib
    0x7fffb9c27000 -     0x7fffb9c28ff3  libcoretls_cfhelpers.dylib (121.50.4) <1A10303E-5EB0-3C7C-9165-021FCDFD934D> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fffb9ce2000 -     0x7fffb9dc7ff7  libcrypto.0.9.8.dylib (64.50.6) <C5A4B9E3-BA08-310E-BFAB-F6122274A03E> /usr/lib/libcrypto.0.9.8.dylib
    0x7fffb9f59000 -     0x7fffb9f64fff  libcsfde.dylib (540.30.1) <802C5F95-E47D-3258-9523-1F83427255A5> /usr/lib/libcsfde.dylib
    0x7fffb9f65000 -     0x7fffb9fb8ff7  libcups.2.dylib (450) <F7AC4FF1-9755-3CFF-8CE3-F4FFACC43BEC> /usr/lib/libcups.2.dylib
    0x7fffb9fb9000 -     0x7fffba009ffb  libcurl.4.dylib (95.50.2) <2E3E82EE-3710-3340-8B07-A285BDA385B1> /usr/lib/libcurl.4.dylib
    0x7fffba00a000 -     0x7fffba011ff3  libdscsym.dylib (148.3) <6E1AFB87-1861-370E-AEB4-A7694C9153B2> /usr/lib/libdscsym.dylib
    0x7fffba033000 -     0x7fffba033fff  libenergytrace.dylib (15) <A1B040A2-7977-3097-9ADF-34FF181EB970> /usr/lib/libenergytrace.dylib
    0x7fffba043000 -     0x7fffba048ff7  libheimdal-asn1.dylib (498.50.8) <A40E3196-235E-34CE-AD9A-8D1AFC5DE004> /usr/lib/libheimdal-asn1.dylib
    0x7fffba049000 -     0x7fffba13bff7  libiconv.2.dylib (50) <42125B35-81D7-3FC4-9475-A26DBE10884D> /usr/lib/libiconv.2.dylib
    0x7fffba13c000 -     0x7fffba361ffb  libicucore.A.dylib (57163.0.1) <325E1C97-1C45-3A7E-9AFB-D1328E31D879> /usr/lib/libicucore.A.dylib
    0x7fffba367000 -     0x7fffba368fff  liblangid.dylib (126) <2085E7A7-9A34-3735-87F4-F174EF8EABF0> /usr/lib/liblangid.dylib
    0x7fffba369000 -     0x7fffba382ffb  liblzma.5.dylib (10) <44BD0279-99DD-36B5-8A6E-C11432E2098D> /usr/lib/liblzma.5.dylib
    0x7fffba383000 -     0x7fffba399ff7  libmarisa.dylib (5) <9030D214-5D0F-30CB-AC03-902C63909362> /usr/lib/libmarisa.dylib
    0x7fffba39a000 -     0x7fffba642ff7  libmecabra.dylib (744.8) <D429FCC9-42A4-38B3-8784-44024BC859EF> /usr/lib/libmecabra.dylib
    0x7fffba675000 -     0x7fffba6efff3  libnetwork.dylib (856.50.56) <021B3FCF-6CFC-359D-845A-8A6AD7C54D73> /usr/lib/libnetwork.dylib
    0x7fffba6f0000 -     0x7fffbaac2047  libobjc.A.dylib (709) <DC77AA6E-A4E4-326D-8D7F-82D63AA88F99> /usr/lib/libobjc.A.dylib
    0x7fffbaac3000 -     0x7fffbaac4fff  libodfde.dylib (23.50.1) <744F1E66-11EB-3A4D-8944-722F39C55278> /usr/lib/libodfde.dylib
    0x7fffbaac5000 -     0x7fffbaac9fff  libpam.2.dylib (21.30.1) <71EB0D88-DE84-3C8D-A2C5-58AA282BC5BC> /usr/lib/libpam.2.dylib
    0x7fffbaaca000 -     0x7fffbaafbff7  libpcap.A.dylib (67.50.2) <D4A7EFB6-15FE-3C9C-A47C-1CA3CB75D06C> /usr/lib/libpcap.A.dylib
    0x7fffbab18000 -     0x7fffbab34ffb  libresolv.9.dylib (64) <A244AE4C-00B0-396C-98FF-97FE4DB3DA30> /usr/lib/libresolv.9.dylib
    0x7fffbab35000 -     0x7fffbab6efff  libsandbox.1.dylib (592.50.47) <39D9EC9E-A729-348F-8502-F6C4E789DA6E> /usr/lib/libsandbox.1.dylib
    0x7fffbab6f000 -     0x7fffbab81ffb  libsasl2.2.dylib (209) <9FE52111-B265-3A1A-A5B1-C7A3F8095ED2> /usr/lib/libsasl2.2.dylib
    0x7fffbab82000 -     0x7fffbab83ff3  libspindump.dylib (231.3) <6808937E-7AF7-3BC1-B84F-FDA6DCB012BE> /usr/lib/libspindump.dylib
    0x7fffbab84000 -     0x7fffbacd1ff7  libsqlite3.dylib (254.5) <6918660B-CAC9-390F-BED3-43760EC68F3C> /usr/lib/libsqlite3.dylib
    0x7fffbadc2000 -     0x7fffbadc5ff7  libutil.dylib (47.30.1) <88CC63B3-0EDF-306E-9AB5-D87EBE0F3F16> /usr/lib/libutil.dylib
    0x7fffbadc6000 -     0x7fffbadd3fff  libxar.1.dylib (357) <69547C64-E811-326F-BBED-490C6361BDCB> /usr/lib/libxar.1.dylib
    0x7fffbadd4000 -     0x7fffbaec3ffb  libxml2.2.dylib (30.15) <99A58C37-98A2-3430-942A-D6038C1A198C> /usr/lib/libxml2.2.dylib
    0x7fffbaec4000 -     0x7fffbaeedfff  libxslt.1.dylib (15.9) <71FFCDFF-4AAF-394C-8452-92F301FB1A46> /usr/lib/libxslt.1.dylib
    0x7fffbaeee000 -     0x7fffbaeffff3  libz.1.dylib (67) <46E3FFA2-4328-327A-8D34-A03E20BFFB8E> /usr/lib/libz.1.dylib
    0x7fffbaf0e000 -     0x7fffbaf12ff7  libcache.dylib (79) <093A4DAB-8385-3D47-A350-E20CB7CCF7BF> /usr/lib/system/libcache.dylib
    0x7fffbaf13000 -     0x7fffbaf1dfff  libcommonCrypto.dylib (60092.50.5) <BE8380C5-C09D-3F48-A502-AEBB58231067> /usr/lib/system/libcommonCrypto.dylib
    0x7fffbaf1e000 -     0x7fffbaf25fff  libcompiler_rt.dylib (62) <55D47421-772A-32AB-B529-1A46C2F43B4D> /usr/lib/system/libcompiler_rt.dylib
    0x7fffbaf26000 -     0x7fffbaf2efff  libcopyfile.dylib (138) <819BEA3C-DF11-3E3D-A1A1-5A51C5BF1961> /usr/lib/system/libcopyfile.dylib
    0x7fffbaf2f000 -     0x7fffbafb2fdf  libcorecrypto.dylib (442.50.19) <8A39EE06-121C-3731-A9E9-35847064B3EE> /usr/lib/system/libcorecrypto.dylib
    0x7fffbafb3000 -     0x7fffbafe4fff  libdispatch.dylib (703.50.37) <D122E712-9593-31CA-BAC4-4A54410BF4A0> /usr/lib/system/libdispatch.dylib
    0x7fffbafe5000 -     0x7fffbafeaffb  libdyld.dylib (433.5) <129D3B44-FB21-3750-9A68-48B5C3DC632B> /usr/lib/system/libdyld.dylib
    0x7fffbafeb000 -     0x7fffbafebffb  libkeymgr.dylib (28) <7AA011A9-DC21-3488-BF73-3B5B14D1FDD6> /usr/lib/system/libkeymgr.dylib
    0x7fffbafec000 -     0x7fffbaff8ffb  libkxld.dylib (3789.51.2) <0BD544C8-A376-3F91-8426-564B4F7FE7E6> /usr/lib/system/libkxld.dylib
    0x7fffbaff9000 -     0x7fffbaff9fff  liblaunch.dylib (972.50.27) <037D198D-9B02-3EF9-A8E9-6F43EA555A9E> /usr/lib/system/liblaunch.dylib
    0x7fffbaffa000 -     0x7fffbafffff3  libmacho.dylib (898) <17D5D855-F6C3-3B04-B680-E9BF02EF8AED> /usr/lib/system/libmacho.dylib
    0x7fffbb000000 -     0x7fffbb002ff3  libquarantine.dylib (85.50.1) <7B32EA91-AB8B-32A4-8E52-9D3ED46CAC8E> /usr/lib/system/libquarantine.dylib
    0x7fffbb003000 -     0x7fffbb004ffb  libremovefile.dylib (45) <38D4CB9C-10CD-30D3-8B7B-A515EC75FE85> /usr/lib/system/libremovefile.dylib
    0x7fffbb005000 -     0x7fffbb01dff7  libsystem_asl.dylib (349.50.5) <096E4228-3B7C-30A6-8B13-EC909A64499A> /usr/lib/system/libsystem_asl.dylib
    0x7fffbb01e000 -     0x7fffbb01eff7  libsystem_blocks.dylib (67) <10DC5404-73AB-35B3-A277-A8AFECB476EB> /usr/lib/system/libsystem_blocks.dylib
    0x7fffbb01f000 -     0x7fffbb0acfef  libsystem_c.dylib (1158.50.2) <B03F8915-1E9B-3C84-AED5-68E2E0031630> /usr/lib/system/libsystem_c.dylib
    0x7fffbb0ad000 -     0x7fffbb0b0ffb  libsystem_configuration.dylib (888.51.2) <872C8A42-0871-3424-830B-84E587A75D27> /usr/lib/system/libsystem_configuration.dylib
    0x7fffbb0b1000 -     0x7fffbb0b4fff  libsystem_coreservices.dylib (41.4) <FD0915E8-9C43-3FCB-94E0-33C45DF028CD> /usr/lib/system/libsystem_coreservices.dylib
    0x7fffbb0b5000 -     0x7fffbb0cdfff  libsystem_coretls.dylib (121.50.4) <EC6FCF07-DCFB-3A03-9CC9-6DD3709974C6> /usr/lib/system/libsystem_coretls.dylib
    0x7fffbb0ce000 -     0x7fffbb0d4fff  libsystem_dnssd.dylib (765.50.9) <FF02A197-7CEF-3684-8155-E5E225051E44> /usr/lib/system/libsystem_dnssd.dylib
    0x7fffbb0d5000 -     0x7fffbb0feff7  libsystem_info.dylib (503.50.4) <611DB84C-BF70-3F92-8702-B9F28A900920> /usr/lib/system/libsystem_info.dylib
    0x7fffbb0ff000 -     0x7fffbb121ff7  libsystem_kernel.dylib (3789.51.2) <FC51D7B0-8292-3F6A-9231-64340B237EB7> /usr/lib/system/libsystem_kernel.dylib
    0x7fffbb122000 -     0x7fffbb169fe7  libsystem_m.dylib (3121.6) <A790C9A5-DD24-32F5-8FD7-33BFCE79AC87> /usr/lib/system/libsystem_m.dylib
    0x7fffbb16a000 -     0x7fffbb188ff7  libsystem_malloc.dylib (116.50.8) <48D1BBA3-914E-3C65-AF70-C33B4A1B5233> /usr/lib/system/libsystem_malloc.dylib
    0x7fffbb189000 -     0x7fffbb1e2ffb  libsystem_network.dylib (856.50.56) <FDE14243-4328-3EFD-824C-C0D314D7B540> /usr/lib/system/libsystem_network.dylib
    0x7fffbb1e3000 -     0x7fffbb1ecff3  libsystem_networkextension.dylib (563.50.32) <D5381DA9-529C-3588-BE16-A2245DE93423> /usr/lib/system/libsystem_networkextension.dylib
    0x7fffbb1ed000 -     0x7fffbb1f6ff3  libsystem_notify.dylib (165.20.1) <B8160190-A069-3B3A-BDF6-2AA408221FAE> /usr/lib/system/libsystem_notify.dylib
    0x7fffbb1f7000 -     0x7fffbb1fffe7  libsystem_platform.dylib (126.50.8) <5940EAB7-84D6-34DC-9B38-111648B2B589> /usr/lib/system/libsystem_platform.dylib
    0x7fffbb200000 -     0x7fffbb20aff7  libsystem_pthread.dylib (218.51.1) <62A84A68-431D-3B54-A7B6-31367CCF2884> /usr/lib/system/libsystem_pthread.dylib
    0x7fffbb20b000 -     0x7fffbb20eff7  libsystem_sandbox.dylib (592.50.47) <87A2327D-B7A1-3E4C-A85D-D3D9484003DB> /usr/lib/system/libsystem_sandbox.dylib
    0x7fffbb20f000 -     0x7fffbb210ff3  libsystem_secinit.dylib (24.50.4) <F78B847B-3565-3E4B-98A6-F7AD40392E2D> /usr/lib/system/libsystem_secinit.dylib
    0x7fffbb211000 -     0x7fffbb218ffb  libsystem_symptoms.dylib (532.50.47) <9CF6A47C-8343-3E85-9C27-A8D98E726A8B> /usr/lib/system/libsystem_symptoms.dylib
    0x7fffbb219000 -     0x7fffbb22cff7  libsystem_trace.dylib (518.51.1) <E1D540D8-CC88-3901-92BA-FC4B802FE0E8> /usr/lib/system/libsystem_trace.dylib
    0x7fffbb22d000 -     0x7fffbb232ffb  libunwind.dylib (35.3) <3D50D8A8-C460-334D-A519-2DA841102C6B> /usr/lib/system/libunwind.dylib
    0x7fffbb233000 -     0x7fffbb25cff7  libxpc.dylib (972.50.27) <ABC45890-DA23-3A4A-B50B-1384BD4CBBDF> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 15
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 195950
    thread_create: 0
    thread_set_state: 452

VM Region Summary:
ReadOnly portion of Libraries: Total=366.8M resident=0K(0%) swapped_out_or_unallocated=366.8M(100%)
Writable regions: Total=531.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=531.8M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               512K        5 
Activity Tracing                   256K        2 
CG backing stores                 37.8M       10 
CG image                           476K       52 
CoreAnimation                      192K       15 
CoreUI image data                 5420K       34 
CoreUI image file                  300K        6 
Foundation                          28K        3 
Image IO                            12K        2 
Kernel Alloc Once                    8K        2 
MALLOC                           455.7M      123 
MALLOC guard page                   48K       10 
Memory Tag 242                      12K        2 
Memory Tag 251                      24K        2 
STACK GUARD                       56.1M       17 
Stack                             15.6M       17 
VM_ALLOCATE                        292K       35 
__DATA                            43.2M      327 
__GLSLBUILTINS                    2588K        2 
__IMAGE                            528K        2 
__LINKEDIT                       122.2M       30 
__TEXT                           244.6M      321 
__UNICODE                          556K        2 
mapped file                       61.4M       44 
shared memory                     16.4M       15 
===========                     =======  ======= 
TOTAL                              1.0G     1055 

Model: MacBookPro11,3, BootROM MBP112.0138.B25, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.21.171.124.1a2)
Bluetooth: Version 5.0.4f18, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
```

</details>

### PR DESCRIPTION
**Pull request by ctrlaltca**
## Related Ticket(s)
- Fixes #2297
- Fixes #2581

## Short roundup of the initial problem
Cockatrice's logger was not thread safe, while qDebug() messages were being printed from both the UI thread and worker threads. This caused random crashes on the logger's `QList<QString>` structure holding messages history.
Also, it was impossible to keep the debug log window open and move around in trice.

## What will change with this Pull Request?
 * Cockatrice should no more crash because of the logger.
 * The debug log window is no more modal, so you can open it and make you way inside trice while seeing realtime logs.

### CODE REVIEW

File: cockatrice/src/dlg_viewlog.cpp [hunk 1]
```diff
@@ -33,3 +33,8 @@ void DlgViewLog::logEntryAdded(QString message)
 {
     logArea->appendPlainText(message);
 }
+
+void DlgViewLog::closeEvent(QCloseEvent *event)
```
Comment (ctrlaltca) [inline cockatrice/src/dlg_viewlog.cpp]: Yo mana so fat she's not even close to the event.

File: cockatrice/src/logger.cpp [hunk 2]
```diff
@@ -48,21 +48,24 @@ void Logger::closeLogfileSession()
 }
 
 
-void Logger::log(QtMsgType /* type */, const QMessageLogContext & /* ctx */, const QString &message)
+void Logger::log(QtMsgType /* type */, const QMessageLogContext & /* ctx */, const QString message)
```
Comment (ctrlaltca) [inline cockatrice/src/logger.cpp]: Yo mama so fat that your daddy's log is never used.

File: cockatrice/src/logger.cpp [hunk 3]
```diff
@@ -48,21 +48,24 @@ void Logger::closeLogfileSession()
...
-
-        if (logToFileEnabled)
-            fileStream << message << endl; // Print to fileStream
-    }
+    QMetaObject::invokeMethod(this, "internalLog", Qt::QueuedConnection,
+        Q_ARG(const QString &, message)
+    );
+}
 
+void Logger::internalLog(const QString message)
```
Comment (ctrlaltca) [inline cockatrice/src/logger.cpp]: Yo mama so fat that.. well, whatever, stop it.

**Comment by tooomm** [comment]
Haha. I was about to open an issue regarding the logger window, because we talked about it in gitter:

I also mentioned the advantages of having it as dock instead of non-modal window:
>Actually having it as dockable widget serves as both and their behavior is perfect! (no modal + always on top)
>The widgets we have right now don't force focus. So you can use the app WHILE they stay on top and never need to search for them. The card info widget also updates the card art while not beeing the active window when undocked. I just realized it and it would be awesome for live debugging! 

It could be hidden/disabled by default and opened the same as the logger now. With defaulting to undocked window mode, so it feels and looks more or less the same as a normal window.

Thoughts @ctrlaltca ?

**Comment by ctrlaltca** [comment]
In order to make it a dock, it should be a child of a specific tab, and you'll be able to only dock it inside that tab.
