### PR TITLE
oracle: fix broken import of sets; fix #1188

### LINKED ISSUE #1188: Oracle Parsing Issues
These issues came about from #1162.

It seems as if Oracle is now parsing **every card** to only have one set, which appears to be the latest set. For example:

OLD:
```
<card>
    <name>Acidic Sliver</name>
    <set muId="207897">H09</set>
    <set muId="5108">STH</set>
    <set muId="397564">TPR</set>
    <color>B</color>
    <color>R</color>
    <manacost>BR</manacost>
    <cmc>2</cmc>
    <type>Creature — Sliver</type>
    <pt>2/2</pt>
    <tablerow>2</tablerow>
    <text>All Slivers have &quot;{2}, Sacrifice this permanent: This permanent deals 2 damage to target creature or player.&quot;</text>
</card>
```
NEW:
```
<card>
    <name>Acidic Sliver</name>
    <set muId="397564">TPR</set>
    <color>B</color>
    <color>R</color>
    <manacost>BR</manacost>
    <cmc>2</cmc>
    <type>Creature — Sliver</type>
    <pt>2/2</pt>
    <tablerow>2</tablerow>
    <text>All Slivers have &quot;{2}, Sacrifice this permanent: This permanent deals 2 damage to target creature or player.&quot;</text>
</card>
```

I haven't seen any other issues occur with the parsing as of this moment, but I will conduct further testing throughout the night.

### PR DESCRIPTION
**Pull request by ctrlaltca**

### CODE REVIEW

File: oracle/src/oracleimporter.cpp [hunk 1]
```diff
@@ -190,6 +195,12 @@ int OracleImporter::importTextSpoiler(CardSet *set, const QVariant &data)
         CardInfo *card = addCard(set->getShortName(), cardName, false, cardId, cardCost, cmc, cardType, cardPT, cardLoyalty, cardText, colors, relatedCards, upsideDown);
 
         if (!set->contains(card)) {
+
+        if(cardName=="Mountain")
```
Comment (woogerboy21) [inline oracle/src/oracleimporter.cpp]: Is this check used for anything or just left over from troubleshooting?

**Comment by ctrlaltca** [comment]
@woogerboy21 nice catch, thank you

**Comment by ZeldaZach** [comment]
I made the catch 😝 but yeah, no problem. I should've seen this before merging initially.

File: oracle/src/oracleimporter.cpp [hunk 2]
```diff
@@ -76,33 +76,38 @@ CardInfo *OracleImporter::addCard(const QString &setName,
...
+
+        // detect mana generator artifacts
+        bool mArtifact = false;
+        if (cardType.endsWith("Artifact"))
+            for (int i = 0; i < cardTextRows.size(); ++i)
+                if (cardTextRows[i].contains("{T}") && cardTextRows[i].contains("to your mana pool"))
+                    mArtifact = true;
+
+        // detect cards that enter the field tapped
+        bool cipt = cardText.contains("Hideaway") || (cardText.contains(cardName + " enters the battlefield tapped") && !cardText.contains(cardName + " enters the battlefield tapped unless"));
```
Comment (Daenyth) [inline oracle/src/oracleimporter.cpp]: It occurs to me that this will fail for a case like:

```
Dudebro, the man of the very long cardname
Dudebro enters the battlefield tapped
```

I'm not sure any such card exists right now, or if we care even if it does.

Comment (ctrlaltca) [inline oracle/src/oracleimporter.cpp]: There are currently 632 cards with containing the "enters the battlefield tapped" text, most of them are duplicates so we end up with only 259 unique cards containing that string.
None of them contains a shortened version of the card name. Some of them contains other text (eg. hideaway lands use "this land" instead of the card name). The longest name i found is "Valakut, the Molten Pinnacle"
So there's no problem here, at least until now.

Comment (Daenyth) [inline oracle/src/oracleimporter.cpp]: I didn't think so, just pointing out a potential for later. :+1:

**Comment by woogerboy21** [comment]
We should probably commit this if its been tested.

**Comment by ZeldaZach** [comment]
I'll do testing right now and make my call on committment(s).
