### PR TITLE
Multiple bg images zone

### LINKED ISSUE #3998: the default tablezone tablezone.jpg, all players is not being honored in multiplayer (spectating)
existing themes broken https://github.com/Cockatrice/Cockatrice/pull/3990
according to the PR i think the behavior should be
tablezone.jpg | default, all players
tablezone0.jpg | ignored
tablezone1.jpg | Player 1
tablezone2.jpg | Player 2
tablezone3.jpg | Player 3
?

## * Edit - the screenshots below are while spectating games

1.
However the default tablezone  `tablezone.jpg | default, all players` is not being honored.
the existing themes at https://github.com/Cockatrice/Cockatrice/wiki/Themes are broken in multiplayer Kitchen Table - by Yami | Screenshots
image

---
2. 
Aalso, i created a grey bg and made the following copies:
```
tablezone.png
tablezone0.png  
tablezone1.png  
tablezone2.png 
tablezone3.png  
tablezone4.png  
```
And in a 3-player game the grey bg is not used for one of the tablezones and it purple when it should be grey.
image

### PR DESCRIPTION
**Pull request by fdipilla**
## Related Ticket(s)
- Fixes #3998 linked to #3985

## Short roundup of the initial problem
Give the user the possibility of using multiple background images for each player

## What will change with this Pull Request?
- Instead of trying to use the player id to load the background image I added a new property to the player called zoneId
- Small fix so the zones default correctly
- Now tablezone1.jpg is contemplated so the images are loaded this way

| image | effect |
| -- | -- |
| tablezone.jpg | default, all players |
| tablezone0.jpg | ignored |
| tablezone1.jpg | Player 1 |
| tablezone2.jpg | Player 2 |
| tablezone3.jpg | Player 3 |
| tablezoneN.jpg | Player N |

### CODE REVIEW

File: cockatrice/src/tab_game.cpp [hunk 1]
```diff
@@ -802,6 +802,27 @@ Player *TabGame::addPlayer(int playerId, const ServerInfo_User &info)
     gameMenu->insertMenu(playersSeparator, newPlayer->getPlayerMenu());
 
     players.insert(playerId, newPlayer);
+
+    int i = 1;
```
Comment (ebbit1q) [inline cockatrice/src/tab_game.cpp:806]: declare in for statement

File: cockatrice/src/tab_game.cpp [hunk 2]
```diff
@@ -802,6 +802,27 @@ Player *TabGame::addPlayer(int playerId, const ServerInfo_User &info)
...
+    // Loop for each player, the idea is to have one assigned zone for each non-spectator player
+    for (i = 1; i <= players.count(); ++i) {
+        bool aPlayerHasThisZone = false;
+        QMapIterator<int, Player *> playerIterator(players);
+        while (playerIterator.hasNext()) {
```
Comment (ebbit1q) [inline cockatrice/src/tab_game.cpp:811]: we prefer `for (auto &item : array)` loops over java style iterators in new pull requests

File: cockatrice/src/tab_game.cpp [hunk 3]
```diff
@@ -802,6 +802,27 @@ Player *TabGame::addPlayer(int playerId, const ServerInfo_User &info)
...
+                aPlayerHasThisZone = true;
+            }
+        }
+        // If no player has this zone number break the loop and assign it
+        if (!aPlayerHasThisZone) {
+            break;
+        }
+    }
+
+    if (!spectators.contains(playerId)) {
```
Comment (ebbit1q) [inline cockatrice/src/tab_game.cpp:822]: this check can be done earlier I think

File: cockatrice/src/thememanager.cpp [hunk 4]
```diff
@@ -107,3 +121,8 @@ void ThemeManager::themeChangedSlot()
 
     emit themeChanged();
 }
+
+QBrush ThemeManager::getExtraTableBgBrush(QString extraNumber, QBrush fallbackBrush)
```
Comment (ebbit1q) [inline cockatrice/src/thememanager.cpp:125]: You should use references with & for these functions.

File: cockatrice/src/thememanager.cpp [hunk 5]
```diff
@@ -107,3 +121,8 @@ void ThemeManager::themeChangedSlot()
...
+{
+    return loadExtraBrush(TABLEZONE_BG_NAME + extraNumber, fallbackBrush);
```
Comment (ebbit1q) [inline cockatrice/src/thememanager.cpp:127]: it'd be preferable to store these in an array or map instead of needing to load them repeatedly.

File: cockatrice/src/tab_game.cpp (hunk 1 above)
Comment (fdipilla) [reply cockatrice/src/tab_game.cpp:806]: I use it a few lines below for this `newPlayer->setZoneId(i);`, maybe should I give the variable a more  significant name?

Comment (ebbit1q) [reply cockatrice/src/tab_game.cpp:806]: no you should move that inside the loop

**Comment by ZeldaZach** [comment]
Hey @fdipilla thanks for helping to improve on Cockatrice! I feel this is a duplicate of PR #3990 so I'll be closing it for now, but if you find there's more to bring to the table please let us know!

Feel free to reach out at https://cockatrice.us/discord anytime :)

**Comment by tooomm** [comment]
It's also mentioned in the wiki docs 👍

**Comment by ebbit1q** [comment]
I honestly thought this was already merged months ago....

**Comment by tooomm** [comment]
The first version was. https://github.com/Cockatrice/Cockatrice/pull/3990

**Comment by ebbit1q** [comment]
I know, and I thought this fix was already added
